// Code generated by qtc from "archived_cases.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/archived_cases.qtpl:4
package views

//line views/archived_cases.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/archived_cases.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/archived_cases.qtpl:5
type ArchivedCasesPage struct {
	BasePage
	WorktreeName string
}

//line views/archived_cases.qtpl:11
func (p *ArchivedCasesPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/archived_cases.qtpl:11
	qw422016.N().S(`
`)
//line views/archived_cases.qtpl:12
	p.StreamHeader(qw422016)
//line views/archived_cases.qtpl:12
	qw422016.N().S(`

<link href="/static/css/cases.css" rel="stylesheet">

<div class="archived-cases" data-worktree-name="`)
//line views/archived_cases.qtpl:16
	qw422016.E().S(p.WorktreeName)
//line views/archived_cases.qtpl:16
	qw422016.N().S(`">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="mb-0"><i class="fa-solid fa-box-archive"></i> Archived cases <small class="text-muted">— `)
//line views/archived_cases.qtpl:18
	qw422016.E().S(p.WorktreeName)
//line views/archived_cases.qtpl:18
	qw422016.N().S(`</small></h2>
        <a href="/worktree/`)
//line views/archived_cases.qtpl:19
	qw422016.E().S(p.WorktreeName)
//line views/archived_cases.qtpl:19
	qw422016.N().S(`" class="btn btn-outline-secondary btn-sm">
            <i class="fa-solid fa-arrow-left"></i> Back
        </a>
    </div>

    <form id="archivedSearchForm" class="row g-2 mb-3" onsubmit="runArchivedSearch(event)">
        <div class="col-md-5">
            <input type="text" id="searchQ" class="form-control" placeholder="Search title, summary, keywords, components, commits, notes…">
        </div>
        <div class="col-md-2">
            <select id="searchKind" class="form-select">
                <option value="">All kinds</option>
                <option value="bug">Bug</option>
                <option value="feature">Feature</option>
                <option value="investigation">Investigation</option>
                <option value="task">Task</option>
            </select>
        </div>
        <div class="col-md-2">
            <input type="date" id="searchFrom" class="form-control" placeholder="From">
        </div>
        <div class="col-md-2">
            <input type="date" id="searchTo" class="form-control" placeholder="To">
        </div>
        <div class="col-md-1 d-grid">
            <button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass"></i></button>
        </div>
    </form>

    <div class="d-flex justify-content-between align-items-center mb-2">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="searchHasTraces">
            <label class="form-check-label" for="searchHasTraces">Has linked traces</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="searchTranscripts">
            <label class="form-check-label" for="searchTranscripts">Also search transcripts (slow)</label>
        </div>
        <div class="ms-auto">
            <label class="form-label me-2 mb-0">Sort by</label>
            <select id="searchSort" class="form-select form-select-sm d-inline-block" style="width: auto;" onchange="runArchivedSearch()">
                <option value="date">Date</option>
                <option value="kind">Kind</option>
                <option value="duration">Duration</option>
                <option value="worktree">Worktree</option>
            </select>
        </div>
    </div>

    <div id="archivedResults">
        <div class="text-muted">Loading…</div>
    </div>
</div>

<script>
var WORKTREE_NAME = '`)
//line views/archived_cases.qtpl:74
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/archived_cases.qtpl:74
	qw422016.N().S(`';

function initArchivedCasesPage() {
    runArchivedSearch();
}
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initArchivedCasesPage);
} else {
    initArchivedCasesPage();
}

function runArchivedSearch(ev) {
    if (ev) ev.preventDefault();
    var qs = new URLSearchParams();
    var q = document.getElementById('searchQ').value.trim();
    if (q) qs.set('q', q);
    var kind = document.getElementById('searchKind').value;
    if (kind) qs.set('kind', kind);
    var from = document.getElementById('searchFrom').value;
    if (from) qs.set('from', from);
    var to = document.getElementById('searchTo').value;
    if (to) qs.set('to', to);
    if (document.getElementById('searchHasTraces').checked) qs.set('has_traces', '1');
    if (document.getElementById('searchTranscripts').checked) qs.set('include_transcripts', '1');
    qs.set('sort', document.getElementById('searchSort').value);

    var el = document.getElementById('archivedResults');
    el.innerHTML = '<div class="text-muted">Searching…</div>';

    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/archived/search?' + qs.toString())
        .then(function(r) { return r.json(); })
        .then(function(d) { renderArchivedResults((d.data || d) || []); })
        .catch(function(err) {
            el.innerHTML = '<div class="alert alert-danger">Search failed: ' + escapeArchivedHtml(String(err)) + '</div>';
        });
}

function renderArchivedResults(results) {
    var el = document.getElementById('archivedResults');
    if (!results || results.length === 0) {
        el.innerHTML = '<div class="text-muted p-3">No archived cases match.</div>';
        return;
    }
    var html = '<div class="list-group">';
    results.forEach(function(r) {
        var href = '/case/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(r.id);
        var date = r.created_at ? new Date(r.created_at).toLocaleDateString() : '';
        html += '<a href="' + href + '" class="list-group-item list-group-item-action">';
        html += '<div class="d-flex justify-content-between">';
        html += '<div>';
        html += '<span class="badge case-kind-' + escapeArchivedAttr(r.kind) + ' me-2">' + escapeArchivedHtml(r.kind) + '</span>';
        html += '<strong>' + escapeArchivedHtml(r.title) + '</strong>';
        if (r.summary && r.summary.synopsis) {
            html += '<div class="text-muted small mt-1">' + escapeArchivedHtml(r.summary.synopsis) + '</div>';
        }
        if (r.snippet) {
            html += '<div class="text-muted small fst-italic">' + escapeArchivedHtml(r.snippet) + '</div>';
        }
        if (r.summary) {
            var chips = [];
            (r.summary.components || []).forEach(function(c) { chips.push('<span class="badge bg-info me-1">' + escapeArchivedHtml(c) + '</span>'); });
            (r.summary.keywords || []).forEach(function(k) { chips.push('<span class="badge bg-secondary me-1">' + escapeArchivedHtml(k) + '</span>'); });
            if (chips.length > 0) html += '<div class="mt-1">' + chips.join('') + '</div>';
        }
        html += '</div>';
        html += '<div class="text-muted small">' + escapeArchivedHtml(date) + '</div>';
        html += '</div>';
        html += '</a>';
    });
    html += '</div>';
    el.innerHTML = html;
}

function escapeArchivedHtml(s) {
    var d = document.createElement('div');
    d.textContent = String(s == null ? '' : s);
    return d.innerHTML;
}
function escapeArchivedAttr(s) {
    return escapeArchivedHtml(s).replace(/"/g, '&quot;');
}
</script>

`)
//line views/archived_cases.qtpl:157
	p.StreamFooter(qw422016)
//line views/archived_cases.qtpl:157
	qw422016.N().S(`
`)
//line views/archived_cases.qtpl:158
}

//line views/archived_cases.qtpl:158
func (p *ArchivedCasesPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/archived_cases.qtpl:158
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/archived_cases.qtpl:158
	p.StreamRender(qw422016)
//line views/archived_cases.qtpl:158
	qt422016.ReleaseWriter(qw422016)
//line views/archived_cases.qtpl:158
}

//line views/archived_cases.qtpl:158
func (p *ArchivedCasesPage) Render() string {
//line views/archived_cases.qtpl:158
	qb422016 := qt422016.AcquireByteBuffer()
//line views/archived_cases.qtpl:158
	p.WriteRender(qb422016)
//line views/archived_cases.qtpl:158
	qs422016 := string(qb422016.B)
//line views/archived_cases.qtpl:158
	qt422016.ReleaseByteBuffer(qb422016)
//line views/archived_cases.qtpl:158
	return qs422016
//line views/archived_cases.qtpl:158
}
