// Code generated by qtc from "case_detail.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/case_detail.qtpl:4
package views

//line views/case_detail.qtpl:4
import "encoding/json"

//line views/case_detail.qtpl:5
import "github.com/wingedpig/trellis/internal/cases"

//line views/case_detail.qtpl:6
import "strings"

//line views/case_detail.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/case_detail.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/case_detail.qtpl:9
type CaseDetailPage struct {
	BasePage
	WorktreeName string
	Case         *cases.CaseJSON
	Notes        string
	Traces       []cases.CaseTraceSummary
}

//line views/case_detail.qtpl:18
func (p *CaseDetailPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/case_detail.qtpl:18
	qw422016.N().S(`
`)
//line views/case_detail.qtpl:19
	p.StreamHeader(qw422016)
//line views/case_detail.qtpl:19
	qw422016.N().S(`

<link href="/static/css/cases.css" rel="stylesheet">

<div class="case-detail">
    <div class="case-header mb-4">
        <div class="d-flex justify-content-between align-items-start">
            <div>
                <h2>`)
//line views/case_detail.qtpl:27
	qw422016.E().S(p.Case.Title)
//line views/case_detail.qtpl:27
	qw422016.N().S(`</h2>
                <div class="case-meta mt-2">
                    <span class="badge case-kind-`)
//line views/case_detail.qtpl:29
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:29
	qw422016.N().S(`">`)
//line views/case_detail.qtpl:29
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:29
	qw422016.N().S(`</span>
                    <span class="badge case-status-`)
//line views/case_detail.qtpl:30
	qw422016.E().S(p.Case.Status)
//line views/case_detail.qtpl:30
	qw422016.N().S(`">`)
//line views/case_detail.qtpl:30
	qw422016.E().S(p.Case.Status)
//line views/case_detail.qtpl:30
	qw422016.N().S(`</span>
                    <span class="text-muted ms-2">
                        <i class="fa-solid fa-calendar"></i> `)
//line views/case_detail.qtpl:32
	qw422016.E().S(p.Case.CreatedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:32
	qw422016.N().S(`
                    </span>
                    `)
//line views/case_detail.qtpl:34
	if !p.Case.UpdatedAt.Equal(p.Case.CreatedAt) {
//line views/case_detail.qtpl:34
		qw422016.N().S(`
                    <span class="text-muted ms-2">
                        <i class="fa-solid fa-clock"></i> Updated `)
//line views/case_detail.qtpl:36
		qw422016.E().S(p.Case.UpdatedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:36
		qw422016.N().S(`
                    </span>
                    `)
//line views/case_detail.qtpl:38
	}
//line views/case_detail.qtpl:38
	qw422016.N().S(`
                </div>
            </div>
            <div class="case-actions">
                <a href="/worktree/`)
//line views/case_detail.qtpl:42
	qw422016.E().S(p.WorktreeName)
//line views/case_detail.qtpl:42
	qw422016.N().S(`" class="btn btn-outline-secondary btn-sm">
                    <i class="fa-solid fa-arrow-left"></i> Back
                </a>
                `)
//line views/case_detail.qtpl:45
	if p.Case.Status != "archived" {
//line views/case_detail.qtpl:45
		qw422016.N().S(`
                <button class="btn btn-outline-primary btn-sm" onclick="showWrapUpModal()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
                <button class="btn btn-outline-warning btn-sm" onclick="archiveCase()">
                    <i class="fa-solid fa-box-archive"></i> Archive
                </button>
                `)
//line views/case_detail.qtpl:52
	} else {
//line views/case_detail.qtpl:52
		qw422016.N().S(`
                <button class="btn btn-outline-success btn-sm" onclick="reopenCase()">
                    <i class="fa-solid fa-box-open"></i> Reopen
                </button>
                `)
//line views/case_detail.qtpl:56
	}
//line views/case_detail.qtpl:56
	qw422016.N().S(`
                <button class="btn btn-outline-danger btn-sm" onclick="deleteCase()">
                    <i class="fa-solid fa-trash"></i> Delete
                </button>
            </div>
        </div>
    </div>

    <div class="case-section mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><i class="fa-solid fa-link"></i> Links</h4>
            <button class="btn btn-outline-secondary btn-sm" onclick="showAddLink()">
                <i class="fa-solid fa-plus"></i> Add
            </button>
        </div>
        <ul id="links-list" class="list-unstyled mt-2"></ul>
        <div id="link-add-form" class="case-link-add-form mt-2" style="display:none">
            <input type="text" id="link-title" class="form-control form-control-sm mb-2" placeholder="Title">
            <input type="url" id="link-url" class="form-control form-control-sm mb-2" placeholder="https://...">
            <div>
                <button class="btn btn-primary btn-sm" onclick="addLink()">
                    <i class="fa-solid fa-check"></i> Save
                </button>
                <button class="btn btn-outline-secondary btn-sm ms-1" onclick="cancelAddLink()">
                    Cancel
                </button>
            </div>
        </div>
    </div>

    `)
//line views/case_detail.qtpl:86
	if len(p.Case.Evidence) > 0 {
//line views/case_detail.qtpl:86
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-file-lines"></i> Evidence</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:90
		for _, ev := range p.Case.Evidence {
//line views/case_detail.qtpl:90
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <strong>`)
//line views/case_detail.qtpl:93
			qw422016.E().S(ev.Title)
//line views/case_detail.qtpl:93
			qw422016.N().S(`</strong>
                    <span class="badge bg-secondary ms-2">`)
//line views/case_detail.qtpl:94
			qw422016.E().S(ev.Format)
//line views/case_detail.qtpl:94
			qw422016.N().S(`</span>
                    `)
//line views/case_detail.qtpl:95
			for _, tag := range ev.Tags {
//line views/case_detail.qtpl:95
				qw422016.N().S(`
                    <span class="badge bg-info ms-1">`)
//line views/case_detail.qtpl:96
				qw422016.E().S(tag)
//line views/case_detail.qtpl:96
				qw422016.N().S(`</span>
                    `)
//line views/case_detail.qtpl:97
			}
//line views/case_detail.qtpl:97
			qw422016.N().S(`
                </div>
                <span class="text-muted">`)
//line views/case_detail.qtpl:99
			qw422016.E().S(ev.AddedAt.Format("2006-01-02"))
//line views/case_detail.qtpl:99
			qw422016.N().S(`</span>
            </div>
            `)
//line views/case_detail.qtpl:101
		}
//line views/case_detail.qtpl:101
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:104
	}
//line views/case_detail.qtpl:104
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:106
	if len(p.Case.Claude) > 0 {
//line views/case_detail.qtpl:106
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-robot"></i> Transcripts</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:110
		for _, ref := range p.Case.Claude {
//line views/case_detail.qtpl:110
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <div>
                        <strong>`)
//line views/case_detail.qtpl:114
			qw422016.E().S(ref.Title)
//line views/case_detail.qtpl:114
			qw422016.N().S(`</strong>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:115
			qw422016.N().D(ref.MessageCount)
//line views/case_detail.qtpl:115
			qw422016.N().S(` messages</span>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:116
			qw422016.E().S(ref.ExportedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:116
			qw422016.N().S(`</span>
                        `)
//line views/case_detail.qtpl:117
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:117
				qw422016.N().S(`
                        <span class="text-warning ms-2" title="The live session has more messages than this saved transcript">
                            <i class="fa-solid fa-circle-exclamation"></i> `)
//line views/case_detail.qtpl:119
				qw422016.N().D(ref.CurrentMessageCount - ref.MessageCount)
//line views/case_detail.qtpl:119
				qw422016.N().S(` new messages
                        </span>
                        `)
//line views/case_detail.qtpl:121
			} else if ref.CurrentMessageCount == -1 {
//line views/case_detail.qtpl:121
				qw422016.N().S(`
                        <span class="text-muted ms-2" title="The source session has been deleted">
                            <i class="fa-solid fa-circle-xmark"></i> session deleted
                        </span>
                        `)
//line views/case_detail.qtpl:125
			}
//line views/case_detail.qtpl:125
			qw422016.N().S(`
                    </div>
                    `)
//line views/case_detail.qtpl:127
			if ref.Preview != "" {
//line views/case_detail.qtpl:127
				qw422016.N().S(`
                    <div class="text-muted small text-truncate" style="max-width: 600px;">`)
//line views/case_detail.qtpl:128
				qw422016.E().S(ref.Preview)
//line views/case_detail.qtpl:128
				qw422016.N().S(`</div>
                    `)
//line views/case_detail.qtpl:129
			}
//line views/case_detail.qtpl:129
			qw422016.N().S(`
                </div>
                <div class="d-flex gap-1">
                    `)
//line views/case_detail.qtpl:132
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:132
				qw422016.N().S(`
                    <button class="btn btn-outline-warning btn-sm" onclick="updateTranscript('`)
//line views/case_detail.qtpl:133
				qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:133
				qw422016.N().S(`')" title="Update transcript with latest messages">
                        <i class="fa-solid fa-rotate"></i> Update
                    </button>
                    `)
//line views/case_detail.qtpl:136
			}
//line views/case_detail.qtpl:136
			qw422016.N().S(`
                    <button class="btn btn-outline-primary btn-sm" onclick="continueTranscript('`)
//line views/case_detail.qtpl:137
			qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:137
			qw422016.N().S(`')">
                        <i class="fa-solid fa-play"></i> Continue
                    </button>
                </div>
            </div>
            `)
//line views/case_detail.qtpl:142
		}
//line views/case_detail.qtpl:142
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:145
	}
//line views/case_detail.qtpl:145
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:147
	if len(p.Traces) > 0 {
//line views/case_detail.qtpl:147
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-magnifying-glass"></i> Traces</h4>
        <div class="list-group" id="traces-list">
            `)
//line views/case_detail.qtpl:151
		for _, tr := range p.Traces {
//line views/case_detail.qtpl:151
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center" id="trace-`)
//line views/case_detail.qtpl:152
			qw422016.E().S(tr.ID)
//line views/case_detail.qtpl:152
			qw422016.N().S(`">
                <a href="/case/`)
//line views/case_detail.qtpl:153
			qw422016.E().S(p.WorktreeName)
//line views/case_detail.qtpl:153
			qw422016.N().S(`/`)
//line views/case_detail.qtpl:153
			qw422016.E().S(p.Case.ID)
//line views/case_detail.qtpl:153
			qw422016.N().S(`/trace/`)
//line views/case_detail.qtpl:153
			qw422016.E().S(tr.ID)
//line views/case_detail.qtpl:153
			qw422016.N().S(`" class="text-decoration-none flex-grow-1">
                    <strong>`)
//line views/case_detail.qtpl:154
			qw422016.E().S(tr.Name)
//line views/case_detail.qtpl:154
			qw422016.N().S(`</strong>
                    <span class="text-muted ms-2"><code>`)
//line views/case_detail.qtpl:155
			qw422016.E().S(tr.TraceID)
//line views/case_detail.qtpl:155
			qw422016.N().S(`</code></span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:156
			qw422016.E().S(tr.Group)
//line views/case_detail.qtpl:156
			qw422016.N().S(`</span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:157
			qw422016.N().D(tr.EntryCount)
//line views/case_detail.qtpl:157
			qw422016.N().S(` entries</span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:158
			qw422016.E().S(tr.SavedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:158
			qw422016.N().S(`</span>
                </a>
                <button class="btn btn-outline-danger btn-sm ms-2" onclick="deleteTrace('`)
//line views/case_detail.qtpl:160
			qw422016.E().S(JSAttr(tr.ID))
//line views/case_detail.qtpl:160
			qw422016.N().S(`')" title="Remove trace">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </div>
            `)
//line views/case_detail.qtpl:164
		}
//line views/case_detail.qtpl:164
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:167
	}
//line views/case_detail.qtpl:167
	qw422016.N().S(`

    <div class="case-section mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><i class="fa-solid fa-note-sticky"></i> Notes</h4>
            <div id="notes-view-actions">
                <button class="btn btn-outline-secondary btn-sm" onclick="editNotes()">
                    <i class="fa-solid fa-pen"></i> Edit
                </button>
            </div>
            <div id="notes-edit-actions" style="display:none">
                <button class="btn btn-primary btn-sm" onclick="saveNotes()">
                    <i class="fa-solid fa-check"></i> Save
                </button>
                <button class="btn btn-outline-secondary btn-sm ms-1" onclick="cancelEditNotes()">
                    Cancel
                </button>
            </div>
        </div>
        <div id="notes-view" class="mt-2">
            <div id="case-notes" class="case-notes-content"></div>
        </div>
        <div id="notes-edit" class="mt-2" style="display:none">
            <textarea id="notes-textarea" class="case-notes-textarea"></textarea>
        </div>
    </div>
</div>

<script>
const WORKTREE_NAME = '`)
//line views/case_detail.qtpl:196
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/case_detail.qtpl:196
	qw422016.N().S(`';
const CASE_ID = '`)
//line views/case_detail.qtpl:197
	qw422016.E().S(JSAttr(p.Case.ID))
//line views/case_detail.qtpl:197
	qw422016.N().S(`';
let CASE_NOTES_RAW = `)
//line views/case_detail.qtpl:198
	qw422016.N().S(notesJSONSafe(p.Notes))
//line views/case_detail.qtpl:198
	qw422016.N().S(`;
let CASE_LINKS = `)
//line views/case_detail.qtpl:199
	qw422016.N().S(linksJSONSafe(p.Case.Links))
//line views/case_detail.qtpl:199
	qw422016.N().S(`;

document.addEventListener('DOMContentLoaded', function() {
    renderNotes();
    renderLinks();
});

function renderNotes() {
    var el = document.getElementById('case-notes');
    if (CASE_NOTES_RAW && typeof marked !== 'undefined') {
        el.innerHTML = marked.parse(CASE_NOTES_RAW);
        el.style.display = '';
    } else {
        el.innerHTML = '<span class="text-muted">No notes yet.</span>';
    }
}

function editNotes() {
    document.getElementById('notes-view').style.display = 'none';
    document.getElementById('notes-view-actions').style.display = 'none';
    document.getElementById('notes-edit').style.display = '';
    document.getElementById('notes-edit-actions').style.display = '';
    document.getElementById('notes-textarea').value = CASE_NOTES_RAW || '';
    document.getElementById('notes-textarea').focus();
}

function cancelEditNotes() {
    document.getElementById('notes-edit').style.display = 'none';
    document.getElementById('notes-edit-actions').style.display = 'none';
    document.getElementById('notes-view').style.display = '';
    document.getElementById('notes-view-actions').style.display = '';
}

function saveNotes() {
    var text = document.getElementById('notes-textarea').value;
    var btn = document.querySelector('#notes-edit-actions .btn-primary');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Saving...';
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({notes: text})
    })
    .then(function(resp) {
        if (!resp.ok) throw new Error('Save failed');
        CASE_NOTES_RAW = text;
        renderNotes();
        cancelEditNotes();
    })
    .catch(function(err) { alert('Save failed: ' + err); })
    .finally(function() {
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-check"></i> Save';
    });
}

function renderLinks() {
    var el = document.getElementById('links-list');
    if (!CASE_LINKS || CASE_LINKS.length === 0) {
        el.innerHTML = '<li class="text-muted">No links yet.</li>';
        return;
    }
    el.innerHTML = CASE_LINKS.map(function(link, i) {
        return '<li class="case-link-item">' +
            '<a href="' + escapeAttr(link.url) + '" target="_blank" rel="noopener">' + escapeHTML(link.title) + '</a>' +
            '<button class="btn btn-outline-danger btn-sm case-link-delete" onclick="deleteLink(' + i + ')" title="Remove link">' +
            '<i class="fa-solid fa-xmark"></i></button>' +
            '</li>';
    }).join('');
}

function escapeHTML(s) {
    var d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML;
}

function escapeAttr(s) {
    var d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML.replace(/"/g, '&quot;');
}

function showAddLink() {
    document.getElementById('link-add-form').style.display = '';
    document.getElementById('link-title').focus();
}

function cancelAddLink() {
    document.getElementById('link-add-form').style.display = 'none';
    document.getElementById('link-title').value = '';
    document.getElementById('link-url').value = '';
}

function addLink() {
    var title = document.getElementById('link-title').value.trim();
    var url = document.getElementById('link-url').value.trim();
    if (!title || !url) { alert('Title and URL are required.'); return; }
    CASE_LINKS.push({title: title, url: url});
    patchLinks()
        .then(function() { renderLinks(); cancelAddLink(); })
        .catch(function(err) { CASE_LINKS.pop(); alert('Save failed: ' + err); });
}

function deleteLink(index) {
    var removed = CASE_LINKS.splice(index, 1)[0];
    patchLinks()
        .then(function() { renderLinks(); })
        .catch(function(err) { CASE_LINKS.splice(index, 0, removed); alert('Delete failed: ' + err); });
}

function patchLinks() {
    return fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({links: CASE_LINKS})
    }).then(function(resp) {
        if (!resp.ok) throw new Error('Save failed');
    });
}

function archiveCase() {
    if (!confirm('Archive this case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/archive', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Archive failed');
        window.location.href = '/worktree/' + encodeURIComponent(WORKTREE_NAME);
    })
    .catch(err => alert('Archive failed: ' + err));
}

function reopenCase() {
    if (!confirm('Reopen this case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/reopen', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Reopen failed');
        window.location.reload();
    })
    .catch(err => alert('Reopen failed: ' + err));
}

function deleteCase() {
    if (!confirm('Permanently delete this case? This cannot be undone.')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'DELETE'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Delete failed');
        window.location.href = '/worktree/' + encodeURIComponent(WORKTREE_NAME);
    })
    .catch(err => alert('Delete failed: ' + err));
}

function deleteTrace(traceId) {
    if (!confirm('Remove this trace from the case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/trace/' + encodeURIComponent(traceId), {
        method: 'DELETE'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Delete failed');
        var el = document.getElementById('trace-' + traceId);
        if (el) el.remove();
    })
    .catch(err => alert('Delete failed: ' + err));
}

function updateTranscript(claudeId) {
    var btn = event.target.closest('button');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Updating...';
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/transcript/' + encodeURIComponent(claudeId), {
        method: 'PUT'
    })
    .then(resp => {
        if (!resp.ok) return resp.json().then(d => { throw new Error(d.error?.message || 'Update failed'); });
        window.location.reload();
    })
    .catch(err => {
        alert('Update failed: ' + err);
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-rotate"></i> Update';
    });
}

function continueTranscript(claudeId) {
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/transcript/' + encodeURIComponent(claudeId) + '/continue', {
        method: 'POST'
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Continue failed'); });
        return r.json();
    })
    .then(data => {
        const sess = data.data || data;
        window.location.href = '/claude/' + encodeURIComponent(WORKTREE_NAME) + '/' + sess.id;
    })
    .catch(err => alert('Continue failed: ' + err));
}
</script>

<script>
const WRAPUP_WORKTREE = WORKTREE_NAME;
const WRAPUP_SESSION_ID = null;
const WRAPUP_CASE = {id: CASE_ID, title: `)
//line views/case_detail.qtpl:406
	qw422016.N().S(notesJSONSafe(p.Case.Title))
//line views/case_detail.qtpl:406
	qw422016.N().S(`, kind: '`)
//line views/case_detail.qtpl:406
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:406
	qw422016.N().S(`'};
</script>

<!-- Wrap Up Modal -->
<div class="modal fade" id="wrapUpModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-flag-checkered"></i> Wrap Up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div id="wrapUpError" class="alert alert-danger" style="display:none"></div>
                <div id="wrapUpSuccess" class="alert alert-success" style="display:none"></div>

                <!-- Existing case info (read-only) -->
                <div id="wrapUpCaseInfo" style="display:none" class="mb-3">
                    <div class="card card-body bg-light">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-secondary" id="wrapUpCaseKind"></span>
                            <strong id="wrapUpCaseTitle"></strong>
                            <code class="ms-auto" id="wrapUpCaseId"></code>
                        </div>
                    </div>
                </div>

                <!-- New case fields (editable) -->
                <div id="wrapUpNewCase" style="display:none">
                    <div class="mb-3">
                        <label for="wrapUpNewTitle" class="form-label">Case Title</label>
                        <input type="text" class="form-control" id="wrapUpNewTitle" placeholder="Fix login bug" oninput="updateWrapUpCommitMsg()">
                    </div>
                    <div class="mb-3">
                        <label for="wrapUpNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="wrapUpNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>

                <!-- Files -->
                <div class="mb-3">
                    <label class="form-label">Files to commit</label>
                    <div id="wrapUpFileList" class="wrap-up-file-list"></div>
                </div>

                <!-- Commit message -->
                <div class="mb-3">
                    <label for="wrapUpCommitMsg" class="form-label">Commit message</label>
                    <textarea class="form-control" id="wrapUpCommitMsg" rows="3"></textarea>
                </div>

                <!-- Links -->
                <div class="mb-3">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <label class="form-label mb-0">Links (optional)</label>
                        <button class="btn btn-outline-secondary btn-sm" type="button" onclick="addWrapUpLink()">
                            <i class="fa-solid fa-plus"></i> Add
                        </button>
                    </div>
                    <div id="wrapUpLinks"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="wrapUpConfirmBtn" onclick="wrapUpConfirm()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
            </div>
        </div>
    </div>
</div>

<link href="/static/css/claude.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.1/marked.min.js"></script>
<script src="/static/js/wrapup.js"></script>
<script src="/static/js/workflow_picker.js"></script>

`)
//line views/case_detail.qtpl:487
	p.StreamFooter(qw422016)
//line views/case_detail.qtpl:487
	qw422016.N().S(`
`)
//line views/case_detail.qtpl:488
}

//line views/case_detail.qtpl:488
func (p *CaseDetailPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/case_detail.qtpl:488
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/case_detail.qtpl:488
	p.StreamRender(qw422016)
//line views/case_detail.qtpl:488
	qt422016.ReleaseWriter(qw422016)
//line views/case_detail.qtpl:488
}

//line views/case_detail.qtpl:488
func (p *CaseDetailPage) Render() string {
//line views/case_detail.qtpl:488
	qb422016 := qt422016.AcquireByteBuffer()
//line views/case_detail.qtpl:488
	p.WriteRender(qb422016)
//line views/case_detail.qtpl:488
	qs422016 := string(qb422016.B)
//line views/case_detail.qtpl:488
	qt422016.ReleaseByteBuffer(qb422016)
//line views/case_detail.qtpl:488
	return qs422016
//line views/case_detail.qtpl:488
}

// notesJSONSafe returns the notes as a JSON-encoded string safe for embedding in a <script> tag.
//
//line views/case_detail.qtpl:491
func notesJSONSafe(s string) string {
	// JSON encode the string (handles escaping quotes, newlines, etc.)
	b, _ := json.Marshal(s)
	// Replace </script to prevent XSS
	result := strings.ReplaceAll(string(b), "</", "<\\/")
	return result
}

// linksJSONSafe returns the links slice as a JSON array safe for embedding in a <script> tag.
func linksJSONSafe(links []cases.CaseLink) string {
	if links == nil {
		return "[]"
	}
	b, _ := json.Marshal(links)
	result := strings.ReplaceAll(string(b), "</", "<\\/")
	return result
}
