// Code generated by qtc from "case_detail.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/case_detail.qtpl:4
package views

//line views/case_detail.qtpl:4
import "encoding/json"

//line views/case_detail.qtpl:5
import "github.com/wingedpig/trellis/internal/cases"

//line views/case_detail.qtpl:6
import "strings"

//line views/case_detail.qtpl:7
import "time"

//line views/case_detail.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/case_detail.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/case_detail.qtpl:10
type CaseDetailPage struct {
	BasePage
	WorktreeName string
	Case         *cases.CaseJSON
	Notes        string
	Traces       []cases.CaseTraceSummary
	IsArchived   bool
	WrapUpCommit *WrapUpCommitInfo
}

// WrapUpCommitInfo mirrors handlers.WrapUpCommitInfo. Defined in the views
// package as well so the qtpl doesn't have to import the handlers package
// (which would create an import cycle). The page handler populates this
// from the handlers package's lookup.
type WrapUpCommitInfo struct {
	SHA          string
	ShortSHA     string
	CommittedAt  time.Time
	Message      string
	FilesChanged []string
}

//line views/case_detail.qtpl:33
func (p *CaseDetailPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/case_detail.qtpl:33
	qw422016.N().S(`
`)
//line views/case_detail.qtpl:34
	p.StreamHeader(qw422016)
//line views/case_detail.qtpl:34
	qw422016.N().S(`

<link href="/static/css/cases.css" rel="stylesheet">

<div class="case-detail" data-worktree-name="`)
//line views/case_detail.qtpl:38
	qw422016.E().S(p.WorktreeName)
//line views/case_detail.qtpl:38
	qw422016.N().S(`">
    <div class="case-header mb-4">
        <div class="d-flex justify-content-between align-items-start">
            <div style="flex: 1;">
                <div id="case-title-view" class="d-flex align-items-center gap-2">
                    <h2 id="case-title-h2" class="mb-0">`)
//line views/case_detail.qtpl:43
	qw422016.E().S(p.Case.Title)
//line views/case_detail.qtpl:43
	qw422016.N().S(`</h2>
                    `)
//line views/case_detail.qtpl:44
	if !p.IsArchived {
//line views/case_detail.qtpl:44
		qw422016.N().S(`
                    <button class="btn btn-outline-secondary btn-sm" onclick="editCaseTitle()" title="Rename">
                        <i class="fa-solid fa-pen"></i>
                    </button>
                    `)
//line views/case_detail.qtpl:48
	}
//line views/case_detail.qtpl:48
	qw422016.N().S(`
                </div>
                <div id="case-title-edit" class="d-flex align-items-center gap-2" style="display:none">
                    <input type="text" id="case-title-input" class="form-control form-control-lg" style="max-width: 32rem;">
                    <button class="btn btn-primary btn-sm" onclick="saveCaseTitle()">
                        <i class="fa-solid fa-check"></i> Save
                    </button>
                    <button class="btn btn-outline-secondary btn-sm" onclick="cancelEditCaseTitle()">Cancel</button>
                </div>
                <div class="text-muted small mt-1">
                    <code title="Case ID is immutable">`)
//line views/case_detail.qtpl:58
	qw422016.E().S(p.Case.ID)
//line views/case_detail.qtpl:58
	qw422016.N().S(`</code>
                </div>
                <div class="case-meta mt-2">
                    <span class="badge case-kind-`)
//line views/case_detail.qtpl:61
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:61
	qw422016.N().S(`">`)
//line views/case_detail.qtpl:61
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:61
	qw422016.N().S(`</span>
                    <span class="badge case-status-`)
//line views/case_detail.qtpl:62
	qw422016.E().S(p.Case.Status)
//line views/case_detail.qtpl:62
	qw422016.N().S(`">`)
//line views/case_detail.qtpl:62
	qw422016.E().S(p.Case.Status)
//line views/case_detail.qtpl:62
	qw422016.N().S(`</span>
                    <span class="text-muted ms-2">
                        <i class="fa-solid fa-calendar"></i> `)
//line views/case_detail.qtpl:64
	qw422016.E().S(p.Case.CreatedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:64
	qw422016.N().S(`
                    </span>
                    `)
//line views/case_detail.qtpl:66
	if !p.Case.UpdatedAt.Equal(p.Case.CreatedAt) {
//line views/case_detail.qtpl:66
		qw422016.N().S(`
                    <span class="text-muted ms-2">
                        <i class="fa-solid fa-clock"></i> Updated `)
//line views/case_detail.qtpl:68
		qw422016.E().S(p.Case.UpdatedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:68
		qw422016.N().S(`
                    </span>
                    `)
//line views/case_detail.qtpl:70
	}
//line views/case_detail.qtpl:70
	qw422016.N().S(`
                </div>
            </div>
            <div class="case-actions">
                <a href="/worktree/`)
//line views/case_detail.qtpl:74
	qw422016.E().S(p.WorktreeName)
//line views/case_detail.qtpl:74
	qw422016.N().S(`" class="btn btn-outline-secondary btn-sm">
                    <i class="fa-solid fa-arrow-left"></i> Back
                </a>
                `)
//line views/case_detail.qtpl:77
	if !p.IsArchived {
//line views/case_detail.qtpl:77
		qw422016.N().S(`
                <button class="btn btn-outline-primary btn-sm" onclick="showWrapUpModal()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
                <button class="btn btn-outline-warning btn-sm" onclick="archiveCase()">
                    <i class="fa-solid fa-box-archive"></i> Archive
                </button>
                `)
//line views/case_detail.qtpl:84
	} else {
//line views/case_detail.qtpl:84
		qw422016.N().S(`
                <button class="btn btn-outline-success btn-sm" onclick="reopenCase()">
                    <i class="fa-solid fa-box-open"></i> Reopen
                </button>
                `)
//line views/case_detail.qtpl:88
	}
//line views/case_detail.qtpl:88
	qw422016.N().S(`
                <button class="btn btn-outline-danger btn-sm" onclick="deleteCase()">
                    <i class="fa-solid fa-trash"></i> Delete
                </button>
            </div>
        </div>
    </div>

    `)
//line views/case_detail.qtpl:96
	if p.Case.Summary != nil {
//line views/case_detail.qtpl:96
		qw422016.N().S(`
    <div class="case-section mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><i class="fa-solid fa-circle-info"></i> Summary <small class="text-muted">(generated)</small></h4>
            <button class="btn btn-outline-secondary btn-sm" onclick="regenerateSummary()">
                <i class="fa-solid fa-arrows-rotate"></i> Regenerate
            </button>
        </div>
        <div id="case-summary" class="mt-2">
            `)
//line views/case_detail.qtpl:105
		streamrenderSummary(qw422016, p.Case.Summary)
//line views/case_detail.qtpl:105
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:108
	}
//line views/case_detail.qtpl:108
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:110
	if p.WrapUpCommit != nil {
//line views/case_detail.qtpl:110
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-flag-checkered"></i> Wrap-up commit</h4>
        <div class="list-group">
            <div class="list-group-item">
                <div>
                    <code class="me-2">`)
//line views/case_detail.qtpl:116
		qw422016.E().S(p.WrapUpCommit.ShortSHA)
//line views/case_detail.qtpl:116
		qw422016.N().S(`</code>
                    <span class="text-muted small">`)
//line views/case_detail.qtpl:117
		qw422016.E().S(p.WrapUpCommit.CommittedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:117
		qw422016.N().S(`</span>
                    <div class="mt-1"><strong>`)
//line views/case_detail.qtpl:118
		qw422016.E().S(firstLine(p.WrapUpCommit.Message))
//line views/case_detail.qtpl:118
		qw422016.N().S(`</strong></div>
                    `)
//line views/case_detail.qtpl:119
		if len(p.WrapUpCommit.FilesChanged) > 0 {
//line views/case_detail.qtpl:119
			qw422016.N().S(`
                    <div class="mt-2">
                        <div class="text-muted small mb-1">Files changed:</div>
                        <ul class="case-files-list mb-0">
                            `)
//line views/case_detail.qtpl:123
			for _, f := range p.WrapUpCommit.FilesChanged {
//line views/case_detail.qtpl:123
				qw422016.N().S(`
                            <li><code>`)
//line views/case_detail.qtpl:124
				qw422016.E().S(f)
//line views/case_detail.qtpl:124
				qw422016.N().S(`</code></li>
                            `)
//line views/case_detail.qtpl:125
			}
//line views/case_detail.qtpl:125
			qw422016.N().S(`
                        </ul>
                    </div>
                    `)
//line views/case_detail.qtpl:128
		}
//line views/case_detail.qtpl:128
		qw422016.N().S(`
                </div>
            </div>
        </div>
    </div>
    `)
//line views/case_detail.qtpl:133
	}
//line views/case_detail.qtpl:133
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:135
	if len(p.Case.Commits) > 0 {
//line views/case_detail.qtpl:135
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-code-commit"></i> `)
//line views/case_detail.qtpl:137
		if p.WrapUpCommit != nil {
//line views/case_detail.qtpl:137
			qw422016.N().S(`Earlier commits`)
//line views/case_detail.qtpl:137
		} else {
//line views/case_detail.qtpl:137
			qw422016.N().S(`Commits`)
//line views/case_detail.qtpl:137
		}
//line views/case_detail.qtpl:137
		qw422016.N().S(`</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:139
		for i := len(p.Case.Commits) - 1; i >= 0; i-- {
//line views/case_detail.qtpl:139
			qw422016.N().S(`
            `)
//line views/case_detail.qtpl:140
			ce := p.Case.Commits[i]

//line views/case_detail.qtpl:140
			qw422016.N().S(`
            <div class="list-group-item">
                <div class="d-flex justify-content-between align-items-start">
                    <div>
                        <code class="me-2">`)
//line views/case_detail.qtpl:144
			qw422016.E().S(ce.ShortSHA)
//line views/case_detail.qtpl:144
			qw422016.N().S(`</code>
                        <span class="text-muted small">`)
//line views/case_detail.qtpl:145
			qw422016.E().S(ce.CommittedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:145
			qw422016.N().S(`</span>
                        <div class="mt-1"><strong>`)
//line views/case_detail.qtpl:146
			qw422016.E().S(firstLine(ce.Message))
//line views/case_detail.qtpl:146
			qw422016.N().S(`</strong></div>
                        `)
//line views/case_detail.qtpl:147
			if ce.Description != "" {
//line views/case_detail.qtpl:147
				qw422016.N().S(`
                        <div class="text-muted small mt-1">`)
//line views/case_detail.qtpl:148
				qw422016.E().S(ce.Description)
//line views/case_detail.qtpl:148
				qw422016.N().S(`</div>
                        `)
//line views/case_detail.qtpl:149
			}
//line views/case_detail.qtpl:149
			qw422016.N().S(`
                        `)
//line views/case_detail.qtpl:150
			if len(ce.FilesChanged) > 0 {
//line views/case_detail.qtpl:150
				qw422016.N().S(`
                        <div class="mt-2">
                            <ul class="case-files-list mb-0">
                                `)
//line views/case_detail.qtpl:153
				for _, f := range ce.FilesChanged {
//line views/case_detail.qtpl:153
					qw422016.N().S(`
                                <li><code>`)
//line views/case_detail.qtpl:154
					qw422016.E().S(f)
//line views/case_detail.qtpl:154
					qw422016.N().S(`</code></li>
                                `)
//line views/case_detail.qtpl:155
				}
//line views/case_detail.qtpl:155
				qw422016.N().S(`
                            </ul>
                        </div>
                        `)
//line views/case_detail.qtpl:158
			}
//line views/case_detail.qtpl:158
			qw422016.N().S(`
                    </div>
                </div>
            </div>
            `)
//line views/case_detail.qtpl:162
		}
//line views/case_detail.qtpl:162
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:165
	}
//line views/case_detail.qtpl:165
	qw422016.N().S(`

    <div class="case-section mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><i class="fa-solid fa-link"></i> Links</h4>
            <button class="btn btn-outline-secondary btn-sm" onclick="showAddLink()">
                <i class="fa-solid fa-plus"></i> Add
            </button>
        </div>
        <ul id="links-list" class="list-unstyled mt-2"></ul>
        <div id="link-add-form" class="case-link-add-form mt-2" style="display:none">
            <input type="text" id="link-title" class="form-control form-control-sm mb-2" placeholder="Title">
            <input type="url" id="link-url" class="form-control form-control-sm mb-2" placeholder="https://...">
            <div>
                <button class="btn btn-primary btn-sm" onclick="addLink()">
                    <i class="fa-solid fa-check"></i> Save
                </button>
                <button class="btn btn-outline-secondary btn-sm ms-1" onclick="cancelAddLink()">
                    Cancel
                </button>
            </div>
        </div>
    </div>

    `)
//line views/case_detail.qtpl:189
	if len(p.Case.Evidence) > 0 {
//line views/case_detail.qtpl:189
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-file-lines"></i> Evidence</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:193
		for _, ev := range p.Case.Evidence {
//line views/case_detail.qtpl:193
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <strong>`)
//line views/case_detail.qtpl:196
			qw422016.E().S(ev.Title)
//line views/case_detail.qtpl:196
			qw422016.N().S(`</strong>
                    <span class="badge bg-secondary ms-2">`)
//line views/case_detail.qtpl:197
			qw422016.E().S(ev.Format)
//line views/case_detail.qtpl:197
			qw422016.N().S(`</span>
                    `)
//line views/case_detail.qtpl:198
			for _, tag := range ev.Tags {
//line views/case_detail.qtpl:198
				qw422016.N().S(`
                    <span class="badge bg-info ms-1">`)
//line views/case_detail.qtpl:199
				qw422016.E().S(tag)
//line views/case_detail.qtpl:199
				qw422016.N().S(`</span>
                    `)
//line views/case_detail.qtpl:200
			}
//line views/case_detail.qtpl:200
			qw422016.N().S(`
                </div>
                <span class="text-muted">`)
//line views/case_detail.qtpl:202
			qw422016.E().S(ev.AddedAt.Format("2006-01-02"))
//line views/case_detail.qtpl:202
			qw422016.N().S(`</span>
            </div>
            `)
//line views/case_detail.qtpl:204
		}
//line views/case_detail.qtpl:204
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:207
	}
//line views/case_detail.qtpl:207
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:209
	if len(p.Case.Claude) > 0 {
//line views/case_detail.qtpl:209
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-robot"></i> Claude Transcripts</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:213
		for _, ref := range p.Case.Claude {
//line views/case_detail.qtpl:213
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <div>
                        <strong>`)
//line views/case_detail.qtpl:217
			qw422016.E().S(ref.Title)
//line views/case_detail.qtpl:217
			qw422016.N().S(`</strong>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:218
			qw422016.N().D(ref.MessageCount)
//line views/case_detail.qtpl:218
			qw422016.N().S(` messages</span>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:219
			qw422016.E().S(ref.ExportedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:219
			qw422016.N().S(`</span>
                        `)
//line views/case_detail.qtpl:220
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:220
				qw422016.N().S(`
                        <span class="text-warning ms-2" title="The live session has more messages than this saved transcript">
                            <i class="fa-solid fa-circle-exclamation"></i> `)
//line views/case_detail.qtpl:222
				qw422016.N().D(ref.CurrentMessageCount - ref.MessageCount)
//line views/case_detail.qtpl:222
				qw422016.N().S(` new messages
                        </span>
                        `)
//line views/case_detail.qtpl:224
			} else if ref.CurrentMessageCount == -1 {
//line views/case_detail.qtpl:224
				qw422016.N().S(`
                        <span class="text-muted ms-2" title="The source session has been deleted">
                            <i class="fa-solid fa-circle-xmark"></i> session deleted
                        </span>
                        `)
//line views/case_detail.qtpl:228
			}
//line views/case_detail.qtpl:228
			qw422016.N().S(`
                    </div>
                    `)
//line views/case_detail.qtpl:230
			if ref.Preview != "" {
//line views/case_detail.qtpl:230
				qw422016.N().S(`
                    <div class="text-muted small text-truncate" style="max-width: 600px;">`)
//line views/case_detail.qtpl:231
				qw422016.E().S(ref.Preview)
//line views/case_detail.qtpl:231
				qw422016.N().S(`</div>
                    `)
//line views/case_detail.qtpl:232
			}
//line views/case_detail.qtpl:232
			qw422016.N().S(`
                </div>
                <div class="d-flex gap-1">
                    `)
//line views/case_detail.qtpl:235
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:235
				qw422016.N().S(`
                    <button class="btn btn-outline-warning btn-sm" onclick="updateTranscript('`)
//line views/case_detail.qtpl:236
				qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:236
				qw422016.N().S(`')" title="Update transcript with latest messages">
                        <i class="fa-solid fa-rotate"></i> Update
                    </button>
                    `)
//line views/case_detail.qtpl:239
			}
//line views/case_detail.qtpl:239
			qw422016.N().S(`
                    <button class="btn btn-outline-primary btn-sm" onclick="continueTranscript('`)
//line views/case_detail.qtpl:240
			qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:240
			qw422016.N().S(`')">
                        <i class="fa-solid fa-play"></i> Continue
                    </button>
                </div>
            </div>
            `)
//line views/case_detail.qtpl:245
		}
//line views/case_detail.qtpl:245
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:248
	}
//line views/case_detail.qtpl:248
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:250
	if len(p.Case.Codex) > 0 {
//line views/case_detail.qtpl:250
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-microchip"></i> Codex Transcripts</h4>
        <div class="list-group">
            `)
//line views/case_detail.qtpl:254
		for _, ref := range p.Case.Codex {
//line views/case_detail.qtpl:254
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <div>
                        <strong>`)
//line views/case_detail.qtpl:258
			qw422016.E().S(ref.Title)
//line views/case_detail.qtpl:258
			qw422016.N().S(`</strong>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:259
			qw422016.N().D(ref.MessageCount)
//line views/case_detail.qtpl:259
			qw422016.N().S(` messages</span>
                        <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:260
			qw422016.E().S(ref.ExportedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:260
			qw422016.N().S(`</span>
                        `)
//line views/case_detail.qtpl:261
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:261
				qw422016.N().S(`
                        <span class="text-warning ms-2" title="The live session has more messages than this saved transcript">
                            <i class="fa-solid fa-circle-exclamation"></i> `)
//line views/case_detail.qtpl:263
				qw422016.N().D(ref.CurrentMessageCount - ref.MessageCount)
//line views/case_detail.qtpl:263
				qw422016.N().S(` new messages
                        </span>
                        `)
//line views/case_detail.qtpl:265
			} else if ref.CurrentMessageCount == -1 {
//line views/case_detail.qtpl:265
				qw422016.N().S(`
                        <span class="text-muted ms-2" title="The source session has been deleted">
                            <i class="fa-solid fa-circle-xmark"></i> session deleted
                        </span>
                        `)
//line views/case_detail.qtpl:269
			}
//line views/case_detail.qtpl:269
			qw422016.N().S(`
                    </div>
                    `)
//line views/case_detail.qtpl:271
			if ref.Preview != "" {
//line views/case_detail.qtpl:271
				qw422016.N().S(`
                    <div class="text-muted small text-truncate" style="max-width: 600px;">`)
//line views/case_detail.qtpl:272
				qw422016.E().S(ref.Preview)
//line views/case_detail.qtpl:272
				qw422016.N().S(`</div>
                    `)
//line views/case_detail.qtpl:273
			}
//line views/case_detail.qtpl:273
			qw422016.N().S(`
                </div>
                <div class="d-flex gap-1">
                    `)
//line views/case_detail.qtpl:276
			if ref.CurrentMessageCount > ref.MessageCount {
//line views/case_detail.qtpl:276
				qw422016.N().S(`
                    <button class="btn btn-outline-warning btn-sm" onclick="updateCodexTranscript('`)
//line views/case_detail.qtpl:277
				qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:277
				qw422016.N().S(`')" title="Update transcript with latest messages">
                        <i class="fa-solid fa-rotate"></i> Update
                    </button>
                    `)
//line views/case_detail.qtpl:280
			}
//line views/case_detail.qtpl:280
			qw422016.N().S(`
                    <button class="btn btn-outline-primary btn-sm" onclick="continueCodexTranscript('`)
//line views/case_detail.qtpl:281
			qw422016.E().S(JSAttr(ref.ID))
//line views/case_detail.qtpl:281
			qw422016.N().S(`')">
                        <i class="fa-solid fa-play"></i> Continue
                    </button>
                </div>
            </div>
            `)
//line views/case_detail.qtpl:286
		}
//line views/case_detail.qtpl:286
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:289
	}
//line views/case_detail.qtpl:289
	qw422016.N().S(`

    `)
//line views/case_detail.qtpl:291
	if len(p.Traces) > 0 {
//line views/case_detail.qtpl:291
		qw422016.N().S(`
    <div class="case-section mb-4">
        <h4><i class="fa-solid fa-magnifying-glass"></i> Traces</h4>
        <div class="list-group" id="traces-list">
            `)
//line views/case_detail.qtpl:295
		for _, tr := range p.Traces {
//line views/case_detail.qtpl:295
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center" id="trace-`)
//line views/case_detail.qtpl:296
			qw422016.E().S(tr.ID)
//line views/case_detail.qtpl:296
			qw422016.N().S(`">
                <a href="/case/`)
//line views/case_detail.qtpl:297
			qw422016.E().S(p.WorktreeName)
//line views/case_detail.qtpl:297
			qw422016.N().S(`/`)
//line views/case_detail.qtpl:297
			qw422016.E().S(p.Case.ID)
//line views/case_detail.qtpl:297
			qw422016.N().S(`/trace/`)
//line views/case_detail.qtpl:297
			qw422016.E().S(tr.ID)
//line views/case_detail.qtpl:297
			qw422016.N().S(`" class="text-decoration-none flex-grow-1">
                    <strong>`)
//line views/case_detail.qtpl:298
			qw422016.E().S(tr.Name)
//line views/case_detail.qtpl:298
			qw422016.N().S(`</strong>
                    <span class="text-muted ms-2"><code>`)
//line views/case_detail.qtpl:299
			qw422016.E().S(tr.TraceID)
//line views/case_detail.qtpl:299
			qw422016.N().S(`</code></span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:300
			qw422016.E().S(tr.Group)
//line views/case_detail.qtpl:300
			qw422016.N().S(`</span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:301
			qw422016.N().D(tr.EntryCount)
//line views/case_detail.qtpl:301
			qw422016.N().S(` entries</span>
                    <span class="text-muted ms-2">`)
//line views/case_detail.qtpl:302
			qw422016.E().S(tr.SavedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:302
			qw422016.N().S(`</span>
                </a>
                <button class="btn btn-outline-danger btn-sm ms-2" onclick="deleteTrace('`)
//line views/case_detail.qtpl:304
			qw422016.E().S(JSAttr(tr.ID))
//line views/case_detail.qtpl:304
			qw422016.N().S(`')" title="Remove trace">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </div>
            `)
//line views/case_detail.qtpl:308
		}
//line views/case_detail.qtpl:308
		qw422016.N().S(`
        </div>
    </div>
    `)
//line views/case_detail.qtpl:311
	}
//line views/case_detail.qtpl:311
	qw422016.N().S(`

    <div class="case-section mb-4">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><i class="fa-solid fa-note-sticky"></i> Notes</h4>
            `)
//line views/case_detail.qtpl:316
	if !p.IsArchived {
//line views/case_detail.qtpl:316
		qw422016.N().S(`
            <div id="notes-view-actions">
                <button class="btn btn-outline-secondary btn-sm" onclick="editNotes()">
                    <i class="fa-solid fa-pen"></i> Edit
                </button>
            </div>
            `)
//line views/case_detail.qtpl:322
	}
//line views/case_detail.qtpl:322
	qw422016.N().S(`
            <div id="notes-edit-actions" style="display:none">
                <button class="btn btn-primary btn-sm" onclick="saveNotes()">
                    <i class="fa-solid fa-check"></i> Save
                </button>
                <button class="btn btn-outline-secondary btn-sm ms-1" onclick="cancelEditNotes()">
                    Cancel
                </button>
            </div>
        </div>
        <div id="notes-view" class="mt-2">
            <div id="case-notes" class="case-notes-content"></div>
        </div>
        <div id="notes-edit" class="mt-2" style="display:none">
            <textarea id="notes-textarea" class="case-notes-textarea"></textarea>
        </div>
    </div>
</div>

<script>
// `)
//line views/case_detail.qtpl:322
	qw422016.N().S("`")
//line views/case_detail.qtpl:322
	qw422016.N().S(`var`)
//line views/case_detail.qtpl:322
	qw422016.N().S("`")
//line views/case_detail.qtpl:322
	qw422016.N().S(` so the script can be re-executed cleanly when the SPA re-fetches.
var WORKTREE_NAME = '`)
//line views/case_detail.qtpl:343
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/case_detail.qtpl:343
	qw422016.N().S(`';
var CASE_ID = '`)
//line views/case_detail.qtpl:344
	qw422016.E().S(JSAttr(p.Case.ID))
//line views/case_detail.qtpl:344
	qw422016.N().S(`';
var CASE_NOTES_RAW = `)
//line views/case_detail.qtpl:345
	qw422016.N().S(notesJSONSafe(p.Notes))
//line views/case_detail.qtpl:345
	qw422016.N().S(`;
var CASE_LINKS = `)
//line views/case_detail.qtpl:346
	qw422016.N().S(linksJSONSafe(p.Case.Links))
//line views/case_detail.qtpl:346
	qw422016.N().S(`;

// SPA: when this container is restored from the LRU cache, the inline script
// does NOT re-execute, so the globals above would otherwise hold whichever
// case was most recently fresh-loaded. Snapshot the live values on every
// page-leaving and restore them on every page-entered. Using page-leaving
// (not the initial fresh-load values) preserves in-page mutations — e.g. if
// the user edits notes or renames the case before navigating away, those
// updates are captured in the snapshot and survive the round-trip through
// the cache. Without this, mutating requests would target the wrong case
// and the edit-notes textarea would seed from stale text.
(function() {
    var snap = {
        worktree: WORKTREE_NAME,
        caseId: CASE_ID,
        notes: CASE_NOTES_RAW,
        links: CASE_LINKS,
    };
    function captureLocal() {
        snap.worktree = WORKTREE_NAME;
        snap.caseId = CASE_ID;
        snap.notes = CASE_NOTES_RAW;
        snap.links = CASE_LINKS;
    }
    function restoreLocal() {
        WORKTREE_NAME = snap.worktree;
        CASE_ID = snap.caseId;
        CASE_NOTES_RAW = snap.notes;
        CASE_LINKS = snap.links;
    }
    var container = document.currentScript && document.currentScript.closest('.page-container');
    if (container) {
        container.addEventListener('trellis:page-leaving', captureLocal);
        container.addEventListener('trellis:page-entered', restoreLocal);
    }
})();

function initCaseDetailPage() {
    renderNotes();
    renderLinks();
}
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initCaseDetailPage);
} else {
    initCaseDetailPage();
}

function renderNotes() {
    var el = document.getElementById('case-notes');
    if (CASE_NOTES_RAW && typeof marked !== 'undefined') {
        el.innerHTML = marked.parse(CASE_NOTES_RAW);
        el.style.display = '';
    } else {
        el.innerHTML = '<span class="text-muted">No notes yet.</span>';
    }
}

function editNotes() {
    document.getElementById('notes-view').style.display = 'none';
    document.getElementById('notes-view-actions').style.display = 'none';
    document.getElementById('notes-edit').style.display = '';
    document.getElementById('notes-edit-actions').style.display = '';
    document.getElementById('notes-textarea').value = CASE_NOTES_RAW || '';
    document.getElementById('notes-textarea').focus();
}

function cancelEditNotes() {
    document.getElementById('notes-edit').style.display = 'none';
    document.getElementById('notes-edit-actions').style.display = 'none';
    document.getElementById('notes-view').style.display = '';
    document.getElementById('notes-view-actions').style.display = '';
}

function saveNotes() {
    var text = document.getElementById('notes-textarea').value;
    var btn = document.querySelector('#notes-edit-actions .btn-primary');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Saving...';
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({notes: text})
    })
    .then(function(resp) {
        if (!resp.ok) throw new Error('Save failed');
        CASE_NOTES_RAW = text;
        renderNotes();
        cancelEditNotes();
    })
    .catch(function(err) { alert('Save failed: ' + err); })
    .finally(function() {
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-check"></i> Save';
    });
}

function renderLinks() {
    var el = document.getElementById('links-list');
    if (!CASE_LINKS || CASE_LINKS.length === 0) {
        el.innerHTML = '<li class="text-muted">No links yet.</li>';
        return;
    }
    el.innerHTML = CASE_LINKS.map(function(link, i) {
        return '<li class="case-link-item">' +
            '<a href="' + escapeAttr(link.url) + '" target="_blank" rel="noopener">' + escapeHTML(link.title) + '</a>' +
            '<button class="btn btn-outline-danger btn-sm case-link-delete" onclick="deleteLink(' + i + ')" title="Remove link">' +
            '<i class="fa-solid fa-xmark"></i></button>' +
            '</li>';
    }).join('');
}

function escapeHTML(s) {
    var d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML;
}

function escapeAttr(s) {
    var d = document.createElement('div');
    d.textContent = s;
    return d.innerHTML.replace(/"/g, '&quot;');
}

function showAddLink() {
    document.getElementById('link-add-form').style.display = '';
    document.getElementById('link-title').focus();
}

function cancelAddLink() {
    document.getElementById('link-add-form').style.display = 'none';
    document.getElementById('link-title').value = '';
    document.getElementById('link-url').value = '';
}

function addLink() {
    var title = document.getElementById('link-title').value.trim();
    var url = document.getElementById('link-url').value.trim();
    if (!title || !url) { alert('Title and URL are required.'); return; }
    CASE_LINKS.push({title: title, url: url});
    patchLinks()
        .then(function() { renderLinks(); cancelAddLink(); })
        .catch(function(err) { CASE_LINKS.pop(); alert('Save failed: ' + err); });
}

// Inline title edit. The case ID is immutable; only the title changes.
function editCaseTitle() {
    var current = document.getElementById('case-title-h2').textContent;
    document.getElementById('case-title-input').value = current;
    document.getElementById('case-title-view').style.display = 'none';
    document.getElementById('case-title-edit').style.display = 'flex';
    document.getElementById('case-title-input').focus();
}

function cancelEditCaseTitle() {
    document.getElementById('case-title-edit').style.display = 'none';
    document.getElementById('case-title-view').style.display = 'flex';
}

function saveCaseTitle() {
    var newTitle = document.getElementById('case-title-input').value.trim();
    if (!newTitle) { alert('Title cannot be empty.'); return; }
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({title: newTitle})
    })
    .then(function(resp) {
        if (!resp.ok) throw new Error('Save failed');
        document.getElementById('case-title-h2').textContent = newTitle;
        // Keep the wrap-up modal in sync.
        if (window.WRAPUP_CASE) window.WRAPUP_CASE.title = newTitle;
        cancelEditCaseTitle();
    })
    .catch(function(err) { alert('Save failed: ' + err); });
}

// Regenerate the generated case summary. Confirms before overwriting if a
// summary already exists (the existing summary may have hand-edits the user
// would lose).
function regenerateSummary() {
    var container = document.getElementById('case-summary');
    var hasExisting = container && container.querySelector('dt');
    if (hasExisting && !confirm('Regenerate summary? This overwrites any hand edits to the existing summary.')) {
        return;
    }
    var btn = event && event.currentTarget;
    if (btn) {
        btn.disabled = true;
        btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Regenerating…';
    }
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/regenerate-summary', {
        method: 'POST'
    })
    .then(function(r) { return r.json().then(function(d) { return {ok: r.ok, data: d}; }); })
    .then(function(result) {
        if (!result.ok) {
            var msg = (result.data.error && result.data.error.message) || 'Regenerate failed';
            throw new Error(msg);
        }
        // Simplest path: reload the page to re-render the summary section.
        window.location.reload();
    })
    .catch(function(err) {
        alert('Regenerate failed: ' + err);
        if (btn) {
            btn.disabled = false;
            btn.innerHTML = '<i class="fa-solid fa-arrows-rotate"></i> Regenerate';
        }
    });
}

function deleteLink(index) {
    var removed = CASE_LINKS.splice(index, 1)[0];
    patchLinks()
        .then(function() { renderLinks(); })
        .catch(function(err) { CASE_LINKS.splice(index, 0, removed); alert('Delete failed: ' + err); });
}

function patchLinks() {
    return fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'PATCH',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({links: CASE_LINKS})
    }).then(function(resp) {
        if (!resp.ok) throw new Error('Save failed');
    });
}

function archiveCase() {
    if (!confirm('Archive this case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/archive', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Archive failed');
        window.location.href = '/worktree/' + encodeURIComponent(WORKTREE_NAME);
    })
    .catch(err => alert('Archive failed: ' + err));
}

function reopenCase() {
    if (!confirm('Reopen this case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/reopen', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Reopen failed');
        window.location.reload();
    })
    .catch(err => alert('Reopen failed: ' + err));
}

function deleteCase() {
    if (!confirm('Permanently delete this case? This cannot be undone.')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID), {
        method: 'DELETE'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Delete failed');
        window.location.href = '/worktree/' + encodeURIComponent(WORKTREE_NAME);
    })
    .catch(err => alert('Delete failed: ' + err));
}

function deleteTrace(traceId) {
    if (!confirm('Remove this trace from the case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/trace/' + encodeURIComponent(traceId), {
        method: 'DELETE'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Delete failed');
        var el = document.getElementById('trace-' + traceId);
        if (el) el.remove();
    })
    .catch(err => alert('Delete failed: ' + err));
}

function updateTranscript(claudeId) {
    var btn = event.target.closest('button');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Updating...';
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/transcript/' + encodeURIComponent(claudeId), {
        method: 'PUT'
    })
    .then(resp => {
        if (!resp.ok) return resp.json().then(d => { throw new Error(d.error?.message || 'Update failed'); });
        window.location.reload();
    })
    .catch(err => {
        alert('Update failed: ' + err);
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-rotate"></i> Update';
    });
}

function continueTranscript(claudeId) {
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/transcript/' + encodeURIComponent(claudeId) + '/continue', {
        method: 'POST'
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Continue failed'); });
        return r.json();
    })
    .then(data => {
        const sess = data.data || data;
        window.location.href = '/claude/' + encodeURIComponent(WORKTREE_NAME) + '/' + sess.id;
    })
    .catch(err => alert('Continue failed: ' + err));
}

function updateCodexTranscript(codexId) {
    var btn = event.target.closest('button');
    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Updating...';
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/codex-transcript/' + encodeURIComponent(codexId), {
        method: 'PUT'
    })
    .then(resp => {
        if (!resp.ok) return resp.json().then(d => { throw new Error(d.error?.message || 'Update failed'); });
        window.location.reload();
    })
    .catch(err => alert('Update failed: ' + err))
    .finally(() => {
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-rotate"></i> Update';
    });
}

function continueCodexTranscript(codexId) {
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(CASE_ID) + '/codex-transcript/' + encodeURIComponent(codexId) + '/continue', {
        method: 'POST'
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Continue failed'); });
        return r.json();
    })
    .then(data => {
        const sess = data.data || data;
        window.location.href = '/codex/' + encodeURIComponent(WORKTREE_NAME) + '/' + sess.id;
    })
    .catch(err => alert('Continue failed: ' + err));
}
</script>

<script>
var WRAPUP_WORKTREE = WORKTREE_NAME;
var WRAPUP_SESSION_ID = null;
var WRAPUP_CASE = {id: CASE_ID, title: `)
//line views/case_detail.qtpl:693
	qw422016.N().S(notesJSONSafe(p.Case.Title))
//line views/case_detail.qtpl:693
	qw422016.N().S(`, kind: '`)
//line views/case_detail.qtpl:693
	qw422016.E().S(p.Case.Kind)
//line views/case_detail.qtpl:693
	qw422016.N().S(`'};
// SPA: snapshot wrap-up globals on page-leaving and restore on page-entered.
// Using page-leaving captures in-page mutations (e.g. WRAPUP_CASE.title being
// updated after a rename) so they survive a round-trip through the cache.
(function() {
    var snap = {
        worktree: WRAPUP_WORKTREE,
        sessionId: WRAPUP_SESSION_ID,
        caseObj: WRAPUP_CASE,
    };
    function captureWrap() {
        snap.worktree = WRAPUP_WORKTREE;
        snap.sessionId = WRAPUP_SESSION_ID;
        snap.caseObj = WRAPUP_CASE;
    }
    function restoreWrap() {
        WRAPUP_WORKTREE = snap.worktree;
        WRAPUP_SESSION_ID = snap.sessionId;
        WRAPUP_CASE = snap.caseObj;
    }
    var container = document.currentScript && document.currentScript.closest('.page-container');
    if (container) {
        container.addEventListener('trellis:page-leaving', captureWrap);
        container.addEventListener('trellis:page-entered', restoreWrap);
    }
})();
</script>

<!-- Wrap Up Modal -->
<div class="modal fade" id="wrapUpModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-flag-checkered"></i> Wrap Up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div id="wrapUpError" class="alert alert-danger" style="display:none"></div>
                <div id="wrapUpSuccess" class="alert alert-success" style="display:none"></div>

                <!-- Existing case info (read-only) -->
                <div id="wrapUpCaseInfo" style="display:none" class="mb-3">
                    <div class="card card-body bg-light">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-secondary" id="wrapUpCaseKind"></span>
                            <strong id="wrapUpCaseTitle"></strong>
                            <code class="ms-auto" id="wrapUpCaseId"></code>
                        </div>
                    </div>
                </div>

                <!-- New case fields (editable) -->
                <div id="wrapUpNewCase" style="display:none">
                    <div class="mb-3">
                        <label for="wrapUpNewTitle" class="form-label">Case Title</label>
                        <input type="text" class="form-control" id="wrapUpNewTitle" placeholder="Fix login bug" oninput="updateWrapUpCommitMsg()">
                    </div>
                    <div class="mb-3">
                        <label for="wrapUpNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="wrapUpNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>

                <!-- Files -->
                <div class="mb-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <label class="form-label mb-1">Files to commit</label>
                        <span class="small">
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpFileList', true); return false;">all</a>
                            /
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpFileList', false); return false;">none</a>
                        </span>
                    </div>
                    <div id="wrapUpFileList" class="wrap-up-file-list"></div>
                </div>

                <!-- Generated tags (wrap-up only) -->
                <div class="mb-3" id="wrapUpTagsSection" style="display:none">
                    <div class="d-flex justify-content-between align-items-center mb-1">
                        <label class="form-label mb-0">Tags <small class="text-muted">(generated — click × to drop)</small></label>
                        <span class="small text-muted" id="wrapUpTagsStatus"></span>
                    </div>
                    <div class="mb-2">
                        <div class="text-muted small">Components</div>
                        <div id="wrapUpComponentsList" class="wrap-up-chip-list"></div>
                    </div>
                    <div>
                        <div class="text-muted small">Keywords</div>
                        <div id="wrapUpKeywordsList" class="wrap-up-chip-list"></div>
                    </div>
                </div>

                <!-- Commit message -->
                <div class="mb-3">
                    <label for="wrapUpCommitMsg" class="form-label">Commit message</label>
                    <textarea class="form-control" id="wrapUpCommitMsg" rows="3"></textarea>
                </div>

                <!-- Links -->
                <div class="mb-3" id="wrapUpLinksSection">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <label class="form-label mb-0">Links (optional)</label>
                        <button class="btn btn-outline-secondary btn-sm" type="button" onclick="addWrapUpLink()">
                            <i class="fa-solid fa-plus"></i> Add
                        </button>
                    </div>
                    <div id="wrapUpLinks"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="wrapUpConfirmBtn" onclick="wrapUpConfirm()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
            </div>
        </div>
    </div>
</div>

<link href="/static/css/claude.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.1/marked.min.js"></script>
<script src="/static/js/wrapup.js"></script>
<script src="/static/js/workflow_picker.js"></script>

`)
//line views/case_detail.qtpl:822
	p.StreamFooter(qw422016)
//line views/case_detail.qtpl:822
	qw422016.N().S(`
`)
//line views/case_detail.qtpl:823
}

//line views/case_detail.qtpl:823
func (p *CaseDetailPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/case_detail.qtpl:823
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/case_detail.qtpl:823
	p.StreamRender(qw422016)
//line views/case_detail.qtpl:823
	qt422016.ReleaseWriter(qw422016)
//line views/case_detail.qtpl:823
}

//line views/case_detail.qtpl:823
func (p *CaseDetailPage) Render() string {
//line views/case_detail.qtpl:823
	qb422016 := qt422016.AcquireByteBuffer()
//line views/case_detail.qtpl:823
	p.WriteRender(qb422016)
//line views/case_detail.qtpl:823
	qs422016 := string(qb422016.B)
//line views/case_detail.qtpl:823
	qt422016.ReleaseByteBuffer(qb422016)
//line views/case_detail.qtpl:823
	return qs422016
//line views/case_detail.qtpl:823
}

//line views/case_detail.qtpl:825
func streamrenderSummary(qw422016 *qt422016.Writer, s *cases.CaseSummary) {
//line views/case_detail.qtpl:825
	qw422016.N().S(`
`)
//line views/case_detail.qtpl:826
	if s == nil {
//line views/case_detail.qtpl:826
		return
//line views/case_detail.qtpl:826
	}
//line views/case_detail.qtpl:826
	qw422016.N().S(`
<dl class="case-summary mb-0">
    `)
//line views/case_detail.qtpl:828
	if s.Synopsis != "" {
//line views/case_detail.qtpl:828
		qw422016.N().S(`
    <dt>Synopsis</dt>
    <dd data-field="synopsis">`)
//line views/case_detail.qtpl:830
		qw422016.E().S(s.Synopsis)
//line views/case_detail.qtpl:830
		qw422016.N().S(`</dd>
    `)
//line views/case_detail.qtpl:831
	}
//line views/case_detail.qtpl:831
	qw422016.N().S(`
    `)
//line views/case_detail.qtpl:832
	if s.Symptoms != "" {
//line views/case_detail.qtpl:832
		qw422016.N().S(`
    <dt>Symptoms</dt>
    <dd data-field="symptoms">`)
//line views/case_detail.qtpl:834
		qw422016.E().S(s.Symptoms)
//line views/case_detail.qtpl:834
		qw422016.N().S(`</dd>
    `)
//line views/case_detail.qtpl:835
	}
//line views/case_detail.qtpl:835
	qw422016.N().S(`
    `)
//line views/case_detail.qtpl:836
	if s.RootCause != "" {
//line views/case_detail.qtpl:836
		qw422016.N().S(`
    <dt>Root cause</dt>
    <dd data-field="root_cause">`)
//line views/case_detail.qtpl:838
		qw422016.E().S(s.RootCause)
//line views/case_detail.qtpl:838
		qw422016.N().S(`</dd>
    `)
//line views/case_detail.qtpl:839
	}
//line views/case_detail.qtpl:839
	qw422016.N().S(`
    `)
//line views/case_detail.qtpl:840
	if s.Resolution != "" {
//line views/case_detail.qtpl:840
		qw422016.N().S(`
    <dt>Resolution</dt>
    <dd data-field="resolution">`)
//line views/case_detail.qtpl:842
		qw422016.E().S(s.Resolution)
//line views/case_detail.qtpl:842
		qw422016.N().S(`</dd>
    `)
//line views/case_detail.qtpl:843
	}
//line views/case_detail.qtpl:843
	qw422016.N().S(`
    `)
//line views/case_detail.qtpl:844
	if len(s.Components) > 0 {
//line views/case_detail.qtpl:844
		qw422016.N().S(`
    <dt>Components</dt>
    <dd data-field="components">
        `)
//line views/case_detail.qtpl:847
		for _, c := range s.Components {
//line views/case_detail.qtpl:847
			qw422016.N().S(`<span class="badge bg-info me-1">`)
//line views/case_detail.qtpl:847
			qw422016.E().S(c)
//line views/case_detail.qtpl:847
			qw422016.N().S(`</span>`)
//line views/case_detail.qtpl:847
		}
//line views/case_detail.qtpl:847
		qw422016.N().S(`
    </dd>
    `)
//line views/case_detail.qtpl:849
	}
//line views/case_detail.qtpl:849
	qw422016.N().S(`
    `)
//line views/case_detail.qtpl:850
	if len(s.Keywords) > 0 {
//line views/case_detail.qtpl:850
		qw422016.N().S(`
    <dt>Keywords</dt>
    <dd data-field="keywords">
        `)
//line views/case_detail.qtpl:853
		for _, k := range s.Keywords {
//line views/case_detail.qtpl:853
			qw422016.N().S(`<span class="badge bg-secondary me-1">`)
//line views/case_detail.qtpl:853
			qw422016.E().S(k)
//line views/case_detail.qtpl:853
			qw422016.N().S(`</span>`)
//line views/case_detail.qtpl:853
		}
//line views/case_detail.qtpl:853
		qw422016.N().S(`
    </dd>
    `)
//line views/case_detail.qtpl:855
	}
//line views/case_detail.qtpl:855
	qw422016.N().S(`
</dl>
<div class="small text-muted mt-2">
    `)
//line views/case_detail.qtpl:858
	if s.Model != "" {
//line views/case_detail.qtpl:858
		qw422016.N().S(`Model: `)
//line views/case_detail.qtpl:858
		qw422016.E().S(s.Model)
//line views/case_detail.qtpl:858
		qw422016.N().S(`. `)
//line views/case_detail.qtpl:858
	}
//line views/case_detail.qtpl:858
	qw422016.N().S(`Generated `)
//line views/case_detail.qtpl:858
	qw422016.E().S(s.GeneratedAt.Format("2006-01-02 15:04"))
//line views/case_detail.qtpl:858
	qw422016.N().S(`.
</div>
`)
//line views/case_detail.qtpl:860
}

//line views/case_detail.qtpl:860
func writerenderSummary(qq422016 qtio422016.Writer, s *cases.CaseSummary) {
//line views/case_detail.qtpl:860
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/case_detail.qtpl:860
	streamrenderSummary(qw422016, s)
//line views/case_detail.qtpl:860
	qt422016.ReleaseWriter(qw422016)
//line views/case_detail.qtpl:860
}

//line views/case_detail.qtpl:860
func renderSummary(s *cases.CaseSummary) string {
//line views/case_detail.qtpl:860
	qb422016 := qt422016.AcquireByteBuffer()
//line views/case_detail.qtpl:860
	writerenderSummary(qb422016, s)
//line views/case_detail.qtpl:860
	qs422016 := string(qb422016.B)
//line views/case_detail.qtpl:860
	qt422016.ReleaseByteBuffer(qb422016)
//line views/case_detail.qtpl:860
	return qs422016
//line views/case_detail.qtpl:860
}

// firstLine returns the first non-empty line of s, used to render commit
// messages compactly on the case detail page.
//
//line views/case_detail.qtpl:863
func firstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			return line
		}
	}
	return s
}

// notesJSONSafe returns the notes as a JSON-encoded string safe for embedding in a <script> tag.
func notesJSONSafe(s string) string {
	// JSON encode the string (handles escaping quotes, newlines, etc.)
	b, _ := json.Marshal(s)
	// Replace </script to prevent XSS
	result := strings.ReplaceAll(string(b), "</", "<\\/")
	return result
}

// linksJSONSafe returns the links slice as a JSON array safe for embedding in a <script> tag.
func linksJSONSafe(links []cases.CaseLink) string {
	if links == nil {
		return "[]"
	}
	b, _ := json.Marshal(links)
	result := strings.ReplaceAll(string(b), "</", "<\\/")
	return result
}
