// Code generated by qtc from "claude.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/claude.qtpl:4
package views

//line views/claude.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/claude.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/claude.qtpl:5
type ClaudePage struct {
	BasePage
	WorktreeName string
	SessionID    string
}

//line views/claude.qtpl:12
func (p *ClaudePage) StreamRender(qw422016 *qt422016.Writer) {
//line views/claude.qtpl:12
	qw422016.N().S(`
`)
//line views/claude.qtpl:13
	p.StreamHeader(qw422016)
//line views/claude.qtpl:13
	qw422016.N().S(`

<link href="/static/css/claude.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css" id="hljs-light">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" id="hljs-dark" disabled>
<script>
    // Apply correct highlight.js theme immediately
    (function() {
        const theme = document.documentElement.getAttribute('data-theme') || 'light';
        document.getElementById('hljs-light').disabled = (theme === 'dark');
        document.getElementById('hljs-dark').disabled = (theme !== 'dark');
    })();
</script>

<div id="claude-chat" class="claude-chat-container">
    <div id="claude-messages" class="claude-messages"></div>
    <div id="claude-input-area" class="claude-input-area">
        <div class="claude-input-row">
            <textarea id="claude-input" class="claude-input" placeholder="Ask Claude Code..." rows="1"></textarea>
            <button id="claude-send-btn" class="btn btn-primary claude-btn" onclick="claudeSend()" title="Send (Enter)">
                <i class="fa-solid fa-paper-plane"></i>
            </button>
            <button id="claude-cancel-btn" class="btn btn-outline-danger claude-btn" onclick="claudeCancel()" title="Cancel" style="display:none;">
                <i class="fa-solid fa-stop"></i>
            </button>
            <button id="claude-reset-btn" class="btn btn-outline-secondary claude-btn" onclick="claudeReset()" title="New conversation">
                <i class="fa-solid fa-rotate-right"></i>
            </button>
            <button class="btn btn-outline-secondary claude-btn" onclick="showSaveToCaseModal()" title="Save to case">
                <i class="fa-solid fa-briefcase"></i>
            </button>
            <button class="btn btn-outline-secondary claude-btn" onclick="showWrapUpModal()" title="Wrap up session">
                <i class="fa-solid fa-flag-checkered"></i>
            </button>
        </div>
        <div class="claude-input-footer">
            <div class="claude-input-hint">Enter to send, Shift+Enter for newline, Esc to stop</div>
            <div id="claude-context-usage" class="claude-context-usage"></div>
        </div>
    </div>
</div>

<script>
const CLAUDE_WORKTREE = '`)
//line views/claude.qtpl:56
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/claude.qtpl:56
	qw422016.N().S(`';
const CLAUDE_SESSION = '`)
//line views/claude.qtpl:57
	qw422016.E().S(JSAttr(p.SessionID))
//line views/claude.qtpl:57
	qw422016.N().S(`';

function showSaveToCaseModal() {
    // Fetch open cases for this worktree
    fetch('/api/v1/cases/' + encodeURIComponent(CLAUDE_WORKTREE))
    .then(r => r.json())
    .then(data => {
        const cases = data.data || data || [];
        const select = document.getElementById('saveToCaseSelect');
        select.innerHTML = '<option value="">-- Select a case --</option>';
        cases.forEach(c => {
            const opt = document.createElement('option');
            opt.value = c.id;
            opt.textContent = '[' + c.kind + '] ' + c.title;
            select.appendChild(opt);
        });
        select.innerHTML += '<option value="__new__">+ Create new case...</option>';
        document.getElementById('saveToCaseNewFields').style.display = 'none';
        const modal = new bootstrap.Modal(document.getElementById('saveToCaseModal'));
        modal.show();
    })
    .catch(err => alert('Failed to load cases: ' + err));
}

function onSaveToCaseSelectChange() {
    const val = document.getElementById('saveToCaseSelect').value;
    document.getElementById('saveToCaseNewFields').style.display = (val === '__new__') ? 'block' : 'none';
}

function saveToCaseConfirm() {
    const selectVal = document.getElementById('saveToCaseSelect').value;
    const title = document.getElementById('saveToCaseTitle').value.trim();

    if (selectVal === '__new__') {
        const newTitle = document.getElementById('saveToCaseNewTitle').value.trim();
        const newKind = document.getElementById('saveToCaseNewKind').value;
        if (!newTitle) { alert('Title is required'); return; }
        // Create case first, then save transcript
        fetch('/api/v1/cases/' + encodeURIComponent(CLAUDE_WORKTREE), {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({title: newTitle, kind: newKind})
        })
        .then(r => {
            if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Create failed'); });
            return r.json();
        })
        .then(data => {
            const c = data.data || data;
            return doSaveTranscript(c.id, title);
        })
        .catch(err => alert('Failed: ' + err));
    } else if (selectVal) {
        doSaveTranscript(selectVal, title);
    } else {
        alert('Please select a case');
    }
}

function doSaveTranscript(caseId, title) {
    fetch('/api/v1/cases/' + encodeURIComponent(CLAUDE_WORKTREE) + '/' + encodeURIComponent(caseId) + '/transcript', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({session_id: CLAUDE_SESSION, title: title || ''})
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Save failed'); });
        return r.json();
    })
    .then(() => {
        bootstrap.Modal.getInstance(document.getElementById('saveToCaseModal')).hide();
        alert('Transcript saved to case.');
    })
    .catch(err => alert('Save failed: ' + err));
}
</script>

<!-- Save to Case Modal -->
<div class="modal fade" id="saveToCaseModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-briefcase"></i> Save Transcript to Case</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="saveToCaseSelect" class="form-label">Case</label>
                    <select class="form-select" id="saveToCaseSelect" onchange="onSaveToCaseSelectChange()"></select>
                </div>
                <div id="saveToCaseNewFields" style="display:none;">
                    <div class="mb-3">
                        <label for="saveToCaseNewTitle" class="form-label">New Case Title</label>
                        <input type="text" class="form-control" id="saveToCaseNewTitle" placeholder="Bug investigation">
                    </div>
                    <div class="mb-3">
                        <label for="saveToCaseNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="saveToCaseNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="saveToCaseTitle" class="form-label">Transcript Title (optional)</label>
                    <input type="text" class="form-control" id="saveToCaseTitle" placeholder="Session export">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="saveToCaseConfirm()">Save</button>
            </div>
        </div>
    </div>
</div>
<script>
const WRAPUP_WORKTREE = CLAUDE_WORKTREE;
const WRAPUP_SESSION_ID = CLAUDE_SESSION;
let WRAPUP_CASE = null;
</script>

<!-- Wrap Up Modal -->
<div class="modal fade" id="wrapUpModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-flag-checkered"></i> Wrap Up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div id="wrapUpError" class="alert alert-danger" style="display:none"></div>
                <div id="wrapUpSuccess" class="alert alert-success" style="display:none"></div>

                <!-- Existing case info (read-only) -->
                <div id="wrapUpCaseInfo" style="display:none" class="mb-3">
                    <div class="card card-body bg-light">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-secondary" id="wrapUpCaseKind"></span>
                            <strong id="wrapUpCaseTitle"></strong>
                            <code class="ms-auto" id="wrapUpCaseId"></code>
                        </div>
                    </div>
                </div>

                <!-- New case fields (editable) -->
                <div id="wrapUpNewCase" style="display:none">
                    <div class="mb-3">
                        <label for="wrapUpNewTitle" class="form-label">Case Title</label>
                        <input type="text" class="form-control" id="wrapUpNewTitle" placeholder="Fix login bug" oninput="updateWrapUpCommitMsg()">
                    </div>
                    <div class="mb-3">
                        <label for="wrapUpNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="wrapUpNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>

                <!-- Files -->
                <div class="mb-3">
                    <label class="form-label">Files to commit</label>
                    <div id="wrapUpFileList" class="wrap-up-file-list"></div>
                </div>

                <!-- Commit message -->
                <div class="mb-3">
                    <label for="wrapUpCommitMsg" class="form-label">Commit message</label>
                    <textarea class="form-control" id="wrapUpCommitMsg" rows="3"></textarea>
                </div>

                <!-- Links -->
                <div class="mb-3">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <label class="form-label mb-0">Links (optional)</label>
                        <button class="btn btn-outline-secondary btn-sm" type="button" onclick="addWrapUpLink()">
                            <i class="fa-solid fa-plus"></i> Add
                        </button>
                    </div>
                    <div id="wrapUpLinks"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="wrapUpConfirmBtn" onclick="wrapUpConfirm()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.1/marked.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="/static/js/claude.js"></script>
<script src="/static/js/wrapup.js"></script>
<script src="/static/js/workflow_picker.js"></script>

`)
//line views/claude.qtpl:259
	p.StreamFooter(qw422016)
//line views/claude.qtpl:259
	qw422016.N().S(`
`)
//line views/claude.qtpl:260
}

//line views/claude.qtpl:260
func (p *ClaudePage) WriteRender(qq422016 qtio422016.Writer) {
//line views/claude.qtpl:260
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/claude.qtpl:260
	p.StreamRender(qw422016)
//line views/claude.qtpl:260
	qt422016.ReleaseWriter(qw422016)
//line views/claude.qtpl:260
}

//line views/claude.qtpl:260
func (p *ClaudePage) Render() string {
//line views/claude.qtpl:260
	qb422016 := qt422016.AcquireByteBuffer()
//line views/claude.qtpl:260
	p.WriteRender(qb422016)
//line views/claude.qtpl:260
	qs422016 := string(qb422016.B)
//line views/claude.qtpl:260
	qt422016.ReleaseByteBuffer(qb422016)
//line views/claude.qtpl:260
	return qs422016
//line views/claude.qtpl:260
}
