// Code generated by qtc from "codex.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/codex.qtpl:4
package views

//line views/codex.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/codex.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/codex.qtpl:5
type CodexPage struct {
	BasePage
	WorktreeName     string
	SessionID        string
	SessionName      string // Session display name (e.g. "Session 1" or a user-given name)
	SessionCreatedAt string // ISO 8601 timestamp
	IsDefaultBranch  bool   // Worktree is on the repo's default branch (main/master)
}

//line views/codex.qtpl:15
func (p *CodexPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/codex.qtpl:15
	qw422016.N().S(`
`)
//line views/codex.qtpl:16
	p.StreamHeader(qw422016)
//line views/codex.qtpl:16
	qw422016.N().S(`

<link href="/static/css/codex.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css" id="hljs-light-codex">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" id="hljs-dark-codex" disabled>
<script>
    (function() {
        const theme = document.documentElement.getAttribute('data-theme') || 'light';
        document.getElementById('hljs-light-codex').disabled = (theme === 'dark');
        document.getElementById('hljs-dark-codex').disabled = (theme !== 'dark');
    })();
</script>

<!-- data-agent/session/worktree let per-page scripts (pair.js, checklist.js)
     identify their session from their own .page-container instead of window
     globals, which go stale when the SPA swaps pages. -->
<div id="codex-chat" class="codex-chat-container" data-agent="codex" data-session="`)
//line views/codex.qtpl:32
	qw422016.E().S(p.SessionID)
//line views/codex.qtpl:32
	qw422016.N().S(`" data-worktree="`)
//line views/codex.qtpl:32
	qw422016.E().S(p.WorktreeName)
//line views/codex.qtpl:32
	qw422016.N().S(`">
    <div id="codex-messages" class="codex-messages"></div>
    <div id="codex-input-area" class="codex-input-area">
        <div class="codex-input-row">
            <textarea id="codex-input" class="codex-input" placeholder="Ask Codex..." rows="1"></textarea>
            <button id="codex-send-btn" class="btn btn-primary codex-btn" onclick="codexSend()" title="Send (Enter)">
                <i class="fa-solid fa-paper-plane"></i>
            </button>
            <button id="codex-cancel-btn" class="btn btn-outline-danger codex-btn" onclick="codexCancel()" title="Cancel" style="display:none;">
                <i class="fa-solid fa-stop"></i>
            </button>
            <div class="dropup codex-actions">
                <button type="button" class="btn btn-outline-secondary codex-btn" data-bs-toggle="dropdown" aria-expanded="false" title="More actions">
                    <i class="fa-solid fa-ellipsis-vertical"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><button class="dropdown-item" type="button" onclick="showCodexSaveToCaseModal()"><i class="fa-solid fa-briefcase fa-fw"></i> Save to case</button></li>
                    <li><button class="dropdown-item" type="button" onclick="showCommitModal('commit')"><i class="fa-solid fa-code-commit fa-fw"></i> Commit</button></li>
                    <li><button class="dropdown-item" type="button" onclick="showCommitModal('wrapup')"><i class="fa-solid fa-flag-checkered fa-fw"></i> Wrap up</button></li>
                    <!-- pair.js and checklist.js inject their items at the end of this menu -->
                </ul>
            </div>
        </div>
        <div class="codex-input-footer">
            <div class="codex-input-hint">Enter to send, Shift+Enter for newline, Esc to stop</div>
            <div class="codex-footer-right">
                <!-- Options beyond Default are filled in by codex.js from the
                     model_options catalog on the WS history message. -->
                <select id="codex-model-select" class="codex-model-select" title="Model — applies from your next message. Default = the model from your ~/.codex/config.toml." onchange="codexSetModel(this.value)">
                    <option value="">Default</option>
                </select>
                <label class="codex-skip-perms" id="codex-skip-perms" title="Auto-approve tool use — Codex stops asking approval and runs without a sandbox. Execpolicy forbidden rules in ~/.codex/rules/ still apply.">
                    <input type="checkbox" id="codex-skip-perms-cb" onchange="codexSetSkipPermissions(this.checked)"> auto-approve
                </label>
                <div id="codex-context-usage" class="codex-context-usage"></div>
            </div>
        </div>
    </div>
</div>

<script>
(function() {
'use strict';
// PAGE_* hold THIS session's values. window.CODEX_*, window.WRAPUP_*, and
// the save-to-case window handlers are re-bound to these page-local values
// on every trellis:page-entered; mutable wrap-up state is snapshotted on
// page-leaving. Without this, the SPA cache restore would leave globals
// pointing at whichever Codex session was most recently fresh-loaded.
var PAGE_WORKTREE = '`)
//line views/codex.qtpl:80
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/codex.qtpl:80
	qw422016.N().S(`';
var PAGE_SESSION = '`)
//line views/codex.qtpl:81
	qw422016.E().S(JSAttr(p.SessionID))
//line views/codex.qtpl:81
	qw422016.N().S(`';
var PAGE_SESSION_NAME = '`)
//line views/codex.qtpl:82
	qw422016.E().S(JSAttr(p.SessionName))
//line views/codex.qtpl:82
	qw422016.N().S(`';
var PAGE_SESSION_CREATED = '`)
//line views/codex.qtpl:83
	qw422016.E().S(JSAttr(p.SessionCreatedAt))
//line views/codex.qtpl:83
	qw422016.N().S(`';
var PAGE_IS_DEFAULT_BRANCH = `)
//line views/codex.qtpl:84
	if p.IsDefaultBranch {
//line views/codex.qtpl:84
		qw422016.N().S(`true`)
//line views/codex.qtpl:84
	} else {
//line views/codex.qtpl:84
		qw422016.N().S(`false`)
//line views/codex.qtpl:84
	}
//line views/codex.qtpl:84
	qw422016.N().S(`;
var PAGE_WORKTREE_NAME_HUMANIZED = (PAGE_WORKTREE || '').split(/[-_]+/).map(function(w) {
    return w ? w[0].toUpperCase() + w.slice(1) : '';
}).join(' ');

function localShowCodexSaveToCaseModal() {
    fetch('/api/v1/cases/' + encodeURIComponent(PAGE_WORKTREE))
    .then(r => r.json())
    .then(data => {
        const cases = data.data || data || [];
        const select = document.getElementById('codexSaveToCaseSelect');
        select.innerHTML = '<option value="">-- Select a case --</option>';
        cases.forEach(c => {
            const opt = document.createElement('option');
            opt.value = c.id;
            opt.textContent = '[' + c.kind + '] ' + c.title;
            select.appendChild(opt);
        });
        select.innerHTML += '<option value="__new__">+ Create new case...</option>';
        document.getElementById('codexSaveToCaseNewFields').style.display = 'none';
        const modal = bootstrap.Modal.getOrCreateInstance(document.getElementById('codexSaveToCaseModal'));
        modal.show();
    })
    .catch(err => alert('Failed to load cases: ' + err));
}

function localOnCodexSaveToCaseSelectChange() {
    const val = document.getElementById('codexSaveToCaseSelect').value;
    document.getElementById('codexSaveToCaseNewFields').style.display = (val === '__new__') ? 'block' : 'none';
}

function localCodexSaveToCaseConfirm() {
    const selectVal = document.getElementById('codexSaveToCaseSelect').value;
    const title = document.getElementById('codexSaveToCaseTitle').value.trim();

    function doSave(caseId) {
        fetch('/api/v1/cases/' + encodeURIComponent(PAGE_WORKTREE) + '/' + encodeURIComponent(caseId) + '/codex-transcript', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: PAGE_SESSION, title: title || ''})
        })
        .then(r => {
            if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Save failed'); });
            return r.json();
        })
        .then(() => {
            bootstrap.Modal.getInstance(document.getElementById('codexSaveToCaseModal')).hide();
            alert('Transcript saved to case.');
        })
        .catch(err => alert('Save failed: ' + err));
    }

    if (selectVal === '__new__') {
        const newTitle = document.getElementById('codexSaveToCaseNewTitle').value.trim();
        const newKind = document.getElementById('codexSaveToCaseNewKind').value;
        if (!newTitle) { alert('Title is required'); return; }
        fetch('/api/v1/cases/' + encodeURIComponent(PAGE_WORKTREE), {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({title: newTitle, kind: newKind})
        })
        .then(r => {
            if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Create failed'); });
            return r.json();
        })
        .then(data => {
            const c = data.data || data;
            doSave(c.id);
        })
        .catch(err => alert('Failed: ' + err));
    } else if (selectVal) {
        doSave(selectVal);
    } else {
        alert('Please select a case');
    }
}

var snap = { caseObj: null };
function captureWrap() {
    snap.caseObj = window.WRAPUP_CASE;
}
function bind() {
    window.CODEX_WORKTREE = PAGE_WORKTREE;
    window.CODEX_SESSION = PAGE_SESSION;
    window.WRAPUP_AGENT = 'codex';
    window.WRAPUP_WORKTREE = PAGE_WORKTREE;
    window.WRAPUP_SESSION_ID = PAGE_SESSION;
    window.WRAPUP_SESSION_NAME = PAGE_SESSION_NAME;
    window.WRAPUP_SESSION_CREATED = PAGE_SESSION_CREATED;
    window.WRAPUP_WORKTREE_NAME_HUMANIZED = PAGE_WORKTREE_NAME_HUMANIZED;
    window.WRAPUP_IS_DEFAULT_BRANCH = PAGE_IS_DEFAULT_BRANCH;
    window.WRAPUP_CASE = snap.caseObj;
    window.showCodexSaveToCaseModal = localShowCodexSaveToCaseModal;
    window.onCodexSaveToCaseSelectChange = localOnCodexSaveToCaseSelectChange;
    window.codexSaveToCaseConfirm = localCodexSaveToCaseConfirm;
}
bind();
var container = document.currentScript && document.currentScript.closest('.page-container');
if (container) {
    container.addEventListener('trellis:page-leaving', captureWrap);
    container.addEventListener('trellis:page-entered', bind);
}
})();
</script>

<!-- Save to Case Modal -->
<div class="modal fade" id="codexSaveToCaseModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-briefcase"></i> Save Transcript to Case</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="codexSaveToCaseSelect" class="form-label">Case</label>
                    <select class="form-select" id="codexSaveToCaseSelect" onchange="onCodexSaveToCaseSelectChange()"></select>
                </div>
                <div id="codexSaveToCaseNewFields" style="display:none;">
                    <div class="mb-3">
                        <label for="codexSaveToCaseNewTitle" class="form-label">New Case Title</label>
                        <input type="text" class="form-control" id="codexSaveToCaseNewTitle" placeholder="Bug investigation">
                    </div>
                    <div class="mb-3">
                        <label for="codexSaveToCaseNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="codexSaveToCaseNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="codexSaveToCaseTitle" class="form-label">Transcript Title (optional)</label>
                    <input type="text" class="form-control" id="codexSaveToCaseTitle" placeholder="Session export">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="codexSaveToCaseConfirm()">Save</button>
            </div>
        </div>
    </div>
</div>

<!-- Wrap Up Modal — same structure as the Claude one; wrapup.js drives it -->
<div class="modal fade" id="wrapUpModal" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-flag-checkered"></i> Wrap Up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div id="wrapUpError" class="alert alert-danger" style="display:none"></div>
                <div id="wrapUpSuccess" class="alert alert-success" style="display:none"></div>

                <div id="wrapUpCaseInfo" style="display:none" class="mb-3">
                    <div class="card card-body bg-light">
                        <div class="d-flex align-items-center gap-2">
                            <span class="badge bg-secondary" id="wrapUpCaseKind"></span>
                            <strong id="wrapUpCaseTitle"></strong>
                            <code class="ms-auto" id="wrapUpCaseId"></code>
                        </div>
                    </div>
                </div>

                <div id="wrapUpNewCase" style="display:none">
                    <div class="mb-3">
                        <label for="wrapUpNewTitle" class="form-label">Case Title</label>
                        <input type="text" class="form-control" id="wrapUpNewTitle" placeholder="Fix login bug" oninput="updateWrapUpCommitMsg()">
                    </div>
                    <div class="mb-3">
                        <label for="wrapUpNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="wrapUpNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation">Investigation</option>
                        </select>
                    </div>
                </div>

                <div class="mb-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <label class="form-label mb-1">Files to commit</label>
                        <span class="small">
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpFileList', true); return false;">all</a>
                            /
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpFileList', false); return false;">none</a>
                        </span>
                    </div>
                    <div id="wrapUpFileList" class="wrap-up-file-list"></div>
                </div>

                <div class="mb-3" id="wrapUpTraceSection" style="display:none">
                    <div class="d-flex justify-content-between align-items-center">
                        <label class="form-label mb-1">Traces to include</label>
                        <span class="small">
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpTraceList', true); return false;">all</a>
                            /
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpTraceList', false); return false;">none</a>
                        </span>
                    </div>
                    <div id="wrapUpTraceList" class="wrap-up-file-list"></div>
                </div>

                <div class="mb-3" id="wrapUpRelatedSection" style="display:none">
                    <div class="d-flex justify-content-between align-items-center">
                        <label class="form-label mb-1" id="wrapUpRelatedLabel">Related sessions to archive</label>
                        <span class="small">
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpRelatedList', true); return false;">all</a>
                            /
                            <a href="#" onclick="toggleAllCheckboxes('wrapUpRelatedList', false); return false;">none</a>
                        </span>
                    </div>
                    <div id="wrapUpRelatedList" class="wrap-up-file-list"></div>
                </div>

                <!-- Generated tags (wrap-up only) -->
                <div class="mb-3" id="wrapUpTagsSection" style="display:none">
                    <div class="d-flex justify-content-end align-items-center mb-1">
                        <span class="small text-muted" id="wrapUpTagsStatus"></span>
                    </div>
                    <div>
                        <div class="text-muted small">Components</div>
                        <div id="wrapUpComponentsList" class="wrap-up-chip-list"></div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="wrapUpCommitMsg" class="form-label">Commit message</label>
                    <textarea class="form-control" id="wrapUpCommitMsg" rows="3"></textarea>
                </div>

                <div class="mb-3" id="wrapUpLinksSection">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <label class="form-label mb-0">Links (optional)</label>
                        <button class="btn btn-outline-secondary btn-sm" type="button" onclick="addWrapUpLink()">
                            <i class="fa-solid fa-plus"></i> Add
                        </button>
                    </div>
                    <div id="wrapUpLinks"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="wrapUpConfirmBtn" onclick="wrapUpConfirm()">
                    <i class="fa-solid fa-flag-checkered"></i> Wrap Up
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Fork Session Modal -->
<div class="modal fade" id="codexForkModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-code-branch"></i> Fork Session</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p class="text-muted small mb-3" id="codexForkSubtitle"></p>
                <div class="mb-3">
                    <label for="codexForkName" class="form-label">New session name</label>
                    <input type="text" class="form-control" id="codexForkName" placeholder="e.g. Alternate path">
                </div>
                <input type="hidden" id="codexForkIndex" value="">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="codexForkConfirm" onclick="codexForkSubmit()">
                    <i class="fa-solid fa-code-branch"></i> Create Fork
                </button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/12.0.1/marked.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.1.6/purify.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
<script src="/static/js/codex.js"></script>
<script src="/static/js/pair.js"></script>
<script src="/static/js/checklist.js"></script>
<script src="/static/js/wrapup.js"></script>
<script src="/static/js/workflow_picker.js"></script>

`)
//line views/codex.qtpl:375
	p.StreamFooter(qw422016)
//line views/codex.qtpl:375
	qw422016.N().S(`
`)
//line views/codex.qtpl:376
}

//line views/codex.qtpl:376
func (p *CodexPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/codex.qtpl:376
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/codex.qtpl:376
	p.StreamRender(qw422016)
//line views/codex.qtpl:376
	qt422016.ReleaseWriter(qw422016)
//line views/codex.qtpl:376
}

//line views/codex.qtpl:376
func (p *CodexPage) Render() string {
//line views/codex.qtpl:376
	qb422016 := qt422016.AcquireByteBuffer()
//line views/codex.qtpl:376
	p.WriteRender(qb422016)
//line views/codex.qtpl:376
	qs422016 := string(qb422016.B)
//line views/codex.qtpl:376
	qt422016.ReleaseByteBuffer(qb422016)
//line views/codex.qtpl:376
	return qs422016
//line views/codex.qtpl:376
}
