// Code generated by qtc from "crash_detail.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/crash_detail.qtpl:4
package views

//line views/crash_detail.qtpl:4
import "github.com/wingedpig/trellis/internal/crashes"

//line views/crash_detail.qtpl:5
import "encoding/json"

//line views/crash_detail.qtpl:6
import "time"

//line views/crash_detail.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/crash_detail.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/crash_detail.qtpl:9
type CrashDetailPage struct {
	BasePage
	Crash *crashes.Crash
}

func (p *CrashDetailPage) EntriesJSON() string {
	data, _ := json.Marshal(p.Crash.Entries)
	return string(data)
}

//line views/crash_detail.qtpl:20
func (p *CrashDetailPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/crash_detail.qtpl:20
	qw422016.N().S(`
`)
//line views/crash_detail.qtpl:21
	p.StreamHeader(qw422016)
//line views/crash_detail.qtpl:21
	qw422016.N().S(`
<!-- Uses shared CSS from /static/css/logviewer.css -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/crashes">Crash Reports</a></li>
        <li class="breadcrumb-item active" aria-current="page">`)
//line views/crash_detail.qtpl:27
	qw422016.E().S(p.Crash.ID)
//line views/crash_detail.qtpl:27
	qw422016.N().S(`</li>
    </ol>
</nav>

<h2 class="mb-4">
    <i class="fa-solid fa-skull-crossbones text-danger"></i> Crash: `)
//line views/crash_detail.qtpl:32
	qw422016.E().S(p.Crash.Service)
//line views/crash_detail.qtpl:32
	qw422016.N().S(`
</h2>

<!-- Summary Card -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fa-solid fa-info-circle"></i> Summary
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-sm mb-0">
                    <tr>
                        <th style="width: 120px;">ID</th>
                        <td><code>`)
//line views/crash_detail.qtpl:46
	qw422016.E().S(p.Crash.ID)
//line views/crash_detail.qtpl:46
	qw422016.N().S(`</code></td>
                    </tr>
                    <tr>
                        <th>Service</th>
                        <td><span class="badge bg-danger">`)
//line views/crash_detail.qtpl:50
	qw422016.E().S(p.Crash.Service)
//line views/crash_detail.qtpl:50
	qw422016.N().S(`</span></td>
                    </tr>
                    <tr>
                        <th>Timestamp</th>
                        <td class="crash-time" data-time="`)
//line views/crash_detail.qtpl:54
	qw422016.E().S(p.Crash.Timestamp.Format(time.RFC3339))
//line views/crash_detail.qtpl:54
	qw422016.N().S(`"></td>
                    </tr>
                    <tr>
                        <th>Exit Code</th>
                        <td><code>`)
//line views/crash_detail.qtpl:58
	qw422016.N().D(p.Crash.ExitCode)
//line views/crash_detail.qtpl:58
	qw422016.N().S(`</code></td>
                    </tr>
                    `)
//line views/crash_detail.qtpl:60
	if p.Crash.TraceID != "" {
//line views/crash_detail.qtpl:60
		qw422016.N().S(`
                    <tr>
                        <th>Trace ID</th>
                        <td><code>`)
//line views/crash_detail.qtpl:63
		qw422016.E().S(p.Crash.TraceID)
//line views/crash_detail.qtpl:63
		qw422016.N().S(`</code></td>
                    </tr>
                    `)
//line views/crash_detail.qtpl:65
	}
//line views/crash_detail.qtpl:65
	qw422016.N().S(`
                    <tr>
                        <th>Total Entries</th>
                        <td>`)
//line views/crash_detail.qtpl:68
	qw422016.N().D(p.Crash.Summary.TotalEntries)
//line views/crash_detail.qtpl:68
	qw422016.N().S(`</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-6">
                `)
//line views/crash_detail.qtpl:73
	if p.Crash.Worktree.Name != "" {
//line views/crash_detail.qtpl:73
		qw422016.N().S(`
                <table class="table table-sm mb-0">
                    <tr>
                        <th style="width: 120px;">Worktree</th>
                        <td>`)
//line views/crash_detail.qtpl:77
		qw422016.E().S(p.Crash.Worktree.Name)
//line views/crash_detail.qtpl:77
		qw422016.N().S(`</td>
                    </tr>
                    <tr>
                        <th>Branch</th>
                        <td>`)
//line views/crash_detail.qtpl:81
		qw422016.E().S(p.Crash.Worktree.Branch)
//line views/crash_detail.qtpl:81
		qw422016.N().S(`</td>
                    </tr>
                    <tr>
                        <th>Path</th>
                        <td><code class="small">`)
//line views/crash_detail.qtpl:85
		qw422016.E().S(p.Crash.Worktree.Path)
//line views/crash_detail.qtpl:85
		qw422016.N().S(`</code></td>
                    </tr>
                </table>
                `)
//line views/crash_detail.qtpl:88
	}
//line views/crash_detail.qtpl:88
	qw422016.N().S(`
                `)
//line views/crash_detail.qtpl:89
	if len(p.Crash.Summary.BySource) > 0 {
//line views/crash_detail.qtpl:89
		qw422016.N().S(`
                <table class="table table-sm mb-0 mt-2">
                    <tr>
                        <th colspan="2">Entries by Source</th>
                    </tr>
                    `)
//line views/crash_detail.qtpl:94
		for source, count := range p.Crash.Summary.BySource {
//line views/crash_detail.qtpl:94
			qw422016.N().S(`
                    <tr>
                        <td>`)
//line views/crash_detail.qtpl:96
			qw422016.E().S(source)
//line views/crash_detail.qtpl:96
			qw422016.N().S(`</td>
                        <td>`)
//line views/crash_detail.qtpl:97
			qw422016.N().D(count)
//line views/crash_detail.qtpl:97
			qw422016.N().S(`</td>
                    </tr>
                    `)
//line views/crash_detail.qtpl:99
		}
//line views/crash_detail.qtpl:99
		qw422016.N().S(`
                </table>
                `)
//line views/crash_detail.qtpl:101
	}
//line views/crash_detail.qtpl:101
	qw422016.N().S(`
            </div>
        </div>
    </div>
</div>

<!-- Error Message -->
`)
//line views/crash_detail.qtpl:108
	if p.Crash.Error != "" {
//line views/crash_detail.qtpl:108
		qw422016.N().S(`
<div class="card mb-3">
    <div class="card-header">
        <i class="fa-solid fa-exclamation-triangle text-danger"></i> Error
    </div>
    <div class="card-body">
        <pre class="crash-stack bg-dark text-light p-3 rounded mb-0">`)
//line views/crash_detail.qtpl:114
		qw422016.E().S(p.Crash.Error)
//line views/crash_detail.qtpl:114
		qw422016.N().S(`</pre>
    </div>
</div>
`)
//line views/crash_detail.qtpl:117
	}
//line views/crash_detail.qtpl:117
	qw422016.N().S(`

<!-- Log Entries -->
<div class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-list"></i> Log Entries (`)
//line views/crash_detail.qtpl:122
	qw422016.N().D(len(p.Crash.Entries))
//line views/crash_detail.qtpl:122
	qw422016.N().S(`)</span>
    </div>
    <div class="card-body p-0">
        `)
//line views/crash_detail.qtpl:125
	if len(p.Crash.Entries) == 0 {
//line views/crash_detail.qtpl:125
		qw422016.N().S(`
        <div class="alert alert-info m-3">
            <i class="fa-solid fa-info-circle"></i> No log entries captured for this crash.
        </div>
        `)
//line views/crash_detail.qtpl:129
	} else {
//line views/crash_detail.qtpl:129
		qw422016.N().S(`
        <div class="trace-filter-bar">
            <i class="fa-solid fa-search text-muted"></i>
            <input type="text" id="filterInput" placeholder="Filter: source:api level:error message text..."
                   onkeyup="filterEntries(event)">
            <button class="btn btn-sm btn-outline-secondary" onclick="clearFilter()" title="Clear filter">
                <i class="fa-solid fa-times"></i>
            </button>
            <button id="timestampToggleBtn" class="btn btn-sm btn-outline-secondary" onclick="toggleTimestampFormat()" title="Switch to relative timestamps">
                Relative
            </button>
        </div>
        <div class="trace-wrapper">
            <div class="trace-log" id="crashLog"></div>
            <div class="trace-expanded" id="crashExpanded" style="display: none;">
                <div class="trace-expanded-header">
                    <span>Entry Details</span>
                    <button onclick="closeExpanded()"><i class="fa-solid fa-times"></i></button>
                </div>
                <div class="trace-expanded-content" id="crashExpandedContent"></div>
            </div>
        </div>
        `)
//line views/crash_detail.qtpl:151
	}
//line views/crash_detail.qtpl:151
	qw422016.N().S(`
    </div>
</div>

<div class="mt-3">
    <a href="/crashes" class="btn btn-secondary">
        <i class="fa-solid fa-arrow-left"></i> Back to Crashes
    </a>
    <button class="btn btn-outline-danger float-end" onclick="deleteAndGoBack()">
        <i class="fa-solid fa-trash"></i> Delete Crash
    </button>
</div>

<script>
// Uses shared functions from /static/js/logviewer.js
var allEntries = `)
//line views/crash_detail.qtpl:166
	qw422016.N().S(p.EntriesJSON())
//line views/crash_detail.qtpl:166
	qw422016.N().S(`;
var filteredEntries = [];
var selectedEntry = null;
var crashTimestampAbsolute = true;

// Default layout for crash entries (timestamp, source, level, message)
var defaultLayout = [
    {field: 'timestamp', timestamp: true, min_width: 12},
    {field: 'level', min_width: 5},
    {field: 'message'}
];

function renderCrashEntry(entry, index) {
    renderLogEntry(entry, {
        container: document.getElementById('crashLog'),
        layout: defaultLayout,
        fieldMap: {},
        formatTs: function(ts) { return formatTimestamp(ts, crashTimestampAbsolute); },
        onExpand: expandCrashEntry,
        entryIndex: index,
        rowClass: 'trace-entry',
        prependColumns: [{
            name: 'source',
            width: '100px',
            getValue: function(e) { return e.source || ''; }
        }]
    });
}

function renderEntries() {
    var container = document.getElementById('crashLog');
    container.innerHTML = '';
    for (var i = 0; i < filteredEntries.length; i++) {
        renderCrashEntry(filteredEntries[i], i);
    }
}

function filterEntries(event) {
    if (event && event.key === 'Escape') {
        clearFilter();
        return;
    }
    var query = document.getElementById('filterInput').value;
    filteredEntries = allEntries.filter(function(e) { return matchesLogFilter(e, query); });
    renderEntries();
}

function clearFilter() {
    document.getElementById('filterInput').value = '';
    filteredEntries = allEntries.slice();
    renderEntries();
}

function expandCrashEntry(entry) {
    selectedEntry = entry;
    expandEntry(entry, {
        expandedEl: document.getElementById('crashExpanded'),
        contentEl: document.getElementById('crashExpandedContent'),
        fieldNames: null,
        tbodySelector: '#crashLog',
        filteredEntries: filteredEntries,
        onSelect: function(e) { selectedEntry = e; }
    });
}

function closeExpanded() {
    document.getElementById('crashExpanded').style.display = 'none';
    document.querySelectorAll('.trace-entry.selected').forEach(function(el) {
        el.classList.remove('selected');
    });
    selectedEntry = null;
}

function toggleTimestampFormat() {
    crashTimestampAbsolute = !crashTimestampAbsolute;
    renderEntries();
    var btn = document.getElementById('timestampToggleBtn');
    if (btn) {
        btn.textContent = crashTimestampAbsolute ? 'Relative' : 'Absolute';
        btn.title = crashTimestampAbsolute ? 'Switch to relative timestamps' : 'Switch to absolute timestamps';
    }
}

function deleteAndGoBack() {
    if (!confirm('Delete this crash report?')) return;
    fetch('/api/v1/crashes/`)
//line views/crash_detail.qtpl:251
	qw422016.E().S(p.Crash.ID)
//line views/crash_detail.qtpl:251
	qw422016.N().S(`', { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                window.location.href = '/crashes';
            }
        })
        .catch(function(err) { alert('Error: ' + err); });
}

function formatLocalDateTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleString([], { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
}

// Initialize
(function() {
    document.querySelectorAll('.crash-time').forEach(function(el) {
        var time = el.dataset.time;
        if (time) {
            el.textContent = formatLocalDateTime(time);
        }
    });

    filteredEntries = allEntries.slice();
    renderEntries();

    // Scroll to last entry
    var crashLog = document.getElementById('crashLog');
    if (crashLog) {
        crashLog.scrollTop = crashLog.scrollHeight;
    }

    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && selectedEntry) {
            closeExpanded();
        }
    });
})();
</script>

`)
//line views/crash_detail.qtpl:294
	p.StreamFooter(qw422016)
//line views/crash_detail.qtpl:294
	qw422016.N().S(`
`)
//line views/crash_detail.qtpl:295
}

//line views/crash_detail.qtpl:295
func (p *CrashDetailPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/crash_detail.qtpl:295
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/crash_detail.qtpl:295
	p.StreamRender(qw422016)
//line views/crash_detail.qtpl:295
	qt422016.ReleaseWriter(qw422016)
//line views/crash_detail.qtpl:295
}

//line views/crash_detail.qtpl:295
func (p *CrashDetailPage) Render() string {
//line views/crash_detail.qtpl:295
	qb422016 := qt422016.AcquireByteBuffer()
//line views/crash_detail.qtpl:295
	p.WriteRender(qb422016)
//line views/crash_detail.qtpl:295
	qs422016 := string(qb422016.B)
//line views/crash_detail.qtpl:295
	qt422016.ReleaseByteBuffer(qb422016)
//line views/crash_detail.qtpl:295
	return qs422016
//line views/crash_detail.qtpl:295
}
