// Code generated by qtc from "crashes.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/crashes.qtpl:4
package views

//line views/crashes.qtpl:4
import "github.com/wingedpig/trellis/internal/crashes"

//line views/crashes.qtpl:5
import "time"

//line views/crashes.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/crashes.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/crashes.qtpl:8
type CrashesPage struct {
	BasePage
	Crashes []crashes.CrashSummary
}

//line views/crashes.qtpl:14
func (p *CrashesPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/crashes.qtpl:14
	qw422016.N().S(`
`)
//line views/crashes.qtpl:15
	p.StreamHeader(qw422016)
//line views/crashes.qtpl:15
	qw422016.N().S(`

<h2 class="mb-4"><i class="fa-solid fa-skull-crossbones"></i> Crash Reports</h2>

<!-- Crash Reports -->
<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-file-lines"></i> Crash Reports</span>
        <div>
            `)
//line views/crashes.qtpl:24
	if len(p.Crashes) > 0 {
//line views/crashes.qtpl:24
		qw422016.N().S(`
            <button class="btn btn-sm btn-outline-danger me-2" onclick="clearAllCrashes()">
                <i class="fa-solid fa-trash"></i> Clear All
            </button>
            `)
//line views/crashes.qtpl:28
	}
//line views/crashes.qtpl:28
	qw422016.N().S(`
            <button class="btn btn-sm btn-outline-secondary" onclick="refreshReports()">
                <i class="fa-solid fa-refresh"></i>
            </button>
        </div>
    </div>
    <div class="card-body p-0">
        `)
//line views/crashes.qtpl:35
	if len(p.Crashes) == 0 {
//line views/crashes.qtpl:35
		qw422016.N().S(`
        <div class="p-3 text-muted">
            <i class="fa-solid fa-check-circle text-success"></i> No crash reports. All services running smoothly.
        </div>
        `)
//line views/crashes.qtpl:39
	} else {
//line views/crashes.qtpl:39
		qw422016.N().S(`
        <div class="table-responsive">
            <table class="table table-dark table-hover mb-0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Service</th>
                        <th>Trace ID</th>
                        <th>Exit Code</th>
                        <th>Error</th>
                        <th>Created</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="reportsTable">
                    `)
//line views/crashes.qtpl:54
		for _, c := range p.Crashes {
//line views/crashes.qtpl:54
			qw422016.N().S(`
                    <tr data-id="`)
//line views/crashes.qtpl:55
			qw422016.E().S(c.ID)
//line views/crashes.qtpl:55
			qw422016.N().S(`">
                        <td>
                            <a href="/crashes/`)
//line views/crashes.qtpl:57
			qw422016.E().S(c.ID)
//line views/crashes.qtpl:57
			qw422016.N().S(`">`)
//line views/crashes.qtpl:57
			qw422016.E().S(c.ID)
//line views/crashes.qtpl:57
			qw422016.N().S(`</a>
                        </td>
                        <td><span class="badge bg-danger">`)
//line views/crashes.qtpl:59
			qw422016.E().S(c.Service)
//line views/crashes.qtpl:59
			qw422016.N().S(`</span></td>
                        <td>
                            `)
//line views/crashes.qtpl:61
			if c.TraceID != "" {
//line views/crashes.qtpl:61
				qw422016.N().S(`
                            <code class="small">`)
//line views/crashes.qtpl:62
				qw422016.E().S(c.TraceID)
//line views/crashes.qtpl:62
				qw422016.N().S(`</code>
                            `)
//line views/crashes.qtpl:63
			} else {
//line views/crashes.qtpl:63
				qw422016.N().S(`
                            <span class="text-muted">-</span>
                            `)
//line views/crashes.qtpl:65
			}
//line views/crashes.qtpl:65
			qw422016.N().S(`
                        </td>
                        <td><code>`)
//line views/crashes.qtpl:67
			qw422016.N().D(c.ExitCode)
//line views/crashes.qtpl:67
			qw422016.N().S(`</code></td>
                        <td>
                            <span class="text-truncate d-inline-block" style="max-width: 250px;" title="`)
//line views/crashes.qtpl:69
			qw422016.E().S(c.Error)
//line views/crashes.qtpl:69
			qw422016.N().S(`">
                                `)
//line views/crashes.qtpl:70
			qw422016.E().S(c.Error)
//line views/crashes.qtpl:70
			qw422016.N().S(`
                            </span>
                        </td>
                        <td class="small text-muted created-time" data-time="`)
//line views/crashes.qtpl:73
			qw422016.E().S(c.Timestamp.Format(time.RFC3339))
//line views/crashes.qtpl:73
			qw422016.N().S(`">
                        </td>
                        <td>
                            <button class="btn btn-sm btn-outline-danger" onclick="deleteCrash('`)
//line views/crashes.qtpl:76
			qw422016.E().S(JSAttr(c.ID))
//line views/crashes.qtpl:76
			qw422016.N().S(`')">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    `)
//line views/crashes.qtpl:81
		}
//line views/crashes.qtpl:81
		qw422016.N().S(`
                </tbody>
            </table>
        </div>
        `)
//line views/crashes.qtpl:85
	}
//line views/crashes.qtpl:85
	qw422016.N().S(`
    </div>
</div>

<script>
function deleteCrash(id) {
    if (!confirm('Delete crash report "' + id + '"?')) {
        return;
    }

    fetch('/api/v1/crashes/' + encodeURIComponent(id), { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                location.reload();
            }
        })
        .catch(function(err) {
            alert('Error: ' + err);
        });
}

function clearAllCrashes() {
    if (!confirm('Delete all crash reports? This cannot be undone.')) {
        return;
    }

    fetch('/api/v1/crashes', { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                location.reload();
            }
        })
        .catch(function(err) {
            alert('Error: ' + err);
        });
}

function refreshReports() {
    location.reload();
}

function formatDateTime(d) {
    return d.toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function formatFullDateTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleString([], { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' });
}

// Initialize time displays
(function() {
    document.querySelectorAll('.created-time').forEach(function(el) {
        var time = el.dataset.time;
        if (time) {
            el.textContent = formatDateTime(new Date(time));
            el.title = formatFullDateTime(time);
        }
    });
})();
</script>

`)
//line views/crashes.qtpl:153
	p.StreamFooter(qw422016)
//line views/crashes.qtpl:153
	qw422016.N().S(`
`)
//line views/crashes.qtpl:154
}

//line views/crashes.qtpl:154
func (p *CrashesPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/crashes.qtpl:154
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/crashes.qtpl:154
	p.StreamRender(qw422016)
//line views/crashes.qtpl:154
	qt422016.ReleaseWriter(qw422016)
//line views/crashes.qtpl:154
}

//line views/crashes.qtpl:154
func (p *CrashesPage) Render() string {
//line views/crashes.qtpl:154
	qb422016 := qt422016.AcquireByteBuffer()
//line views/crashes.qtpl:154
	p.WriteRender(qb422016)
//line views/crashes.qtpl:154
	qs422016 := string(qb422016.B)
//line views/crashes.qtpl:154
	qt422016.ReleaseByteBuffer(qb422016)
//line views/crashes.qtpl:154
	return qs422016
//line views/crashes.qtpl:154
}
