// Code generated by qtc from "dashboard.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/dashboard.qtpl:4
package views

//line views/dashboard.qtpl:4
import "github.com/wingedpig/trellis/internal/service"

//line views/dashboard.qtpl:5
import "github.com/wingedpig/trellis/internal/worktree"

//line views/dashboard.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/dashboard.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/dashboard.qtpl:8
type DashboardPage struct {
	BasePage
	Services  []service.ServiceInfo
	Worktrees []worktree.WorktreeInfo
}

//line views/dashboard.qtpl:15
func (p *DashboardPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/dashboard.qtpl:15
	qw422016.N().S(`
`)
//line views/dashboard.qtpl:16
	p.StreamHeader(qw422016)
//line views/dashboard.qtpl:16
	qw422016.N().S(`

<div class="row">
    <div class="col-lg-8">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <span><i class="fa-solid fa-server"></i> Services</span>
                <div>
                    <button class="btn btn-sm btn-primary" onclick="startAll()" title="Start all services">
                        <i class="fa-solid fa-play"></i> Start All
                    </button>
                    <button class="btn btn-sm btn-outline-secondary" onclick="stopAll()" title="Stop all services">
                        <i class="fa-solid fa-stop"></i> Stop All
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                `)
//line views/dashboard.qtpl:33
	if len(p.Services) > 0 {
//line views/dashboard.qtpl:33
		qw422016.N().S(`
                <table class="table table-dark table-hover mb-0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        `)
//line views/dashboard.qtpl:43
		for _, svc := range p.Services {
//line views/dashboard.qtpl:43
			qw422016.N().S(`
                        <tr>
                            <td>
                                <a href="/services/`)
//line views/dashboard.qtpl:46
			qw422016.E().S(svc.Name)
//line views/dashboard.qtpl:46
			qw422016.N().S(`" class="text-decoration-none text-accent">`)
//line views/dashboard.qtpl:46
			qw422016.E().S(svc.Name)
//line views/dashboard.qtpl:46
			qw422016.N().S(`</a>
                            </td>
                            <td>
                                `)
//line views/dashboard.qtpl:49
			state := svc.Status.State.String()

//line views/dashboard.qtpl:49
			qw422016.N().S(`
                                <span class="badge badge-`)
//line views/dashboard.qtpl:50
			qw422016.E().S(state)
//line views/dashboard.qtpl:50
			qw422016.N().S(`">`)
//line views/dashboard.qtpl:50
			qw422016.E().S(state)
//line views/dashboard.qtpl:50
			qw422016.N().S(`</span>
                            </td>
                            <td>
                                `)
//line views/dashboard.qtpl:53
			if svc.Status.State.String() == "running" {
//line views/dashboard.qtpl:53
				qw422016.N().S(`
                                <button class="btn btn-sm btn-outline-secondary" onclick="serviceAction('`)
//line views/dashboard.qtpl:54
				qw422016.E().S(JSAttr(svc.Name))
//line views/dashboard.qtpl:54
				qw422016.N().S(`', 'stop')" title="Stop service">
                                    <i class="fa-solid fa-stop"></i>
                                </button>
                                <button class="btn btn-sm btn-outline-secondary" onclick="serviceAction('`)
//line views/dashboard.qtpl:57
				qw422016.E().S(JSAttr(svc.Name))
//line views/dashboard.qtpl:57
				qw422016.N().S(`', 'restart')" title="Restart service">
                                    <i class="fa-solid fa-rotate"></i>
                                </button>
                                `)
//line views/dashboard.qtpl:60
			} else {
//line views/dashboard.qtpl:60
				qw422016.N().S(`
                                <button class="btn btn-sm btn-primary" onclick="serviceAction('`)
//line views/dashboard.qtpl:61
				qw422016.E().S(JSAttr(svc.Name))
//line views/dashboard.qtpl:61
				qw422016.N().S(`', 'start')" title="Start service">
                                    <i class="fa-solid fa-play"></i>
                                </button>
                                `)
//line views/dashboard.qtpl:64
			}
//line views/dashboard.qtpl:64
			qw422016.N().S(`
                            </td>
                        </tr>
                        `)
//line views/dashboard.qtpl:67
		}
//line views/dashboard.qtpl:67
		qw422016.N().S(`
                    </tbody>
                </table>
                `)
//line views/dashboard.qtpl:70
	} else {
//line views/dashboard.qtpl:70
		qw422016.N().S(`
                <div class="p-3 text-muted">No services configured</div>
                `)
//line views/dashboard.qtpl:72
	}
//line views/dashboard.qtpl:72
	qw422016.N().S(`
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        `)
//line views/dashboard.qtpl:78
	if p.Worktree != nil {
//line views/dashboard.qtpl:78
		qw422016.N().S(`
        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-code-branch"></i> Active Worktree
            </div>
            <div class="card-body">
                <p class="mb-1"><strong>Name:</strong> `)
//line views/dashboard.qtpl:84
		qw422016.E().S(p.Worktree.Name())
//line views/dashboard.qtpl:84
		qw422016.N().S(`</p>
                <p class="mb-1"><strong>Branch:</strong> `)
//line views/dashboard.qtpl:85
		qw422016.E().S(p.Worktree.Branch)
//line views/dashboard.qtpl:85
		qw422016.N().S(`</p>
                <p class="mb-0"><strong>Path:</strong> <code>`)
//line views/dashboard.qtpl:86
		qw422016.E().S(p.Worktree.Path)
//line views/dashboard.qtpl:86
		qw422016.N().S(`</code></p>
            </div>
        </div>
        `)
//line views/dashboard.qtpl:89
	}
//line views/dashboard.qtpl:89
	qw422016.N().S(`

        <div class="card mb-4">
            <div class="card-header">
                <i class="fa-solid fa-link"></i> Quick Links
            </div>
            <div class="list-group list-group-flush">
                <a href="/api/v1/services" class="list-group-item list-group-item-action">Services API</a>
                <a href="/api/v1/worktrees" class="list-group-item list-group-item-action">Worktrees API</a>
                <a href="/api/v1/workflows" class="list-group-item list-group-item-action">Workflows API</a>
                <a href="/api/v1/events" class="list-group-item list-group-item-action">Events API</a>
                <a href="/api/v1/ai/context.md" class="list-group-item list-group-item-action">AI Context</a>
            </div>
        </div>
    </div>
</div>

<!-- Alert Modal -->
<div class="modal fade" id="alertModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalTitle">Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p id="alertModalMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="alertModalOk">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
function showAlert(message, title) {
    document.getElementById('alertModalTitle').textContent = title || 'Error';
    document.getElementById('alertModalMessage').textContent = message;
    var modal = new bootstrap.Modal(document.getElementById('alertModal'));
    modal.show();
    document.getElementById('alertModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('alertModalOk').focus();
    }, { once: true });
}

function serviceAction(name, action) {
    fetch('/api/v1/services/' + name + '/' + action, { method: 'POST' })
        .then(function(r) { return r.json(); })
        .then(function() { location.reload(); })
        .catch(function(err) { showAlert('Error: ' + err, 'Error'); });
}

function startAll() {
    fetch('/api/v1/workflows/_start_all/run', { method: 'POST' })
        .then(function() { location.reload(); })
        .catch(function(err) { showAlert('Error: ' + err, 'Error'); });
}

function stopAll() {
    fetch('/api/v1/workflows/_stop_all/run', { method: 'POST' })
        .then(function() { location.reload(); })
        .catch(function(err) { showAlert('Error: ' + err, 'Error'); });
}
</script>

`)
//line views/dashboard.qtpl:155
	p.StreamFooter(qw422016)
//line views/dashboard.qtpl:155
	qw422016.N().S(`
`)
//line views/dashboard.qtpl:156
}

//line views/dashboard.qtpl:156
func (p *DashboardPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/dashboard.qtpl:156
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/dashboard.qtpl:156
	p.StreamRender(qw422016)
//line views/dashboard.qtpl:156
	qt422016.ReleaseWriter(qw422016)
//line views/dashboard.qtpl:156
}

//line views/dashboard.qtpl:156
func (p *DashboardPage) Render() string {
//line views/dashboard.qtpl:156
	qb422016 := qt422016.AcquireByteBuffer()
//line views/dashboard.qtpl:156
	p.WriteRender(qb422016)
//line views/dashboard.qtpl:156
	qs422016 := string(qb422016.B)
//line views/dashboard.qtpl:156
	qt422016.ReleaseByteBuffer(qb422016)
//line views/dashboard.qtpl:156
	return qs422016
//line views/dashboard.qtpl:156
}
