// Code generated by qtc from "events.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/events.qtpl:4
package views

//line views/events.qtpl:4
import "github.com/wingedpig/trellis/internal/events"

//line views/events.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/events.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/events.qtpl:7
type EventsPage struct {
	BasePage
	Events []events.Event
}

//line views/events.qtpl:13
func (p *EventsPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/events.qtpl:13
	qw422016.N().S(`
`)
//line views/events.qtpl:14
	p.StreamHeader(qw422016)
//line views/events.qtpl:14
	qw422016.N().S(`

<div class="d-flex justify-content-between align-items-center mb-4">
    <h2><i class="fa-solid fa-clock-rotate-left"></i> Events</h2>
    <div>
        <button class="btn btn-outline-secondary" onclick="location.reload()">
            <i class="fa-solid fa-rotate"></i> Refresh
        </button>
    </div>
</div>

<div class="card">
    <div class="card-header">
        <i class="fa-solid fa-stream"></i> Recent Events
        <span class="badge bg-secondary ms-2">`)
//line views/events.qtpl:28
	qw422016.N().D(len(p.Events))
//line views/events.qtpl:28
	qw422016.N().S(`</span>
    </div>
    <div class="card-body p-0">
        `)
//line views/events.qtpl:31
	if len(p.Events) > 0 {
//line views/events.qtpl:31
		qw422016.N().S(`
        <div class="table-responsive">
            <table class="table table-dark table-hover mb-0">
                <thead>
                    <tr>
                        <th style="width: 180px;">Time</th>
                        <th style="width: 200px;">Type</th>
                        <th>Worktree</th>
                        <th>Details</th>
                    </tr>
                </thead>
                <tbody id="events-table">
                    `)
//line views/events.qtpl:43
		for _, evt := range p.Events {
//line views/events.qtpl:43
			qw422016.N().S(`
                    <tr>
                        <td>
                            <small class="text-muted">`)
//line views/events.qtpl:46
			qw422016.E().S(evt.Timestamp.Format("2006-01-02 15:04:05"))
//line views/events.qtpl:46
			qw422016.N().S(`</small>
                        </td>
                        <td>
                            `)
//line views/events.qtpl:50
			badgeClass := "bg-secondary"
			if evt.Type == "service.crashed" {
				badgeClass = "bg-danger"
			} else if evt.Type == "service.started" || evt.Type == "service.restarted" {
				badgeClass = "bg-success"
			} else if evt.Type == "workflow.finished" {
				badgeClass = "bg-info"
			} else if evt.Type == "worktree.activated" {
				badgeClass = "bg-primary"
			}

//line views/events.qtpl:60
			qw422016.N().S(`
                            <span class="badge `)
//line views/events.qtpl:61
			qw422016.E().S(badgeClass)
//line views/events.qtpl:61
			qw422016.N().S(`">`)
//line views/events.qtpl:61
			qw422016.E().S(evt.Type)
//line views/events.qtpl:61
			qw422016.N().S(`</span>
                        </td>
                        <td>`)
//line views/events.qtpl:63
			qw422016.E().S(evt.Worktree)
//line views/events.qtpl:63
			qw422016.N().S(`</td>
                        <td>
                            `)
//line views/events.qtpl:65
			if evt.Payload != nil {
//line views/events.qtpl:65
				qw422016.N().S(`
                                `)
//line views/events.qtpl:66
				for key, val := range evt.Payload {
//line views/events.qtpl:66
					qw422016.N().S(`
                                    <small class="me-2"><strong>`)
//line views/events.qtpl:67
					qw422016.E().S(key)
//line views/events.qtpl:67
					qw422016.N().S(`:</strong> `)
//line views/events.qtpl:67
					qw422016.E().V(val)
//line views/events.qtpl:67
					qw422016.N().S(`</small>
                                `)
//line views/events.qtpl:68
				}
//line views/events.qtpl:68
				qw422016.N().S(`
                            `)
//line views/events.qtpl:69
			}
//line views/events.qtpl:69
			qw422016.N().S(`
                        </td>
                    </tr>
                    `)
//line views/events.qtpl:72
		}
//line views/events.qtpl:72
		qw422016.N().S(`
                </tbody>
            </table>
        </div>
        `)
//line views/events.qtpl:76
	} else {
//line views/events.qtpl:76
		qw422016.N().S(`
        <div class="p-4 text-center text-muted">
            <i class="fa-solid fa-inbox fa-3x mb-3"></i>
            <p>No events recorded yet.</p>
        </div>
        `)
//line views/events.qtpl:81
	}
//line views/events.qtpl:81
	qw422016.N().S(`
    </div>
</div>

<script>
// Scroll to bottom to show most recent events
(function() {
    window.scrollTo(0, document.body.scrollHeight);
})();
</script>

`)
//line views/events.qtpl:92
	p.StreamFooter(qw422016)
//line views/events.qtpl:92
	qw422016.N().S(`
`)
//line views/events.qtpl:93
}

//line views/events.qtpl:93
func (p *EventsPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/events.qtpl:93
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/events.qtpl:93
	p.StreamRender(qw422016)
//line views/events.qtpl:93
	qt422016.ReleaseWriter(qw422016)
//line views/events.qtpl:93
}

//line views/events.qtpl:93
func (p *EventsPage) Render() string {
//line views/events.qtpl:93
	qb422016 := qt422016.AcquireByteBuffer()
//line views/events.qtpl:93
	p.WriteRender(qb422016)
//line views/events.qtpl:93
	qs422016 := string(qb422016.B)
//line views/events.qtpl:93
	qt422016.ReleaseByteBuffer(qb422016)
//line views/events.qtpl:93
	return qs422016
//line views/events.qtpl:93
}
