// Code generated by qtc from "services.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/services.qtpl:4
package views

//line views/services.qtpl:4
import "github.com/wingedpig/trellis/internal/service"

//line views/services.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/services.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/services.qtpl:7
type ServiceDetailPage struct {
	BasePage
	ServiceName string
	Status      service.ServiceStatus
	Logs        []string
}

//line views/services.qtpl:15
func (p *ServiceDetailPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/services.qtpl:15
	qw422016.N().S(`
`)
//line views/services.qtpl:16
	p.StreamHeader(qw422016)
//line views/services.qtpl:16
	qw422016.N().S(`

<div class="d-flex justify-content-between align-items-center mb-4">
    <h2><i class="fa-solid fa-cube"></i> `)
//line views/services.qtpl:19
	qw422016.E().S(p.ServiceName)
//line views/services.qtpl:19
	qw422016.N().S(`</h2>
    <div>
        `)
//line views/services.qtpl:21
	state := p.Status.State.String()

//line views/services.qtpl:21
	qw422016.N().S(`
        `)
//line views/services.qtpl:22
	if state == "running" {
//line views/services.qtpl:22
		qw422016.N().S(`
        <button class="btn btn-outline-secondary" onclick="serviceAction('stop')">
            <i class="fa-solid fa-stop"></i> Stop
        </button>
        <button class="btn btn-outline-secondary" onclick="serviceAction('restart')">
            <i class="fa-solid fa-rotate"></i> Restart
        </button>
        `)
//line views/services.qtpl:29
	} else {
//line views/services.qtpl:29
		qw422016.N().S(`
        <button class="btn btn-primary" onclick="serviceAction('start')">
            <i class="fa-solid fa-play"></i> Start
        </button>
        `)
//line views/services.qtpl:33
	}
//line views/services.qtpl:33
	qw422016.N().S(`
        <a href="/" class="btn btn-outline-secondary">
            <i class="fa-solid fa-arrow-left"></i> Back
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="card mb-4">
            <div class="card-header">Status</div>
            <div class="card-body">
                <p><strong>State:</strong> <span class="badge badge-`)
//line views/services.qtpl:45
	qw422016.E().S(state)
//line views/services.qtpl:45
	qw422016.N().S(`">`)
//line views/services.qtpl:45
	qw422016.E().S(state)
//line views/services.qtpl:45
	qw422016.N().S(`</span></p>
                `)
//line views/services.qtpl:46
	if p.Status.PID > 0 {
//line views/services.qtpl:46
		qw422016.N().S(`
                <p><strong>PID:</strong> `)
//line views/services.qtpl:47
		qw422016.N().D(p.Status.PID)
//line views/services.qtpl:47
		qw422016.N().S(`</p>
                `)
//line views/services.qtpl:48
	}
//line views/services.qtpl:48
	qw422016.N().S(`
                `)
//line views/services.qtpl:49
	if p.Status.ExitCode != 0 {
//line views/services.qtpl:49
		qw422016.N().S(`
                <p><strong>Exit Code:</strong> `)
//line views/services.qtpl:50
		qw422016.N().D(p.Status.ExitCode)
//line views/services.qtpl:50
		qw422016.N().S(`</p>
                `)
//line views/services.qtpl:51
	}
//line views/services.qtpl:51
	qw422016.N().S(`
                <p><strong>Restarts:</strong> `)
//line views/services.qtpl:52
	qw422016.N().D(p.Status.RestartCount)
//line views/services.qtpl:52
	qw422016.N().S(`</p>
                `)
//line views/services.qtpl:53
	if p.Status.Error != "" {
//line views/services.qtpl:53
		qw422016.N().S(`
                <p class="text-danger"><strong>Error:</strong> `)
//line views/services.qtpl:54
		qw422016.E().S(p.Status.Error)
//line views/services.qtpl:54
		qw422016.N().S(`</p>
                `)
//line views/services.qtpl:55
	}
//line views/services.qtpl:55
	qw422016.N().S(`
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <span><i class="fa-solid fa-file-lines"></i> Logs</span>
                <button class="btn btn-sm btn-outline-secondary" onclick="clearLogs()">
                    <i class="fa-solid fa-trash"></i> Clear
                </button>
            </div>
            <div class="card-body p-0">
                <pre class="m-0" style="max-height: 500px; overflow-y: auto;"><code>`)
//line views/services.qtpl:69
	for _, line := range p.Logs {
//line views/services.qtpl:69
		qw422016.E().S(line)
//line views/services.qtpl:69
		qw422016.N().S(`
`)
//line views/services.qtpl:70
	}
//line views/services.qtpl:70
	qw422016.N().S(`</code></pre>
            </div>
        </div>
    </div>
</div>

<!-- Alert Modal -->
<div class="modal fade" id="alertModalDetail" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalDetailTitle">Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p id="alertModalDetailMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="alertModalDetailOk">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
function showAlert(message, title) {
    document.getElementById('alertModalDetailTitle').textContent = title || 'Error';
    document.getElementById('alertModalDetailMessage').textContent = message;
    var modal = new bootstrap.Modal(document.getElementById('alertModalDetail'));
    modal.show();
    document.getElementById('alertModalDetail').addEventListener('shown.bs.modal', function() {
        document.getElementById('alertModalDetailOk').focus();
    }, { once: true });
}

function serviceAction(action) {
    fetch('/api/v1/services/`)
//line views/services.qtpl:106
	qw422016.E().S(p.ServiceName)
//line views/services.qtpl:106
	qw422016.N().S(`/' + action, { method: 'POST' })
        .then(function(r) { return r.json(); })
        .then(function() { location.reload(); })
        .catch(function(err) { showAlert('Error: ' + err, 'Error'); });
}

function clearLogs() {
    fetch('/api/v1/services/`)
//line views/services.qtpl:113
	qw422016.E().S(p.ServiceName)
//line views/services.qtpl:113
	qw422016.N().S(`/logs', { method: 'DELETE' })
        .then(function() { location.reload(); })
        .catch(function(err) { showAlert('Error: ' + err, 'Error'); });
}

// Auto-refresh logs
setInterval(function() {
    fetch('/api/v1/services/`)
//line views/services.qtpl:120
	qw422016.E().S(p.ServiceName)
//line views/services.qtpl:120
	qw422016.N().S(`/logs')
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.data && data.data.logs) {
                document.querySelector('pre code').textContent = data.data.logs.join('\n');
            }
        });
}, 2000);
</script>

`)
//line views/services.qtpl:130
	p.StreamFooter(qw422016)
//line views/services.qtpl:130
	qw422016.N().S(`
`)
//line views/services.qtpl:131
}

//line views/services.qtpl:131
func (p *ServiceDetailPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/services.qtpl:131
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/services.qtpl:131
	p.StreamRender(qw422016)
//line views/services.qtpl:131
	qt422016.ReleaseWriter(qw422016)
//line views/services.qtpl:131
}

//line views/services.qtpl:131
func (p *ServiceDetailPage) Render() string {
//line views/services.qtpl:131
	qb422016 := qt422016.AcquireByteBuffer()
//line views/services.qtpl:131
	p.WriteRender(qb422016)
//line views/services.qtpl:131
	qs422016 := string(qb422016.B)
//line views/services.qtpl:131
	qt422016.ReleaseByteBuffer(qb422016)
//line views/services.qtpl:131
	return qs422016
//line views/services.qtpl:131
}
