// Code generated by qtc from "status.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/status.qtpl:4
package views

//line views/status.qtpl:4
import "github.com/wingedpig/trellis/internal/service"

//line views/status.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/status.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/status.qtpl:7
type StatusPage struct {
	BasePage
	Services []service.ServiceInfo
}

//line views/status.qtpl:13
func (p *StatusPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/status.qtpl:13
	qw422016.N().S(`
`)
//line views/status.qtpl:14
	p.StreamHeader(qw422016)
//line views/status.qtpl:14
	qw422016.N().S(`

<h2 class="mb-4"><i class="fa-solid fa-server"></i> Service Status</h2>

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span>Services</span>
        <div class="d-flex gap-2">
            <button class="btn btn-sm btn-primary" onclick="startAll()" title="Start all services">
                <i class="fa-solid fa-play"></i> Start All
            </button>
            <button class="btn btn-sm btn-outline-secondary" onclick="stopAll()" title="Stop all services">
                <i class="fa-solid fa-stop"></i> Stop All
            </button>
            <button class="btn btn-sm btn-outline-secondary" onclick="refreshStatus()" title="Refresh">
                <i class="fa-solid fa-refresh"></i>
            </button>
        </div>
    </div>
    <div class="card-body p-0">
        <div class="accordion" id="statusAccordion">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#stoppedServices">
                        <i class="fa-solid fa-stop text-danger me-2"></i> Stopped <span id="stoppedCount" class="badge bg-danger ms-2">0</span>
                    </button>
                </h2>
                <div id="stoppedServices" class="accordion-collapse collapse show" data-bs-parent="#statusAccordion">
                    <div class="accordion-body p-0">
                        <table class="table table-dark table-hover mb-0">
                            <tbody id="stoppedServicesBody"></tbody>
                        </table>
                        <div id="stoppedServicesEmpty" class="p-3 text-muted text-center" style="display: none;">
                            All services are running
                        </div>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#runningServices">
                        <i class="fa-solid fa-play text-success me-2"></i> Running <span id="runningCount" class="badge bg-success ms-2">0</span>
                    </button>
                </h2>
                <div id="runningServices" class="accordion-collapse collapse" data-bs-parent="#statusAccordion">
                    <div class="accordion-body p-0">
                        <table class="table table-dark table-hover mb-0">
                            <tbody id="runningServicesBody"></tbody>
                        </table>
                        <div id="runningServicesEmpty" class="p-3 text-muted text-center" style="display: none;">
                            No services are running
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function escapeJsAttr(s) {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function loadStatusData() {
    fetch('/api/v1/services')
        .then(r => r.json())
        .then(data => {
            const services = data.data || [];
            const stoppedBody = document.getElementById('stoppedServicesBody');
            const runningBody = document.getElementById('runningServicesBody');
            stoppedBody.innerHTML = '';
            runningBody.innerHTML = '';

            services.sort((a, b) => (a.Name || '').localeCompare(b.Name || ''));

            let runningCount = 0;
            let stoppedCount = 0;

            services.forEach(svc => {
                const state = svc.Status?.State || 'unknown';
                const isRunning = state === 'running';
                const name = svc.Name || '';
                const tr = document.createElement('tr');
                tr.innerHTML = `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(`
                    <td>
                        <a href="/terminal/service/${encodeURIComponent(name)}" class="text-accent text-decoration-none">
                            ${escapeHtml(name)}
                        </a>
                    </td>
                    <td><span class="badge badge-${state}">${state}</span></td>
                    <td class="text-end">
                        ${isRunning ? `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(`
                            <button class="btn btn-sm btn-outline-secondary" onclick="serviceAction('${escapeJsAttr(name)}', 'stop')" title="Stop">
                                <i class="fa-solid fa-stop"></i>
                            </button>
                            <button class="btn btn-sm btn-outline-secondary" onclick="serviceAction('${escapeJsAttr(name)}', 'restart')" title="Restart">
                                <i class="fa-solid fa-rotate"></i>
                            </button>
                        `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(` : `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(`
                            <button class="btn btn-sm btn-primary" onclick="serviceAction('${escapeJsAttr(name)}', 'start')" title="Start">
                                <i class="fa-solid fa-play"></i>
                            </button>
                        `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(`}
                    </td>
                `)
//line views/status.qtpl:14
	qw422016.N().S("`")
//line views/status.qtpl:14
	qw422016.N().S(`;

                if (isRunning) {
                    runningBody.appendChild(tr);
                    runningCount++;
                } else {
                    stoppedBody.appendChild(tr);
                    stoppedCount++;
                }
            });

            // Update counts
            document.getElementById('stoppedCount').textContent = stoppedCount;
            document.getElementById('runningCount').textContent = runningCount;

            // Show/hide empty messages
            document.getElementById('stoppedServicesEmpty').style.display = stoppedCount === 0 ? 'block' : 'none';
            document.getElementById('runningServicesEmpty').style.display = runningCount === 0 ? 'block' : 'none';

            // Expand stopped section if there are stopped services, otherwise expand running
            if (stoppedCount > 0) {
                document.getElementById('stoppedServices').classList.add('show');
                document.getElementById('runningServices').classList.remove('show');
                document.querySelector('[data-bs-target="#stoppedServices"]').classList.remove('collapsed');
                document.querySelector('[data-bs-target="#runningServices"]').classList.add('collapsed');
            } else {
                document.getElementById('stoppedServices').classList.remove('show');
                document.getElementById('runningServices').classList.add('show');
                document.querySelector('[data-bs-target="#stoppedServices"]').classList.add('collapsed');
                document.querySelector('[data-bs-target="#runningServices"]').classList.remove('collapsed');
            }
        })
        .catch(err => {
            console.error('Failed to load services:', err);
        });
}

function serviceAction(name, action) {
    fetch('/api/v1/services/' + encodeURIComponent(name) + '/' + action, { method: 'POST' })
        .then(() => loadStatusData())
        .catch(err => console.error('Service action failed:', err));
}

function startAll() {
    fetch('/api/v1/workflows/_start_all/run', { method: 'POST' })
        .then(() => setTimeout(loadStatusData, 500))
        .catch(err => console.error('Start all failed:', err));
}

function stopAll() {
    fetch('/api/v1/workflows/_stop_all/run', { method: 'POST' })
        .then(() => setTimeout(loadStatusData, 500))
        .catch(err => console.error('Stop all failed:', err));
}

function refreshStatus() {
    loadStatusData();
}

// Load data on page load
loadStatusData();

// Auto-refresh every 5 seconds
setInterval(loadStatusData, 5000);
</script>

`)
//line views/status.qtpl:191
	p.StreamFooter(qw422016)
//line views/status.qtpl:191
	qw422016.N().S(`
`)
//line views/status.qtpl:192
}

//line views/status.qtpl:192
func (p *StatusPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/status.qtpl:192
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/status.qtpl:192
	p.StreamRender(qw422016)
//line views/status.qtpl:192
	qt422016.ReleaseWriter(qw422016)
//line views/status.qtpl:192
}

//line views/status.qtpl:192
func (p *StatusPage) Render() string {
//line views/status.qtpl:192
	qb422016 := qt422016.AcquireByteBuffer()
//line views/status.qtpl:192
	p.WriteRender(qb422016)
//line views/status.qtpl:192
	qs422016 := string(qb422016.B)
//line views/status.qtpl:192
	qt422016.ReleaseByteBuffer(qb422016)
//line views/status.qtpl:192
	return qs422016
//line views/status.qtpl:192
}
