// Code generated by qtc from "trace.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/trace.qtpl:4
package views

//line views/trace.qtpl:4
import "github.com/wingedpig/trellis/internal/trace"

//line views/trace.qtpl:5
import "time"

//line views/trace.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/trace.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/trace.qtpl:8
type TracePage struct {
	BasePage
	Groups  []trace.TraceGroup
	Reports []trace.ReportSummary
}

//line views/trace.qtpl:15
func (p *TracePage) StreamRender(qw422016 *qt422016.Writer) {
//line views/trace.qtpl:15
	qw422016.N().S(`
`)
//line views/trace.qtpl:16
	p.StreamHeader(qw422016)
//line views/trace.qtpl:16
	qw422016.N().S(`

<h2 class="mb-4"><i class="fa-solid fa-magnifying-glass-location"></i> Distributed Trace</h2>

<!-- Start New Trace -->
<div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-plus"></i> Start New Trace</span>
        `)
//line views/trace.qtpl:24
	if len(p.Groups) > 0 {
//line views/trace.qtpl:24
		qw422016.N().S(`
        <button class="btn btn-sm btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#traceGroups">
            <i class="fa-solid fa-layer-group"></i> Groups
        </button>
        `)
//line views/trace.qtpl:28
	}
//line views/trace.qtpl:28
	qw422016.N().S(`
    </div>
    <div class="card-body">
        <form id="traceForm" onsubmit="return executeTrace(event)">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="traceId" class="form-label">Trace ID:</label>
                    <input type="text" class="form-control" id="traceId" name="trace_id"
                           placeholder="e.g., req-abc123, correlation-xyz"
                           required>
                    <div class="form-text">The pattern to search for in log messages (grep pattern)</div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="traceGroup" class="form-label">Trace Group:</label>
                    <div class="position-relative">
                        <select class="form-select" id="traceGroup" name="group" required style="padding-right: 2.5rem;">
                            `)
//line views/trace.qtpl:44
	if len(p.Groups) == 0 {
//line views/trace.qtpl:44
		qw422016.N().S(`
                            <option value="" disabled selected>No trace groups configured</option>
                            `)
//line views/trace.qtpl:46
	} else {
//line views/trace.qtpl:46
		qw422016.N().S(`
                            <option value="" disabled selected>Select a trace group...</option>
                            `)
//line views/trace.qtpl:48
		for _, g := range p.Groups {
//line views/trace.qtpl:48
			qw422016.N().S(`
                            <option value="`)
//line views/trace.qtpl:49
			qw422016.E().S(g.Name)
//line views/trace.qtpl:49
			qw422016.N().S(`">`)
//line views/trace.qtpl:49
			qw422016.E().S(g.Name)
//line views/trace.qtpl:49
			qw422016.N().S(` (`)
//line views/trace.qtpl:49
			qw422016.N().D(len(g.LogViewers))
//line views/trace.qtpl:49
			qw422016.N().S(` log viewers)</option>
                            `)
//line views/trace.qtpl:50
		}
//line views/trace.qtpl:50
		qw422016.N().S(`
                            `)
//line views/trace.qtpl:51
	}
//line views/trace.qtpl:51
	qw422016.N().S(`
                        </select>
                        <i class="fa-solid fa-caret-down position-absolute" style="right: 12px; top: 50%; transform: translateY(-50%); pointer-events: none; color: #6c757d;"></i>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 mb-3">
                    <label class="form-label">Time Mode:</label>
                    <div class="btn-group w-100" role="group">
                        <input type="radio" class="btn-check" name="timeMode" id="timeModeRange" value="range" checked onchange="toggleTimeMode()">
                        <label class="btn btn-outline-secondary btn-sm" for="timeModeRange">Range</label>
                        <input type="radio" class="btn-check" name="timeMode" id="timeModeDay" value="day" onchange="toggleTimeMode()">
                        <label class="btn btn-outline-secondary btn-sm" for="timeModeDay">Day</label>
                    </div>
                </div>
                <div class="col-md-2 mb-3" id="startTimeGroup">
                    <label for="startTime" class="form-label">Start Time:</label>
                    <input type="text" class="form-control" id="startTime" name="start"
                           placeholder="1h, 6:00am"
                           value="1h">
                </div>
                <div class="col-md-2 mb-3" id="endTimeGroup">
                    <label for="endTime" class="form-label">End Time:</label>
                    <input type="text" class="form-control" id="endTime" name="end"
                           placeholder="now, 7:00am"
                           value="now">
                </div>
                <div class="col-md-2 mb-3" id="specificDayGroup" style="display: none;">
                    <label for="specificDay" class="form-label">Date:</label>
                    <input type="date" class="form-control" id="specificDay" name="specific_day">
                </div>
                <div class="col-md-3 mb-3">
                    <label for="reportName" class="form-label">Report Name (optional):</label>
                    <input type="text" class="form-control" id="reportName" name="name"
                           placeholder="Auto-generated if empty">
                </div>
                <div class="col-md-3 mb-3 d-flex align-items-end">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="expandByID" checked>
                        <label class="form-check-label" for="expandByID">Expand by ID</label>
                    </div>
                </div>
                <div class="col-md-2 mb-3 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary w-100" id="submitBtn" `)
//line views/trace.qtpl:95
	if len(p.Groups) == 0 {
//line views/trace.qtpl:95
		qw422016.N().S(`disabled`)
//line views/trace.qtpl:95
	}
//line views/trace.qtpl:95
	qw422016.N().S(`>
                        <i class="fa-solid fa-magnifying-glass"></i> Execute
                    </button>
                </div>
            </div>
        </form>

        `)
//line views/trace.qtpl:102
	if len(p.Groups) > 0 {
//line views/trace.qtpl:102
		qw422016.N().S(`
        <div class="collapse mt-3" id="traceGroups">
            <div class="card card-body bg-dark">
                <strong class="mb-2">Configured Trace Groups:</strong>
                `)
//line views/trace.qtpl:106
		for _, g := range p.Groups {
//line views/trace.qtpl:106
			qw422016.N().S(`
                <div class="mb-2">
                    <span class="text-accent">`)
//line views/trace.qtpl:108
			qw422016.E().S(g.Name)
//line views/trace.qtpl:108
			qw422016.N().S(`</span>:
                    <span class="text-muted">
                        `)
//line views/trace.qtpl:110
			for i, lv := range g.LogViewers {
//line views/trace.qtpl:110
				qw422016.N().S(`
                        `)
//line views/trace.qtpl:111
				qw422016.E().S(lv)
//line views/trace.qtpl:111
				if i < len(g.LogViewers)-1 {
//line views/trace.qtpl:111
					qw422016.N().S(`, `)
//line views/trace.qtpl:111
				}
//line views/trace.qtpl:111
				qw422016.N().S(`
                        `)
//line views/trace.qtpl:112
			}
//line views/trace.qtpl:112
			qw422016.N().S(`
                    </span>
                </div>
                `)
//line views/trace.qtpl:115
		}
//line views/trace.qtpl:115
		qw422016.N().S(`
            </div>
        </div>
        `)
//line views/trace.qtpl:118
	}
//line views/trace.qtpl:118
	qw422016.N().S(`
    </div>
</div>

<!-- Trace Reports -->
<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-file-lines"></i> Trace Reports</span>
        <button class="btn btn-sm btn-outline-secondary" onclick="refreshReports()">
            <i class="fa-solid fa-refresh"></i>
        </button>
    </div>
    <div class="card-body p-0">
        `)
//line views/trace.qtpl:131
	if len(p.Reports) == 0 {
//line views/trace.qtpl:131
		qw422016.N().S(`
        <div class="p-3 text-muted">
            <i class="fa-solid fa-info-circle"></i> No trace reports yet. Execute a trace to create one.
        </div>
        `)
//line views/trace.qtpl:135
	} else {
//line views/trace.qtpl:135
		qw422016.N().S(`
        <div class="table-responsive">
            <table class="table table-dark table-hover mb-0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Trace ID</th>
                        <th>Group</th>
                        <th>Time Range</th>
                        <th>Status</th>
                        <th>Entries</th>
                        <th>Created</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="reportsTable">
                    `)
//line views/trace.qtpl:151
		for _, r := range p.Reports {
//line views/trace.qtpl:151
			qw422016.N().S(`
                    <tr data-report="`)
//line views/trace.qtpl:152
			qw422016.E().S(r.Name)
//line views/trace.qtpl:152
			qw422016.N().S(`" data-status="`)
//line views/trace.qtpl:152
			qw422016.E().S(r.Status)
//line views/trace.qtpl:152
			qw422016.N().S(`">
                        <td>
                            `)
//line views/trace.qtpl:154
			if r.Status == "completed" {
//line views/trace.qtpl:154
				qw422016.N().S(`
                            <a href="/trace/report/`)
//line views/trace.qtpl:155
				qw422016.E().S(r.Name)
//line views/trace.qtpl:155
				qw422016.N().S(`">`)
//line views/trace.qtpl:155
				qw422016.E().S(r.Name)
//line views/trace.qtpl:155
				qw422016.N().S(`</a>
                            `)
//line views/trace.qtpl:156
			} else {
//line views/trace.qtpl:156
				qw422016.N().S(`
                            `)
//line views/trace.qtpl:157
				qw422016.E().S(r.Name)
//line views/trace.qtpl:157
				qw422016.N().S(`
                            `)
//line views/trace.qtpl:158
			}
//line views/trace.qtpl:158
			qw422016.N().S(`
                        </td>
                        <td><code class="small">`)
//line views/trace.qtpl:160
			qw422016.E().S(r.TraceID)
//line views/trace.qtpl:160
			qw422016.N().S(`</code></td>
                        <td>`)
//line views/trace.qtpl:161
			qw422016.E().S(r.Group)
//line views/trace.qtpl:161
			qw422016.N().S(`</td>
                        <td class="small text-muted time-range"
                            data-start="`)
//line views/trace.qtpl:163
			qw422016.E().S(r.TimeStart.Format(time.RFC3339))
//line views/trace.qtpl:163
			qw422016.N().S(`"
                            data-end="`)
//line views/trace.qtpl:164
			qw422016.E().S(r.TimeEnd.Format(time.RFC3339))
//line views/trace.qtpl:164
			qw422016.N().S(`">
                        </td>
                        <td>
                            `)
//line views/trace.qtpl:167
			if r.Status == "running" {
//line views/trace.qtpl:167
				qw422016.N().S(`
                            <span class="badge bg-primary"><i class="fa-solid fa-sync fa-spin"></i> Running</span>
                            `)
//line views/trace.qtpl:169
			} else if r.Status == "completed" {
//line views/trace.qtpl:169
				qw422016.N().S(`
                            <span class="badge bg-success">Completed</span>
                            `)
//line views/trace.qtpl:171
			} else if r.Status == "failed" {
//line views/trace.qtpl:171
				qw422016.N().S(`
                            <span class="badge bg-danger">Failed</span>
                            `)
//line views/trace.qtpl:173
			} else {
//line views/trace.qtpl:173
				qw422016.N().S(`
                            <span class="badge bg-secondary">`)
//line views/trace.qtpl:174
				qw422016.E().S(r.Status)
//line views/trace.qtpl:174
				qw422016.N().S(`</span>
                            `)
//line views/trace.qtpl:175
			}
//line views/trace.qtpl:175
			qw422016.N().S(`
                        </td>
                        <td>`)
//line views/trace.qtpl:177
			qw422016.N().D(r.EntryCount)
//line views/trace.qtpl:177
			qw422016.N().S(`</td>
                        <td class="small text-muted created-time" data-time="`)
//line views/trace.qtpl:178
			qw422016.E().S(r.CreatedAt.Format(time.RFC3339))
//line views/trace.qtpl:178
			qw422016.N().S(`">
                        </td>
                        <td>
                            <button class="btn btn-sm btn-outline-danger" onclick="deleteReport('`)
//line views/trace.qtpl:181
			qw422016.E().S(JSAttr(r.Name))
//line views/trace.qtpl:181
			qw422016.N().S(`')">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                    `)
//line views/trace.qtpl:186
		}
//line views/trace.qtpl:186
		qw422016.N().S(`
                </tbody>
            </table>
        </div>
        `)
//line views/trace.qtpl:190
	}
//line views/trace.qtpl:190
	qw422016.N().S(`
    </div>
</div>

<script>
function toggleTimeMode() {
    var isRangeMode = document.getElementById('timeModeRange').checked;
    document.getElementById('startTimeGroup').style.display = isRangeMode ? '' : 'none';
    document.getElementById('endTimeGroup').style.display = isRangeMode ? '' : 'none';
    document.getElementById('specificDayGroup').style.display = isRangeMode ? 'none' : '';

    // Set default value for specific day to today
    if (!isRangeMode && !document.getElementById('specificDay').value) {
        var today = new Date().toISOString().split('T')[0];
        document.getElementById('specificDay').value = today;
    }
}

function executeTrace(event) {
    event.preventDefault();

    var traceId = document.getElementById('traceId').value.trim();
    var group = document.getElementById('traceGroup').value;
    var reportName = document.getElementById('reportName').value.trim();
    var expandByID = document.getElementById('expandByID').checked;
    var isRangeMode = document.getElementById('timeModeRange').checked;

    if (!traceId || !group) {
        alert('Please enter a trace ID and select a trace group');
        return false;
    }

    // Disable submit button while request is in flight
    var submitBtn = document.getElementById('submitBtn');
    submitBtn.disabled = true;
    submitBtn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Starting...';

    // Build request body
    var body = {
        id: traceId,
        group: group,
        expand_by_id: expandByID
    };
    if (reportName) {
        body.name = reportName;
    }

    // Parse times based on mode
    if (isRangeMode) {
        var startTime = document.getElementById('startTime').value.trim();
        var endTime = document.getElementById('endTime').value.trim();
        if (startTime) {
            body.start = parseTimeInput(startTime, false);
        }
        if (endTime) {
            if (endTime === 'now') {
                body.end = new Date().toISOString();
            } else {
                body.end = parseTimeInput(endTime, true);
            }
        }
    } else {
        // Specific day mode - set start to 00:00:00 and end to 23:59:59
        var specificDay = document.getElementById('specificDay').value;
        if (specificDay) {
            var startDate = new Date(specificDay + 'T00:00:00');
            var endDate = new Date(specificDay + 'T23:59:59.999');
            body.start = startDate.toISOString();
            body.end = endDate.toISOString();
        }
    }

    fetch('/api/v1/trace', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
    })
    .then(function(r) { return r.json(); })
    .then(function(data) {
        if (data.error) {
            alert('Error: ' + data.error.message);
            submitBtn.disabled = false;
            submitBtn.innerHTML = '<i class="fa-solid fa-magnifying-glass"></i> Execute';
        } else {
            // Reload page to show the new report in the table
            location.reload();
        }
    })
    .catch(function(err) {
        alert('Error: ' + err);
        submitBtn.disabled = false;
        submitBtn.innerHTML = '<i class="fa-solid fa-magnifying-glass"></i> Execute';
    });

    return false;
}

function parseTimeInput(input, isEndTime) {
    // Check for "today" or "yesterday"
    if (input.toLowerCase() === 'today') {
        var d = new Date();
        if (isEndTime) {
            d.setHours(23, 59, 59, 999);
        } else {
            d.setHours(0, 0, 0, 0);
        }
        return d.toISOString();
    }
    if (input.toLowerCase() === 'yesterday') {
        var d = new Date();
        d.setDate(d.getDate() - 1);
        if (isEndTime) {
            d.setHours(23, 59, 59, 999);
        } else {
            d.setHours(0, 0, 0, 0);
        }
        return d.toISOString();
    }

    // Check if it's a duration (e.g., "1h", "30m")
    var durationMatch = input.match(/^(\d+)(s|m|h|d)$/);
    if (durationMatch) {
        var value = parseInt(durationMatch[1]);
        var unit = durationMatch[2];
        var ms = 0;
        switch (unit) {
            case 's': ms = value * 1000; break;
            case 'm': ms = value * 60 * 1000; break;
            case 'h': ms = value * 60 * 60 * 1000; break;
            case 'd': ms = value * 24 * 60 * 60 * 1000; break;
        }
        return new Date(Date.now() - ms).toISOString();
    }

    // Check if it's a date with time (e.g., "2025-01-10 6:00am", "2025-01-10 14:30")
    var dateTimeMatch = input.match(/^(\d{4}-\d{2}-\d{2})\s+(\d{1,2}):(\d{2})(am|pm)?$/i);
    if (dateTimeMatch) {
        var datePart = dateTimeMatch[1];
        var hours = parseInt(dateTimeMatch[2]);
        var minutes = parseInt(dateTimeMatch[3]);
        var ampm = dateTimeMatch[4];
        if (ampm) {
            if (ampm.toLowerCase() === 'pm' && hours !== 12) hours += 12;
            if (ampm.toLowerCase() === 'am' && hours === 12) hours = 0;
        }
        var d = new Date(datePart + 'T00:00:00');
        d.setHours(hours, minutes, 0, 0);
        return d.toISOString();
    }

    // Check if it's just a date (e.g., "2025-01-10")
    var dateMatch = input.match(/^(\d{4}-\d{2}-\d{2})$/);
    if (dateMatch) {
        var d = new Date(dateMatch[1] + 'T00:00:00');
        if (isEndTime) {
            d.setHours(23, 59, 59, 999);
        } else {
            d.setHours(0, 0, 0, 0);
        }
        return d.toISOString();
    }

    // Check if it's a time (e.g., "6:00am", "14:30")
    var timeMatch = input.match(/^(\d{1,2}):(\d{2})(am|pm)?$/i);
    if (timeMatch) {
        var hours = parseInt(timeMatch[1]);
        var minutes = parseInt(timeMatch[2]);
        var ampm = timeMatch[3];
        if (ampm) {
            if (ampm.toLowerCase() === 'pm' && hours !== 12) hours += 12;
            if (ampm.toLowerCase() === 'am' && hours === 12) hours = 0;
        }
        var d = new Date();
        d.setHours(hours, minutes, 0, 0);
        return d.toISOString();
    }

    // Try parsing as ISO date
    return input;
}

function deleteReport(name) {
    if (!confirm('Delete trace report "' + name + '"?')) {
        return;
    }

    fetch('/api/v1/trace/reports/' + encodeURIComponent(name), { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                location.reload();
            }
        })
        .catch(function(err) {
            alert('Error: ' + err);
        });
}

function refreshReports() {
    location.reload();
}

// Format times in user's timezone
function formatTime(d) {
    return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function formatDateShort(d) {
    return d.toLocaleDateString([], { month: 'short', day: 'numeric' });
}

function formatDateTime(d) {
    return d.toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

function formatFullDateTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleString([], { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' });
}

function isSameDay(d1, d2) {
    return d1.getFullYear() === d2.getFullYear() &&
           d1.getMonth() === d2.getMonth() &&
           d1.getDate() === d2.getDate();
}

function isToday(d) {
    return isSameDay(d, new Date());
}

// Format a time range smartly:
// - If both today: "10:30 - 14:00"
// - If same day but not today: "Jan 10 10:30 - 14:00"
// - If different days: "Jan 10 10:30 - Jan 11 14:00"
function formatTimeRange(startISO, endISO) {
    var start = new Date(startISO);
    var end = new Date(endISO);

    if (isSameDay(start, end)) {
        if (isToday(start)) {
            // Both today: just show times
            return formatTime(start) + ' - ' + formatTime(end);
        } else {
            // Same day, not today: show date once + both times
            return formatDateShort(start) + ' ' + formatTime(start) + ' - ' + formatTime(end);
        }
    } else {
        // Different days: show full date+time for both
        return formatDateTime(start) + ' - ' + formatDateTime(end);
    }
}

// Initialize time displays
(function() {
    // Format time ranges
    document.querySelectorAll('.time-range').forEach(function(el) {
        var start = el.dataset.start;
        var end = el.dataset.end;
        if (start && end) {
            el.textContent = formatTimeRange(start, end);
            el.title = formatFullDateTime(start) + ' - ' + formatFullDateTime(end);
        }
    });

    // Format created times
    document.querySelectorAll('.created-time').forEach(function(el) {
        var time = el.dataset.time;
        if (time) {
            el.textContent = formatDateTime(new Date(time));
            el.title = formatFullDateTime(time);
        }
    });
})();

// Auto-refresh if there are running reports
(function() {
    var runningReports = document.querySelectorAll('tr[data-status="running"]');
    if (runningReports.length > 0) {
        setTimeout(function() {
            location.reload();
        }, 3000);
    }
})();
</script>

`)
//line views/trace.qtpl:477
	p.StreamFooter(qw422016)
//line views/trace.qtpl:477
	qw422016.N().S(`
`)
//line views/trace.qtpl:478
}

//line views/trace.qtpl:478
func (p *TracePage) WriteRender(qq422016 qtio422016.Writer) {
//line views/trace.qtpl:478
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/trace.qtpl:478
	p.StreamRender(qw422016)
//line views/trace.qtpl:478
	qt422016.ReleaseWriter(qw422016)
//line views/trace.qtpl:478
}

//line views/trace.qtpl:478
func (p *TracePage) Render() string {
//line views/trace.qtpl:478
	qb422016 := qt422016.AcquireByteBuffer()
//line views/trace.qtpl:478
	p.WriteRender(qb422016)
//line views/trace.qtpl:478
	qs422016 := string(qb422016.B)
//line views/trace.qtpl:478
	qt422016.ReleaseByteBuffer(qb422016)
//line views/trace.qtpl:478
	return qs422016
//line views/trace.qtpl:478
}
