// Code generated by qtc from "trace_report.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/trace_report.qtpl:4
package views

//line views/trace_report.qtpl:4
import "github.com/wingedpig/trellis/internal/trace"

//line views/trace_report.qtpl:5
import "encoding/json"

//line views/trace_report.qtpl:6
import "time"

//line views/trace_report.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/trace_report.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/trace_report.qtpl:9
type TraceReportPage struct {
	BasePage
	Report     *trace.TraceReport
	LogViewers []LogViewerInfo
}

func (p *TraceReportPage) EntriesJSON() string {
	data, _ := json.Marshal(p.Report.Entries)
	return string(data)
}

func (p *TraceReportPage) LogViewersJSON() string {
	data, _ := json.Marshal(p.LogViewers)
	return string(data)
}

//line views/trace_report.qtpl:26
func (p *TraceReportPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/trace_report.qtpl:26
	qw422016.N().S(`
`)
//line views/trace_report.qtpl:27
	p.StreamHeader(qw422016)
//line views/trace_report.qtpl:27
	qw422016.N().S(`
<!-- Uses shared CSS from /static/css/logviewer.css -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/trace">Distributed Trace</a></li>
        <li class="breadcrumb-item active" aria-current="page">`)
//line views/trace_report.qtpl:33
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:33
	qw422016.N().S(`</li>
    </ol>
</nav>

<h2 class="mb-4">
    <i class="fa-solid fa-file-lines"></i> `)
//line views/trace_report.qtpl:38
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:38
	qw422016.N().S(`
</h2>

<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-info-circle"></i> Summary
    </div>
    <div class="card-body">
        <table class="table table-sm mb-0">
            <tr>
                <th>Trace ID</th>
                <td><code>`)
//line views/trace_report.qtpl:49
	qw422016.E().S(p.Report.TraceID)
//line views/trace_report.qtpl:49
	qw422016.N().S(`</code></td>
            </tr>
            <tr>
                <th>Group</th>
                <td>`)
//line views/trace_report.qtpl:53
	qw422016.E().S(p.Report.Group)
//line views/trace_report.qtpl:53
	qw422016.N().S(`</td>
            </tr>
            <tr>
                <th>Created</th>
                <td class="created-time" data-time="`)
//line views/trace_report.qtpl:57
	qw422016.E().S(p.Report.CreatedAt.Format(time.RFC3339))
//line views/trace_report.qtpl:57
	qw422016.N().S(`"></td>
            </tr>
            <tr>
                <th>Time Range</th>
                <td class="time-range"
                    data-start="`)
//line views/trace_report.qtpl:62
	qw422016.E().S(p.Report.TimeRange.Start.Format(time.RFC3339))
//line views/trace_report.qtpl:62
	qw422016.N().S(`"
                    data-end="`)
//line views/trace_report.qtpl:63
	qw422016.E().S(p.Report.TimeRange.End.Format(time.RFC3339))
//line views/trace_report.qtpl:63
	qw422016.N().S(`"></td>
            </tr>
            <tr>
                <th>Total Entries</th>
                <td>`)
//line views/trace_report.qtpl:67
	qw422016.N().D(p.Report.Summary.TotalEntries)
//line views/trace_report.qtpl:67
	qw422016.N().S(`</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>`)
//line views/trace_report.qtpl:71
	qw422016.N().D(int(p.Report.Summary.DurationMS))
//line views/trace_report.qtpl:71
	qw422016.N().S(`ms</td>
            </tr>
        </table>
    </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-3">
    <a href="/trace" class="btn btn-secondary">
        <i class="fa-solid fa-arrow-left"></i> Back to Traces
    </a>
    <div>
        <button class="btn btn-outline-primary me-2" onclick="showSaveToCase()">
            <i class="fa-solid fa-briefcase"></i> Save to Case
        </button>
        <button class="btn btn-outline-danger" onclick="deleteAndGoBack()">
            <i class="fa-solid fa-trash"></i> Delete Report
        </button>
    </div>
</div>

<!-- Log Entries -->
<div class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-list"></i> Log Entries (`)
//line views/trace_report.qtpl:94
	qw422016.N().D(len(p.Report.Entries))
//line views/trace_report.qtpl:94
	qw422016.N().S(`)</span>
    </div>
    <div class="card-body p-0">
        `)
//line views/trace_report.qtpl:97
	if len(p.Report.Entries) == 0 {
//line views/trace_report.qtpl:97
		qw422016.N().S(`
        <div class="alert alert-info m-3">
            <i class="fa-solid fa-info-circle"></i> No log entries found for this trace.
        </div>
        `)
//line views/trace_report.qtpl:101
	} else {
//line views/trace_report.qtpl:101
		qw422016.N().S(`
        <div class="trace-filter-bar">
            <i class="fa-solid fa-search text-muted"></i>
            <input type="text" id="filterInput" placeholder="Filter: source:api level:error message text..."
                   onkeyup="filterEntries(event)">
            <button class="btn btn-sm btn-outline-secondary" onclick="clearFilter()" title="Clear filter">
                <i class="fa-solid fa-times"></i>
            </button>
            <button id="timestampToggleBtn" class="btn btn-sm btn-outline-secondary" onclick="toggleTimestampFormat()" title="Switch to relative timestamps">
                Relative
            </button>
        </div>
        <div class="trace-wrapper">
            <div class="trace-log" id="traceLog"></div>
            <div class="trace-expanded" id="traceExpanded" style="display: none;">
                <div class="trace-expanded-header">
                    <span>Entry Details</span>
                    <button onclick="closeExpanded()"><i class="fa-solid fa-times"></i></button>
                </div>
                <div class="trace-expanded-content" id="traceExpandedContent"></div>
            </div>
        </div>
        `)
//line views/trace_report.qtpl:123
	}
//line views/trace_report.qtpl:123
	qw422016.N().S(`
    </div>
</div>

<script>
// Uses shared functions from /static/js/logviewer.js
var allEntries = `)
//line views/trace_report.qtpl:129
	qw422016.N().S(p.EntriesJSON())
//line views/trace_report.qtpl:129
	qw422016.N().S(`;
var logViewers = `)
//line views/trace_report.qtpl:130
	qw422016.N().S(p.LogViewersJSON())
//line views/trace_report.qtpl:130
	qw422016.N().S(`;
var filteredEntries = [];
var selectedEntry = null;
var traceTimestampAbsolute = true;

// Build a map of source name -> log viewer config
var logViewerMap = {};
for (var i = 0; i < logViewers.length; i++) {
    logViewerMap[logViewers[i].name] = logViewers[i];
}

function renderTraceEntry(entry, index) {
    var viewerConfig = logViewerMap[entry.source];
    var layout = (viewerConfig && viewerConfig.layout && viewerConfig.layout.length > 0)
        ? viewerConfig.layout
        : [{field: 'timestamp', timestamp: true}, {field: 'level'}, {field: 'message'}];

    renderLogEntry(entry, {
        container: document.getElementById('traceLog'),
        layout: layout,
        fieldMap: buildFieldMap(viewerConfig),
        formatTs: function(ts) { return formatTimestamp(ts, traceTimestampAbsolute); },
        onExpand: expandTraceEntry,
        entryIndex: index,
        rowClass: 'trace-entry',
        prependColumns: [{
            name: 'source',
            width: '100px',
            getValue: function(e) { return e.source || ''; }
        }]
    });
}

function renderEntries() {
    var container = document.getElementById('traceLog');
    container.innerHTML = '';
    for (var i = 0; i < filteredEntries.length; i++) {
        renderTraceEntry(filteredEntries[i], i);
    }
}

function filterEntries(event) {
    if (event && event.key === 'Escape') {
        clearFilter();
        return;
    }
    var query = document.getElementById('filterInput').value;
    filteredEntries = allEntries.filter(function(e) { return matchesLogFilter(e, query); });
    renderEntries();
}

function clearFilter() {
    document.getElementById('filterInput').value = '';
    filteredEntries = allEntries.slice();
    renderEntries();
}

function expandTraceEntry(entry) {
    selectedEntry = entry;
    var viewerConfig = logViewerMap[entry.source];
    expandEntry(entry, {
        expandedEl: document.getElementById('traceExpanded'),
        contentEl: document.getElementById('traceExpandedContent'),
        fieldNames: getFieldNames(viewerConfig),
        tbodySelector: '#traceLog',
        filteredEntries: filteredEntries,
        onSelect: function(e) { selectedEntry = e; }
    });
}

function closeExpanded() {
    document.getElementById('traceExpanded').style.display = 'none';
    document.querySelectorAll('.trace-entry.selected').forEach(function(el) {
        el.classList.remove('selected');
    });
    selectedEntry = null;
}

function toggleTimestampFormat() {
    traceTimestampAbsolute = !traceTimestampAbsolute;
    renderEntries();
    var btn = document.getElementById('timestampToggleBtn');
    if (btn) {
        btn.textContent = traceTimestampAbsolute ? 'Relative' : 'Absolute';
        btn.title = traceTimestampAbsolute ? 'Switch to relative timestamps' : 'Switch to absolute timestamps';
    }
}

function deleteAndGoBack() {
    if (!confirm('Delete this trace report?')) return;
    fetch('/api/v1/trace/reports/`)
//line views/trace_report.qtpl:220
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:220
	qw422016.N().S(`', { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                window.location.href = '/trace';
            }
        })
        .catch(function(err) { alert('Error: ' + err); });
}

function formatLocalTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function formatLocalDateTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

// Format a time range smartly:
// - Same day: "Jan 15, 10:30 - 14:45"
// - Different days: "Jan 15, 10:30 - Jan 16, 14:45"
function formatTimeRange(startISO, endISO) {
    var start = new Date(startISO);
    var end = new Date(endISO);

    var startDate = start.toLocaleDateString([], { month: 'short', day: 'numeric' });
    var endDate = end.toLocaleDateString([], { month: 'short', day: 'numeric' });
    var startTime = start.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    var endTime = end.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    if (startDate === endDate) {
        // Same day: show date once
        return startDate + ', ' + startTime + ' - ' + endTime;
    } else {
        // Different days: show both dates
        return startDate + ', ' + startTime + ' - ' + endDate + ', ' + endTime;
    }
}

// Initialize
(function() {
    document.querySelectorAll('.time-range').forEach(function(el) {
        var start = el.dataset.start;
        var end = el.dataset.end;
        if (start && end) {
            el.textContent = formatTimeRange(start, end);
        }
    });
    document.querySelectorAll('.created-time').forEach(function(el) {
        var time = el.dataset.time;
        if (time) {
            el.textContent = formatLocalDateTime(time);
        }
    });

    filteredEntries = allEntries.slice();
    renderEntries();

    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && selectedEntry) {
            closeExpanded();
        }
    });
})();
</script>

<!-- Save to Case Modal -->
<div class="modal fade" id="saveToCaseModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-briefcase"></i> Save Trace to Case</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="traceCaseWorktree" class="form-label">Worktree</label>
                    <select class="form-select" id="traceCaseWorktree" onchange="onTraceCaseWorktreeChange()"></select>
                </div>
                <div class="mb-3">
                    <label for="traceCaseSelect" class="form-label">Case</label>
                    <select class="form-select" id="traceCaseSelect" onchange="onTraceCaseSelectChange()" disabled></select>
                </div>
                <div id="traceCaseNewFields" style="display:none;">
                    <div class="mb-3">
                        <label for="traceCaseNewTitle" class="form-label">New Case Title</label>
                        <input type="text" class="form-control" id="traceCaseNewTitle" placeholder="Bug investigation">
                    </div>
                    <div class="mb-3">
                        <label for="traceCaseNewKind" class="form-label">Kind</label>
                        <select class="form-select" id="traceCaseNewKind">
                            <option value="task">Task</option>
                            <option value="bug">Bug</option>
                            <option value="feature">Feature</option>
                            <option value="investigation" selected>Investigation</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="saveToCaseConfirm()">Save</button>
            </div>
        </div>
    </div>
</div>

<script>
var TRACE_REPORT_NAME = '`)
//line views/trace_report.qtpl:332
	qw422016.E().S(JSAttr(p.Report.Name))
//line views/trace_report.qtpl:332
	qw422016.N().S(`';

function showSaveToCase() {
    fetch('/api/v1/nav/options')
    .then(function(r) { return r.json(); })
    .then(function(data) {
        var opts = data.data || data;
        var wts = opts.worktrees || [];
        var select = document.getElementById('traceCaseWorktree');
        select.innerHTML = '<option value="">-- Select a worktree --</option>';
        for (var i = 0; i < wts.length; i++) {
            var opt = document.createElement('option');
            opt.value = wts[i].name;
            opt.textContent = wts[i].name;
            select.appendChild(opt);
        }
        document.getElementById('traceCaseSelect').innerHTML = '';
        document.getElementById('traceCaseSelect').disabled = true;
        document.getElementById('traceCaseNewFields').style.display = 'none';
        var modal = new bootstrap.Modal(document.getElementById('saveToCaseModal'));
        modal.show();
    })
    .catch(function(err) { alert('Failed to load worktrees: ' + err); });
}

function onTraceCaseWorktreeChange() {
    var wt = document.getElementById('traceCaseWorktree').value;
    var select = document.getElementById('traceCaseSelect');
    if (!wt) {
        select.innerHTML = '';
        select.disabled = true;
        return;
    }
    fetch('/api/v1/cases/' + encodeURIComponent(wt))
    .then(function(r) { return r.json(); })
    .then(function(data) {
        var cases = data.data || data || [];
        select.innerHTML = '<option value="">-- Select a case --</option>';
        for (var i = 0; i < cases.length; i++) {
            var opt = document.createElement('option');
            opt.value = cases[i].id;
            opt.textContent = '[' + cases[i].kind + '] ' + cases[i].title;
            select.appendChild(opt);
        }
        select.innerHTML += '<option value="__new__">+ Create new case...</option>';
        select.disabled = false;
        document.getElementById('traceCaseNewFields').style.display = 'none';
    })
    .catch(function(err) { alert('Failed to load cases: ' + err); });
}

function onTraceCaseSelectChange() {
    var val = document.getElementById('traceCaseSelect').value;
    document.getElementById('traceCaseNewFields').style.display = (val === '__new__') ? 'block' : 'none';
}

function saveToCaseConfirm() {
    var wt = document.getElementById('traceCaseWorktree').value;
    var selectVal = document.getElementById('traceCaseSelect').value;
    if (!wt) { alert('Please select a worktree'); return; }

    if (selectVal === '__new__') {
        var newTitle = document.getElementById('traceCaseNewTitle').value.trim();
        var newKind = document.getElementById('traceCaseNewKind').value;
        if (!newTitle) { alert('Title is required'); return; }
        fetch('/api/v1/cases/' + encodeURIComponent(wt), {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({title: newTitle, kind: newKind})
        })
        .then(function(r) {
            if (!r.ok) return r.json().then(function(d) { throw new Error(d.error && d.error.message || 'Create failed'); });
            return r.json();
        })
        .then(function(data) {
            var c = data.data || data;
            return doLinkTrace(wt, c.id);
        })
        .catch(function(err) { alert('Failed: ' + err); });
    } else if (selectVal) {
        doLinkTrace(wt, selectVal);
    } else {
        alert('Please select a case');
    }
}

function doLinkTrace(worktree, caseId) {
    return fetch('/api/v1/cases/' + encodeURIComponent(worktree) + '/' + encodeURIComponent(caseId) + '/trace', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({
            report_name: TRACE_REPORT_NAME
        })
    })
    .then(function(r) {
        if (!r.ok) return r.json().then(function(d) { throw new Error(d.error && d.error.message || 'Link failed'); });
        return r.json();
    })
    .then(function() {
        bootstrap.Modal.getInstance(document.getElementById('saveToCaseModal')).hide();
        alert('Trace report saved to case.');
    })
    .catch(function(err) { alert('Save failed: ' + err); });
}
</script>

`)
//line views/trace_report.qtpl:438
	p.StreamFooter(qw422016)
//line views/trace_report.qtpl:438
	qw422016.N().S(`
`)
//line views/trace_report.qtpl:439
}

//line views/trace_report.qtpl:439
func (p *TraceReportPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/trace_report.qtpl:439
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/trace_report.qtpl:439
	p.StreamRender(qw422016)
//line views/trace_report.qtpl:439
	qt422016.ReleaseWriter(qw422016)
//line views/trace_report.qtpl:439
}

//line views/trace_report.qtpl:439
func (p *TraceReportPage) Render() string {
//line views/trace_report.qtpl:439
	qb422016 := qt422016.AcquireByteBuffer()
//line views/trace_report.qtpl:439
	p.WriteRender(qb422016)
//line views/trace_report.qtpl:439
	qs422016 := string(qb422016.B)
//line views/trace_report.qtpl:439
	qt422016.ReleaseByteBuffer(qb422016)
//line views/trace_report.qtpl:439
	return qs422016
//line views/trace_report.qtpl:439
}

//line views/trace_report.qtpl:442
func levelBadgeClass(level string) string {
	switch level {
	case "ERROR", "error", "ERR":
		return "bg-danger"
	case "WARN", "warn", "WARNING", "warning":
		return "bg-warning text-dark"
	case "INFO", "info":
		return "bg-info text-dark"
	case "DEBUG", "debug":
		return "bg-secondary"
	default:
		return "bg-light text-dark"
	}
}
