// Code generated by qtc from "trace_report.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/trace_report.qtpl:4
package views

//line views/trace_report.qtpl:4
import "github.com/wingedpig/trellis/internal/trace"

//line views/trace_report.qtpl:5
import "encoding/json"

//line views/trace_report.qtpl:6
import "time"

//line views/trace_report.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/trace_report.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/trace_report.qtpl:9
type TraceReportPage struct {
	BasePage
	Report     *trace.TraceReport
	LogViewers []LogViewerInfo
}

func (p *TraceReportPage) EntriesJSON() string {
	data, _ := json.Marshal(p.Report.Entries)
	return string(data)
}

func (p *TraceReportPage) LogViewersJSON() string {
	data, _ := json.Marshal(p.LogViewers)
	return string(data)
}

//line views/trace_report.qtpl:26
func (p *TraceReportPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/trace_report.qtpl:26
	qw422016.N().S(`
`)
//line views/trace_report.qtpl:27
	p.StreamHeader(qw422016)
//line views/trace_report.qtpl:27
	qw422016.N().S(`
<!-- Uses shared CSS from /static/css/logviewer.css -->

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/trace">Distributed Trace</a></li>
        <li class="breadcrumb-item active" aria-current="page">`)
//line views/trace_report.qtpl:33
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:33
	qw422016.N().S(`</li>
    </ol>
</nav>

<h2 class="mb-4">
    <i class="fa-solid fa-file-lines"></i> `)
//line views/trace_report.qtpl:38
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:38
	qw422016.N().S(`
</h2>

<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-info-circle"></i> Summary
    </div>
    <div class="card-body">
        <table class="table table-sm mb-0">
            <tr>
                <th>Trace ID</th>
                <td><code>`)
//line views/trace_report.qtpl:49
	qw422016.E().S(p.Report.TraceID)
//line views/trace_report.qtpl:49
	qw422016.N().S(`</code></td>
            </tr>
            <tr>
                <th>Group</th>
                <td>`)
//line views/trace_report.qtpl:53
	qw422016.E().S(p.Report.Group)
//line views/trace_report.qtpl:53
	qw422016.N().S(`</td>
            </tr>
            <tr>
                <th>Created</th>
                <td class="created-time" data-time="`)
//line views/trace_report.qtpl:57
	qw422016.E().S(p.Report.CreatedAt.Format(time.RFC3339))
//line views/trace_report.qtpl:57
	qw422016.N().S(`"></td>
            </tr>
            <tr>
                <th>Time Range</th>
                <td class="time-range"
                    data-start="`)
//line views/trace_report.qtpl:62
	qw422016.E().S(p.Report.TimeRange.Start.Format(time.RFC3339))
//line views/trace_report.qtpl:62
	qw422016.N().S(`"
                    data-end="`)
//line views/trace_report.qtpl:63
	qw422016.E().S(p.Report.TimeRange.End.Format(time.RFC3339))
//line views/trace_report.qtpl:63
	qw422016.N().S(`"></td>
            </tr>
            <tr>
                <th>Total Entries</th>
                <td>`)
//line views/trace_report.qtpl:67
	qw422016.N().D(p.Report.Summary.TotalEntries)
//line views/trace_report.qtpl:67
	qw422016.N().S(`</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>`)
//line views/trace_report.qtpl:71
	qw422016.N().D(int(p.Report.Summary.DurationMS))
//line views/trace_report.qtpl:71
	qw422016.N().S(`ms</td>
            </tr>
        </table>
    </div>
</div>

<!-- Log Entries -->
<div class="card mb-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <span><i class="fa-solid fa-list"></i> Log Entries (`)
//line views/trace_report.qtpl:80
	qw422016.N().D(len(p.Report.Entries))
//line views/trace_report.qtpl:80
	qw422016.N().S(`)</span>
    </div>
    <div class="card-body p-0">
        `)
//line views/trace_report.qtpl:83
	if len(p.Report.Entries) == 0 {
//line views/trace_report.qtpl:83
		qw422016.N().S(`
        <div class="alert alert-info m-3">
            <i class="fa-solid fa-info-circle"></i> No log entries found for this trace.
        </div>
        `)
//line views/trace_report.qtpl:87
	} else {
//line views/trace_report.qtpl:87
		qw422016.N().S(`
        <div class="trace-filter-bar">
            <i class="fa-solid fa-search text-muted"></i>
            <input type="text" id="filterInput" placeholder="Filter: source:api level:error message text..."
                   onkeyup="filterEntries(event)">
            <button class="btn btn-sm btn-outline-secondary" onclick="clearFilter()" title="Clear filter">
                <i class="fa-solid fa-times"></i>
            </button>
            <button id="timestampToggleBtn" class="btn btn-sm btn-outline-secondary" onclick="toggleTimestampFormat()" title="Switch to relative timestamps">
                Relative
            </button>
        </div>
        <div class="trace-wrapper">
            <div class="trace-log" id="traceLog"></div>
            <div class="trace-expanded" id="traceExpanded" style="display: none;">
                <div class="trace-expanded-header">
                    <span>Entry Details</span>
                    <button onclick="closeExpanded()"><i class="fa-solid fa-times"></i></button>
                </div>
                <div class="trace-expanded-content" id="traceExpandedContent"></div>
            </div>
        </div>
        `)
//line views/trace_report.qtpl:109
	}
//line views/trace_report.qtpl:109
	qw422016.N().S(`
    </div>
</div>

<div class="mt-3">
    <a href="/trace" class="btn btn-secondary">
        <i class="fa-solid fa-arrow-left"></i> Back to Traces
    </a>
    <button class="btn btn-outline-danger float-end" onclick="deleteAndGoBack()">
        <i class="fa-solid fa-trash"></i> Delete Report
    </button>
</div>

<script>
// Uses shared functions from /static/js/logviewer.js
var allEntries = `)
//line views/trace_report.qtpl:124
	qw422016.N().S(p.EntriesJSON())
//line views/trace_report.qtpl:124
	qw422016.N().S(`;
var logViewers = `)
//line views/trace_report.qtpl:125
	qw422016.N().S(p.LogViewersJSON())
//line views/trace_report.qtpl:125
	qw422016.N().S(`;
var filteredEntries = [];
var selectedEntry = null;
var traceTimestampAbsolute = true;

// Build a map of source name -> log viewer config
var logViewerMap = {};
for (var i = 0; i < logViewers.length; i++) {
    logViewerMap[logViewers[i].name] = logViewers[i];
}

function renderTraceEntry(entry, index) {
    var viewerConfig = logViewerMap[entry.source];
    var layout = (viewerConfig && viewerConfig.layout && viewerConfig.layout.length > 0)
        ? viewerConfig.layout
        : [{field: 'timestamp', timestamp: true}, {field: 'level'}, {field: 'message'}];

    renderLogEntry(entry, {
        container: document.getElementById('traceLog'),
        layout: layout,
        fieldMap: buildFieldMap(viewerConfig),
        formatTs: function(ts) { return formatTimestamp(ts, traceTimestampAbsolute); },
        onExpand: expandTraceEntry,
        entryIndex: index,
        rowClass: 'trace-entry',
        prependColumns: [{
            name: 'source',
            width: '100px',
            getValue: function(e) { return e.source || ''; }
        }]
    });
}

function renderEntries() {
    var container = document.getElementById('traceLog');
    container.innerHTML = '';
    for (var i = 0; i < filteredEntries.length; i++) {
        renderTraceEntry(filteredEntries[i], i);
    }
}

function filterEntries(event) {
    if (event && event.key === 'Escape') {
        clearFilter();
        return;
    }
    var query = document.getElementById('filterInput').value;
    filteredEntries = allEntries.filter(function(e) { return matchesLogFilter(e, query); });
    renderEntries();
}

function clearFilter() {
    document.getElementById('filterInput').value = '';
    filteredEntries = allEntries.slice();
    renderEntries();
}

function expandTraceEntry(entry) {
    selectedEntry = entry;
    var viewerConfig = logViewerMap[entry.source];
    expandEntry(entry, {
        expandedEl: document.getElementById('traceExpanded'),
        contentEl: document.getElementById('traceExpandedContent'),
        fieldNames: getFieldNames(viewerConfig),
        tbodySelector: '#traceLog',
        filteredEntries: filteredEntries,
        onSelect: function(e) { selectedEntry = e; }
    });
}

function closeExpanded() {
    document.getElementById('traceExpanded').style.display = 'none';
    document.querySelectorAll('.trace-entry.selected').forEach(function(el) {
        el.classList.remove('selected');
    });
    selectedEntry = null;
}

function toggleTimestampFormat() {
    traceTimestampAbsolute = !traceTimestampAbsolute;
    renderEntries();
    var btn = document.getElementById('timestampToggleBtn');
    if (btn) {
        btn.textContent = traceTimestampAbsolute ? 'Relative' : 'Absolute';
        btn.title = traceTimestampAbsolute ? 'Switch to relative timestamps' : 'Switch to absolute timestamps';
    }
}

function deleteAndGoBack() {
    if (!confirm('Delete this trace report?')) return;
    fetch('/api/v1/trace/reports/`)
//line views/trace_report.qtpl:215
	qw422016.E().S(p.Report.Name)
//line views/trace_report.qtpl:215
	qw422016.N().S(`', { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                alert('Error: ' + data.error.message);
            } else {
                window.location.href = '/trace';
            }
        })
        .catch(function(err) { alert('Error: ' + err); });
}

function formatLocalTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function formatLocalDateTime(isoString) {
    var d = new Date(isoString);
    return d.toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}

// Initialize
(function() {
    document.querySelectorAll('.time-range').forEach(function(el) {
        var start = el.dataset.start;
        var end = el.dataset.end;
        if (start && end) {
            el.textContent = formatLocalTime(start) + ' - ' + formatLocalTime(end);
        }
    });
    document.querySelectorAll('.created-time').forEach(function(el) {
        var time = el.dataset.time;
        if (time) {
            el.textContent = formatLocalDateTime(time);
        }
    });

    filteredEntries = allEntries.slice();
    renderEntries();

    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && selectedEntry) {
            closeExpanded();
        }
    });
})();
</script>

`)
//line views/trace_report.qtpl:264
	p.StreamFooter(qw422016)
//line views/trace_report.qtpl:264
	qw422016.N().S(`
`)
//line views/trace_report.qtpl:265
}

//line views/trace_report.qtpl:265
func (p *TraceReportPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/trace_report.qtpl:265
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/trace_report.qtpl:265
	p.StreamRender(qw422016)
//line views/trace_report.qtpl:265
	qt422016.ReleaseWriter(qw422016)
//line views/trace_report.qtpl:265
}

//line views/trace_report.qtpl:265
func (p *TraceReportPage) Render() string {
//line views/trace_report.qtpl:265
	qb422016 := qt422016.AcquireByteBuffer()
//line views/trace_report.qtpl:265
	p.WriteRender(qb422016)
//line views/trace_report.qtpl:265
	qs422016 := string(qb422016.B)
//line views/trace_report.qtpl:265
	qt422016.ReleaseByteBuffer(qb422016)
//line views/trace_report.qtpl:265
	return qs422016
//line views/trace_report.qtpl:265
}

//line views/trace_report.qtpl:268
func levelBadgeClass(level string) string {
	switch level {
	case "ERROR", "error", "ERR":
		return "bg-danger"
	case "WARN", "warn", "WARNING", "warning":
		return "bg-warning text-dark"
	case "INFO", "info":
		return "bg-info text-dark"
	case "DEBUG", "debug":
		return "bg-secondary"
	default:
		return "bg-light text-dark"
	}
}
