// Code generated by qtc from "worktree_home.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/worktree_home.qtpl:4
package views

//line views/worktree_home.qtpl:4
import "github.com/wingedpig/trellis/internal/cases"

//line views/worktree_home.qtpl:5
import "github.com/wingedpig/trellis/internal/claude"

//line views/worktree_home.qtpl:6
import "github.com/wingedpig/trellis/internal/terminal"

//line views/worktree_home.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/worktree_home.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/worktree_home.qtpl:9
type WorktreeHomePage struct {
	BasePage
	WorktreeName    string
	Branch          string
	Cases           []cases.CaseInfo
	ClaudeSessions  []*claude.SessionInfo
	Terminals       []terminal.WindowInfo
	TmuxSessionName string // Empty if no tmux session exists
}

//line views/worktree_home.qtpl:20
func (p *WorktreeHomePage) StreamRender(qw422016 *qt422016.Writer) {
//line views/worktree_home.qtpl:20
	qw422016.N().S(`
`)
//line views/worktree_home.qtpl:21
	p.StreamHeader(qw422016)
//line views/worktree_home.qtpl:21
	qw422016.N().S(`

<link href="/static/css/worktree_home.css" rel="stylesheet">
<link href="/static/css/cases.css" rel="stylesheet">

<div class="worktree-home">
    <div class="worktree-header mb-4">
        <h2><i class="fa-solid fa-folder-tree"></i> `)
//line views/worktree_home.qtpl:28
	qw422016.E().S(p.WorktreeName)
//line views/worktree_home.qtpl:28
	qw422016.N().S(`</h2>
        `)
//line views/worktree_home.qtpl:29
	if p.Branch != "" {
//line views/worktree_home.qtpl:29
		qw422016.N().S(`
        <span class="badge bg-secondary"><i class="fa-solid fa-code-branch"></i> `)
//line views/worktree_home.qtpl:30
		qw422016.E().S(p.Branch)
//line views/worktree_home.qtpl:30
		qw422016.N().S(`</span>
        `)
//line views/worktree_home.qtpl:31
	}
//line views/worktree_home.qtpl:31
	qw422016.N().S(`
    </div>

    <!-- Cases -->
    <div class="section mb-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4><i class="fa-solid fa-briefcase"></i> Cases</h4>
            <div>
                <button class="btn btn-outline-secondary btn-sm me-1" id="showArchivedBtn" onclick="toggleArchivedCases()">
                    <i class="fa-solid fa-box-archive"></i> Show Archived
                </button>
                <button class="btn btn-primary btn-sm" onclick="showNewCaseModal()">
                    <i class="fa-solid fa-plus"></i> New Case
                </button>
            </div>
        </div>

        `)
//line views/worktree_home.qtpl:48
	if len(p.Cases) == 0 {
//line views/worktree_home.qtpl:48
		qw422016.N().S(`
        <div class="empty-state" id="casesEmptyState">
            <p class="text-muted">No open cases. Create one to track a unit of work.</p>
        </div>
        `)
//line views/worktree_home.qtpl:52
	} else {
//line views/worktree_home.qtpl:52
		qw422016.N().S(`
        <div class="list-group" id="casesList">
            `)
//line views/worktree_home.qtpl:54
		for _, c := range p.Cases {
//line views/worktree_home.qtpl:54
			qw422016.N().S(`
            <div class="list-group-item case-list-item">
                <div class="case-info">
                    <a href="/case/`)
//line views/worktree_home.qtpl:57
			qw422016.E().S(p.WorktreeName)
//line views/worktree_home.qtpl:57
			qw422016.N().S(`/`)
//line views/worktree_home.qtpl:57
			qw422016.E().S(c.ID)
//line views/worktree_home.qtpl:57
			qw422016.N().S(`" class="text-decoration-none">
                        <span class="badge case-kind-`)
//line views/worktree_home.qtpl:58
			qw422016.E().S(c.Kind)
//line views/worktree_home.qtpl:58
			qw422016.N().S(` me-1">`)
//line views/worktree_home.qtpl:58
			qw422016.E().S(c.Kind)
//line views/worktree_home.qtpl:58
			qw422016.N().S(`</span>
                        `)
//line views/worktree_home.qtpl:59
			qw422016.E().S(c.Title)
//line views/worktree_home.qtpl:59
			qw422016.N().S(`
                    </a>
                    <span class="case-date">`)
//line views/worktree_home.qtpl:61
			qw422016.E().S(c.CreatedAt.Format("2006-01-02"))
//line views/worktree_home.qtpl:61
			qw422016.N().S(`</span>
                </div>
                <button class="btn btn-outline-warning btn-sm" onclick="archiveCaseFromList('`)
//line views/worktree_home.qtpl:63
			qw422016.E().S(JSAttr(c.ID))
//line views/worktree_home.qtpl:63
			qw422016.N().S(`')">
                    <i class="fa-solid fa-box-archive"></i>
                </button>
            </div>
            `)
//line views/worktree_home.qtpl:67
		}
//line views/worktree_home.qtpl:67
		qw422016.N().S(`
        </div>
        `)
//line views/worktree_home.qtpl:69
	}
//line views/worktree_home.qtpl:69
	qw422016.N().S(`

        <div id="archivedCasesContainer" style="display:none;" class="mt-3">
            <h6 class="text-muted">Archived</h6>
            <div id="archivedCasesList" class="list-group"></div>
        </div>
    </div>

    <!-- Claude Sessions -->
    <div class="section mb-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4><i class="fa-solid fa-robot"></i> Claude Sessions</h4>
            <div>
                <button class="btn btn-outline-secondary btn-sm me-1" id="showTrashBtn" onclick="toggleTrashedSessions()">
                    <i class="fa-solid fa-trash-can"></i> Show Trash
                </button>
                <button class="btn btn-outline-secondary btn-sm me-1" onclick="showImportTranscriptModal()">
                    <i class="fa-solid fa-file-import"></i> Import Transcript
                </button>
                <button class="btn btn-primary btn-sm" onclick="showNewClaudeModal()">
                    <i class="fa-solid fa-plus"></i> New Session
                </button>
            </div>
        </div>

        `)
//line views/worktree_home.qtpl:94
	if len(p.ClaudeSessions) == 0 {
//line views/worktree_home.qtpl:94
		qw422016.N().S(`
        <div class="empty-state">
            <p class="text-muted">No Claude sessions yet. Create one to get started.</p>
        </div>
        `)
//line views/worktree_home.qtpl:98
	} else {
//line views/worktree_home.qtpl:98
		qw422016.N().S(`
        <div class="list-group">
            `)
//line views/worktree_home.qtpl:100
		for _, sess := range p.ClaudeSessions {
//line views/worktree_home.qtpl:100
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <a href="/claude/`)
//line views/worktree_home.qtpl:102
			qw422016.E().S(p.WorktreeName)
//line views/worktree_home.qtpl:102
			qw422016.N().S(`/`)
//line views/worktree_home.qtpl:102
			qw422016.E().S(sess.ID)
//line views/worktree_home.qtpl:102
			qw422016.N().S(`" class="text-decoration-none flex-grow-1 d-flex align-items-center">
                    <i class="fa-solid fa-message"></i>
                    <span class="ms-1">`)
//line views/worktree_home.qtpl:104
			qw422016.E().S(sess.DisplayName)
//line views/worktree_home.qtpl:104
			qw422016.N().S(`</span>
                    `)
//line views/worktree_home.qtpl:105
			if !sess.LastUserInput.IsZero() {
//line views/worktree_home.qtpl:105
				qw422016.N().S(`
                    <span class="text-muted ms-2 small">`)
//line views/worktree_home.qtpl:106
				qw422016.E().S(FormatRelativeTime(sess.LastUserInput))
//line views/worktree_home.qtpl:106
				qw422016.N().S(`</span>
                    `)
//line views/worktree_home.qtpl:107
			}
//line views/worktree_home.qtpl:107
			qw422016.N().S(`
                </a>
                <button class="btn btn-outline-secondary btn-sm me-1" onclick="renameClaudeSession('`)
//line views/worktree_home.qtpl:109
			qw422016.E().S(JSAttr(sess.ID))
//line views/worktree_home.qtpl:109
			qw422016.N().S(`', '`)
//line views/worktree_home.qtpl:109
			qw422016.E().S(JSAttr(sess.DisplayName))
//line views/worktree_home.qtpl:109
			qw422016.N().S(`')">
                    <i class="fa-solid fa-pencil"></i>
                </button>
                <button class="btn btn-outline-secondary btn-sm me-1" title="Move to new worktree" onclick="showMoveSessionModal('`)
//line views/worktree_home.qtpl:112
			qw422016.E().S(JSAttr(sess.ID))
//line views/worktree_home.qtpl:112
			qw422016.N().S(`', '`)
//line views/worktree_home.qtpl:112
			qw422016.E().S(JSAttr(sess.DisplayName))
//line views/worktree_home.qtpl:112
			qw422016.N().S(`')">
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                </button>
                <button class="btn btn-outline-danger btn-sm" onclick="deleteClaudeSession('`)
//line views/worktree_home.qtpl:115
			qw422016.E().S(JSAttr(sess.ID))
//line views/worktree_home.qtpl:115
			qw422016.N().S(`')">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </div>
            `)
//line views/worktree_home.qtpl:119
		}
//line views/worktree_home.qtpl:119
		qw422016.N().S(`
        </div>
        `)
//line views/worktree_home.qtpl:121
	}
//line views/worktree_home.qtpl:121
	qw422016.N().S(`

        <div id="trashedSessionsContainer" style="display:none;" class="mt-3">
            <h6 class="text-muted">Trash</h6>
            <div id="trashedSessionsList" class="list-group"></div>
        </div>
    </div>

    <!-- Terminals -->
    <div class="section mb-4">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h4><i class="fa-solid fa-terminal"></i> Terminals</h4>
            <button class="btn btn-primary btn-sm" onclick="showNewTerminalModal()">
                <i class="fa-solid fa-plus"></i> New Terminal
            </button>
        </div>

        `)
//line views/worktree_home.qtpl:138
	if len(p.Terminals) == 0 {
//line views/worktree_home.qtpl:138
		qw422016.N().S(`
        <div class="empty-state">
            <p class="text-muted">No terminal windows. Create one to get started.</p>
        </div>
        `)
//line views/worktree_home.qtpl:142
	} else {
//line views/worktree_home.qtpl:142
		qw422016.N().S(`
        <div class="list-group">
            `)
//line views/worktree_home.qtpl:144
		for _, win := range p.Terminals {
//line views/worktree_home.qtpl:144
			qw422016.N().S(`
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <a href="/terminal/local/`)
//line views/worktree_home.qtpl:146
			qw422016.E().S(p.WorktreeName)
//line views/worktree_home.qtpl:146
			qw422016.N().S(`/`)
//line views/worktree_home.qtpl:146
			qw422016.E().S(win.Name)
//line views/worktree_home.qtpl:146
			qw422016.N().S(`" class="text-decoration-none flex-grow-1">
                    <i class="fa-solid fa-terminal"></i>
                    `)
//line views/worktree_home.qtpl:148
			qw422016.E().S(win.Name)
//line views/worktree_home.qtpl:148
			qw422016.N().S(`
                </a>
                <button class="btn btn-outline-secondary btn-sm me-1" onclick="renameTerminal('`)
//line views/worktree_home.qtpl:150
			qw422016.E().S(JSAttr(win.Name))
//line views/worktree_home.qtpl:150
			qw422016.N().S(`')">
                    <i class="fa-solid fa-pencil"></i>
                </button>
                <button class="btn btn-outline-danger btn-sm" onclick="deleteTerminal('`)
//line views/worktree_home.qtpl:153
			qw422016.E().S(JSAttr(win.Name))
//line views/worktree_home.qtpl:153
			qw422016.N().S(`')">
                    <i class="fa-solid fa-trash"></i>
                </button>
            </div>
            `)
//line views/worktree_home.qtpl:157
		}
//line views/worktree_home.qtpl:157
		qw422016.N().S(`
        </div>
        `)
//line views/worktree_home.qtpl:159
	}
//line views/worktree_home.qtpl:159
	qw422016.N().S(`
    </div>

</div>

<!-- New Claude Session Modal -->
<div class="modal fade" id="newClaudeModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-robot"></i> New Claude Session</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="claudeSessionName" class="form-label">Name</label>
                    <input type="text" class="form-control" id="claudeSessionName" placeholder="Session 1" autofocus>
                    <div class="form-text">Leave blank for auto-naming (Session 1, Session 2, ...)</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="createClaudeSession()">Create</button>
            </div>
        </div>
    </div>
</div>

<!-- New Terminal Modal -->
<div class="modal fade" id="newTerminalModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-terminal"></i> New Terminal</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="terminalName" class="form-label">Name</label>
                    <input type="text" class="form-control" id="terminalName" placeholder="shell" autofocus>
                    <div class="form-text">Leave blank for auto-naming (shell, shell-2, ...)</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="createTerminal()">Create</button>
            </div>
        </div>
    </div>
</div>

<!-- Rename Modal -->
<div class="modal fade" id="renameModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="renameModalTitle">Rename</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <input type="text" class="form-control" id="renameInput">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="renameConfirmBtn">Rename</button>
            </div>
        </div>
    </div>
</div>

<!-- Import Transcript Modal -->
<div class="modal fade" id="importTranscriptModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-file-import"></i> Import Claude Transcript</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="transcriptFile" class="form-label">Transcript file (.json)</label>
                    <input type="file" class="form-control" id="transcriptFile" accept=".json">
                    <div class="form-text">Select a trellis.transcript.v1 JSON file exported from another session.</div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="importTranscript()">Import</button>
            </div>
        </div>
    </div>
</div>

<!-- Move Claude Session Modal -->
<div class="modal fade" id="moveSessionModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-arrow-right-from-bracket"></i> Move Session to New Worktree</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p class="text-muted small mb-2" id="moveSessionSubtitle"></p>
                <div class="mb-3">
                    <label for="moveSessionBranch" class="form-label">New branch name</label>
                    <input type="text" class="form-control" id="moveSessionBranch" placeholder="feature/my-branch">
                    <div class="form-text">A fresh git worktree will be created for this branch.</div>
                </div>
                <div class="mb-2">
                    <label class="form-label mb-1">Files to move (from source worktree)</label>
                    <div id="moveSessionFilesStatus" class="text-muted small">Loading…</div>
                    <div id="moveSessionFilesList" class="border rounded p-2" style="max-height: 250px; overflow-y: auto;"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="moveSessionConfirmBtn">Move</button>
            </div>
        </div>
    </div>
</div>

<!-- New Case Modal -->
<div class="modal fade" id="newCaseModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa-solid fa-briefcase"></i> New Case</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label for="caseTitle" class="form-label">Title</label>
                    <input type="text" class="form-control" id="caseTitle" placeholder="Investigate login timeout" autofocus>
                </div>
                <div class="mb-3">
                    <label for="caseKind" class="form-label">Kind</label>
                    <select class="form-select" id="caseKind">
                        <option value="task">Task</option>
                        <option value="bug">Bug</option>
                        <option value="feature">Feature</option>
                        <option value="investigation">Investigation</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="createCase()">Create</button>
            </div>
        </div>
    </div>
</div>

<script>
const WORKTREE_NAME = '`)
//line views/worktree_home.qtpl:313
	qw422016.E().S(JSAttr(p.WorktreeName))
//line views/worktree_home.qtpl:313
	qw422016.N().S(`';

let newTerminalModal, newClaudeModal, newCaseModal, renameModal, importTranscriptModal, moveSessionModal;
let renameConfirmCallback = null;
let moveSessionState = { sessionId: null };
document.addEventListener('DOMContentLoaded', function() {
    importTranscriptModal = new bootstrap.Modal(document.getElementById('importTranscriptModal'));
    moveSessionModal = new bootstrap.Modal(document.getElementById('moveSessionModal'));
    document.getElementById('moveSessionConfirmBtn').addEventListener('click', submitMoveSession);
    document.getElementById('moveSessionModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('moveSessionBranch').focus();
    });

    newCaseModal = new bootstrap.Modal(document.getElementById('newCaseModal'));
    document.getElementById('newCaseModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('caseTitle').focus();
    });
    document.getElementById('caseTitle').addEventListener('keydown', function(e) {
        if (e.key === 'Enter') { e.preventDefault(); createCase(); }
    });
    newClaudeModal = new bootstrap.Modal(document.getElementById('newClaudeModal'));
    document.getElementById('newClaudeModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('claudeSessionName').focus();
    });
    document.getElementById('claudeSessionName').addEventListener('keydown', function(e) {
        if (e.key === 'Enter') { e.preventDefault(); createClaudeSession(); }
    });

    newTerminalModal = new bootstrap.Modal(document.getElementById('newTerminalModal'));
    document.getElementById('newTerminalModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('terminalName').focus();
    });
    document.getElementById('terminalName').addEventListener('keydown', function(e) {
        if (e.key === 'Enter') { e.preventDefault(); createTerminal(); }
    });

    renameModal = new bootstrap.Modal(document.getElementById('renameModal'));
    document.getElementById('renameModal').addEventListener('shown.bs.modal', function() {
        const input = document.getElementById('renameInput');
        input.focus();
        input.select();
    });
    document.getElementById('renameInput').addEventListener('keydown', function(e) {
        if (e.key === 'Enter') { e.preventDefault(); document.getElementById('renameConfirmBtn').click(); }
    });
    document.getElementById('renameConfirmBtn').addEventListener('click', function() {
        if (renameConfirmCallback) renameConfirmCallback();
    });
});

function showNewClaudeModal() {
    document.getElementById('claudeSessionName').value = '';
    newClaudeModal.show();
}

function showNewTerminalModal() {
    document.getElementById('terminalName').value = '';
    newTerminalModal.show();
}

function createClaudeSession() {
    const name = document.getElementById('claudeSessionName').value.trim();
    const body = name ? JSON.stringify({display_name: name}) : '{}';
    fetch('/api/v1/claude/' + encodeURIComponent(WORKTREE_NAME) + '/sessions', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: body
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Create failed'); });
        return r.json();
    })
    .then(data => {
        const sess = data.data || data;
        TrellisNav.pushToHistory(window.location.pathname);
        window.location.href = '/claude/' + encodeURIComponent(WORKTREE_NAME) + '/' + sess.id;
    })
    .catch(err => alert('Failed to create session: ' + err));
}

function deleteClaudeSession(sessionId) {
    fetch('/api/v1/claude/sessions/' + sessionId, { method: 'DELETE' })
    .then(() => window.location.reload())
    .catch(err => alert('Failed to trash session: ' + err));
}

let trashedVisible = false;
function toggleTrashedSessions() {
    const container = document.getElementById('trashedSessionsContainer');
    const btn = document.getElementById('showTrashBtn');
    if (trashedVisible) {
        container.style.display = 'none';
        btn.innerHTML = '<i class="fa-solid fa-trash-can"></i> Show Trash';
        trashedVisible = false;
        return;
    }
    fetch('/api/v1/claude/' + encodeURIComponent(WORKTREE_NAME) + '/sessions/trash')
    .then(r => r.json())
    .then(data => {
        const sessions = data.data || data;
        const list = document.getElementById('trashedSessionsList');
        list.innerHTML = '';
        if (!sessions || sessions.length === 0) {
            list.innerHTML = '<p class="text-muted p-2">No trashed sessions.</p>';
        } else {
            sessions.forEach(s => {
                const item = document.createElement('div');
                item.className = 'list-group-item d-flex justify-content-between align-items-center';
                const name = document.createElement('span');
                name.className = 'flex-grow-1';
                name.innerHTML = '<i class="fa-solid fa-message"></i> <span class="ms-1">' + escapeHtml(s.display_name) + '</span>';
                item.appendChild(name);
                const restoreBtn = document.createElement('button');
                restoreBtn.className = 'btn btn-outline-success btn-sm me-1';
                restoreBtn.innerHTML = '<i class="fa-solid fa-trash-arrow-up"></i>';
                restoreBtn.onclick = function() { restoreClaudeSession(s.id); };
                item.appendChild(restoreBtn);
                const deleteBtn = document.createElement('button');
                deleteBtn.className = 'btn btn-outline-danger btn-sm';
                deleteBtn.innerHTML = '<i class="fa-solid fa-trash"></i>';
                deleteBtn.onclick = function() { permanentDeleteClaudeSession(s.id); };
                item.appendChild(deleteBtn);
                list.appendChild(item);
            });
        }
        container.style.display = 'block';
        btn.innerHTML = '<i class="fa-solid fa-trash-can"></i> Hide Trash';
        trashedVisible = true;
    })
    .catch(err => alert('Failed to load trashed sessions: ' + err));
}

function restoreClaudeSession(sessionId) {
    fetch('/api/v1/claude/sessions/' + sessionId + '/restore', { method: 'POST' })
    .then(() => window.location.reload())
    .catch(err => alert('Failed to restore session: ' + err));
}

function permanentDeleteClaudeSession(sessionId) {
    if (!confirm('Permanently delete this session? This cannot be undone.')) return;
    fetch('/api/v1/claude/sessions/' + sessionId + '/permanent', { method: 'DELETE' })
    .then(() => {
        if (trashedVisible) {
            toggleTrashedSessions();
            toggleTrashedSessions();
        }
    })
    .catch(err => alert('Failed to delete session: ' + err));
}

function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

function createTerminal() {
    const name = document.getElementById('terminalName').value.trim();
    const body = name ? JSON.stringify({name: name}) : '{}';
    fetch('/api/v1/terminal/' + encodeURIComponent(WORKTREE_NAME) + '/windows', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: body
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Create failed'); });
        return r.json();
    })
    .then(data => {
        const win = data.data || data;
        TrellisNav.pushToHistory(window.location.pathname);
        window.location.href = '/terminal/local/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(win.name);
    })
    .catch(err => alert('Failed to create terminal: ' + err));
}

function deleteTerminal(windowName) {
    if (!confirm('Delete terminal "' + windowName + '"?')) return;
    fetch('/api/v1/terminal/' + encodeURIComponent(WORKTREE_NAME) + '/windows/' + encodeURIComponent(windowName), {
        method: 'DELETE'
    })
    .then(() => window.location.reload())
    .catch(err => alert('Failed to delete terminal: ' + err));
}

function showMoveSessionModal(sessionId, sessionName) {
    moveSessionState.sessionId = sessionId;
    document.getElementById('moveSessionSubtitle').textContent = 'Moving "' + sessionName + '" from ' + WORKTREE_NAME;
    document.getElementById('moveSessionBranch').value = '';
    const listEl = document.getElementById('moveSessionFilesList');
    const statusEl = document.getElementById('moveSessionFilesStatus');
    listEl.innerHTML = '';
    statusEl.textContent = 'Loading…';
    statusEl.style.display = '';
    fetch('/api/v1/claude/' + encodeURIComponent(WORKTREE_NAME) + '/git-status')
    .then(r => r.json())
    .then(payload => {
        const data = payload.data || payload;
        const groups = [
            { label: 'Modified', files: data.modified || [] },
            { label: 'Added', files: data.added || [] },
            { label: 'Renamed', files: data.renamed || [] },
            { label: 'Untracked', files: data.untracked || [] }
        ];
        const total = groups.reduce((n, g) => n + g.files.length, 0);
        if (total === 0) {
            statusEl.textContent = 'No uncommitted files in the source worktree.';
            return;
        }
        statusEl.style.display = 'none';
        groups.forEach(g => {
            if (g.files.length === 0) return;
            const heading = document.createElement('div');
            heading.className = 'text-muted small mt-1';
            heading.textContent = g.label;
            listEl.appendChild(heading);
            g.files.forEach(f => {
                const id = 'move-file-' + Math.random().toString(36).slice(2);
                const row = document.createElement('div');
                row.className = 'form-check';
                const input = document.createElement('input');
                input.type = 'checkbox';
                input.className = 'form-check-input move-session-file';
                input.id = id;
                input.value = f;
                input.checked = true;
                const label = document.createElement('label');
                label.className = 'form-check-label';
                label.htmlFor = id;
                label.textContent = f;
                row.appendChild(input);
                row.appendChild(label);
                listEl.appendChild(row);
            });
        });
    })
    .catch(err => {
        statusEl.textContent = 'Failed to load git status: ' + err;
    });
    moveSessionModal.show();
}

function submitMoveSession() {
    const sessionId = moveSessionState.sessionId;
    if (!sessionId) return;
    const branch = document.getElementById('moveSessionBranch').value.trim();
    if (!branch) {
        alert('Enter a branch name.');
        return;
    }
    const files = Array.from(document.querySelectorAll('.move-session-file'))
        .filter(cb => cb.checked)
        .map(cb => cb.value);
    const btn = document.getElementById('moveSessionConfirmBtn');
    btn.disabled = true;
    fetch('/api/v1/claude/sessions/' + encodeURIComponent(sessionId) + '/move', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ branch: branch, files: files })
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Move failed'); });
        return r.json();
    })
    .then(payload => {
        const data = payload.data || payload;
        const errs = data.revert_errors || [];
        moveSessionModal.hide();
        if (errs.length > 0) {
            alert('Session moved, but some source files could not be reverted:\n' + errs.join('\n'));
        }
        const target = data.worktree;
        if (target) {
            window.location.href = '/worktree/' + encodeURIComponent(target);
        } else {
            window.location.reload();
        }
    })
    .catch(err => alert('Failed to move session: ' + err))
    .finally(() => { btn.disabled = false; });
}

function renameClaudeSession(sessionId, currentName) {
    document.getElementById('renameModalTitle').textContent = 'Rename Claude Session';
    document.getElementById('renameInput').value = currentName;
    renameConfirmCallback = function() {
        const newName = document.getElementById('renameInput').value.trim();
        if (!newName) return;
        fetch('/api/v1/claude/sessions/' + sessionId, {
            method: 'PATCH',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({display_name: newName})
        })
        .then(resp => {
            if (!resp.ok) throw new Error('rename failed');
            renameModal.hide();
            window.location.reload();
        })
        .catch(err => alert('Failed to rename session: ' + err));
    };
    renameModal.show();
}

function showImportTranscriptModal() {
    document.getElementById('transcriptFile').value = '';
    importTranscriptModal.show();
}

function importTranscript() {
    const fileInput = document.getElementById('transcriptFile');
    if (!fileInput.files.length) {
        alert('Please select a transcript file.');
        return;
    }
    const reader = new FileReader();
    reader.onload = function(e) {
        let transcript;
        try {
            transcript = JSON.parse(e.target.result);
        } catch (err) {
            alert('Invalid JSON file: ' + err);
            return;
        }
        fetch('/api/v1/claude/' + encodeURIComponent(WORKTREE_NAME) + '/sessions/import', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify(transcript)
        })
        .then(r => {
            if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Import failed'); });
            return r.json();
        })
        .then(data => {
            const sess = data.data || data;
            importTranscriptModal.hide();
            TrellisNav.pushToHistory(window.location.pathname);
            window.location.href = '/claude/' + encodeURIComponent(WORKTREE_NAME) + '/' + sess.id;
        })
        .catch(err => alert('Import failed: ' + err));
    };
    reader.readAsText(fileInput.files[0]);
}

function renameTerminal(currentName) {
    document.getElementById('renameModalTitle').textContent = 'Rename Terminal';
    document.getElementById('renameInput').value = currentName;
    renameConfirmCallback = function() {
        const newName = document.getElementById('renameInput').value.trim();
        if (!newName) return;
        fetch('/api/v1/terminal/' + encodeURIComponent(WORKTREE_NAME) + '/windows/' + encodeURIComponent(currentName), {
            method: 'PATCH',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({name: newName})
        })
        .then(resp => {
            if (!resp.ok) throw new Error('rename failed');
            renameModal.hide();
            window.location.reload();
        })
        .catch(err => alert('Failed to rename terminal: ' + err));
    };
    renameModal.show();
}

function showNewCaseModal() {
    document.getElementById('caseTitle').value = '';
    document.getElementById('caseKind').value = 'task';
    newCaseModal.show();
}

function createCase() {
    const title = document.getElementById('caseTitle').value.trim();
    if (!title) { alert('Title is required'); return; }
    const kind = document.getElementById('caseKind').value;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME), {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({title: title, kind: kind})
    })
    .then(r => {
        if (!r.ok) return r.json().then(d => { throw new Error(d.error?.message || 'Create failed'); });
        return r.json();
    })
    .then(data => {
        const c = data.data || data;
        newCaseModal.hide();
        window.location.href = '/case/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(c.id);
    })
    .catch(err => alert('Failed to create case: ' + err));
}

function archiveCaseFromList(caseId) {
    if (!confirm('Archive this case?')) return;
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(caseId) + '/archive', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Archive failed');
        window.location.reload();
    })
    .catch(err => alert('Archive failed: ' + err));
}

let archivedVisible = false;
function toggleArchivedCases() {
    const container = document.getElementById('archivedCasesContainer');
    const btn = document.getElementById('showArchivedBtn');
    if (archivedVisible) {
        container.style.display = 'none';
        btn.innerHTML = '<i class="fa-solid fa-box-archive"></i> Show Archived';
        archivedVisible = false;
        return;
    }
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/archived')
    .then(r => r.json())
    .then(data => {
        const cases = data.data || data;
        const list = document.getElementById('archivedCasesList');
        list.innerHTML = '';
        if (!cases || cases.length === 0) {
            list.innerHTML = '<p class="text-muted p-2">No archived cases.</p>';
        } else {
            cases.forEach(c => {
                const item = document.createElement('div');
                item.className = 'list-group-item case-list-item';
                item.innerHTML = '<div class="case-info">' +
                    '<a href="/case/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(c.id) + '" class="text-decoration-none">' +
                    '<span class="badge case-kind-' + c.kind + ' me-1">' + c.kind + '</span>' +
                    c.title + '</a>' +
                    '<span class="case-date">' + (c.created_at || '').substring(0, 10) + '</span></div>' +
                    '<button class="btn btn-outline-success btn-sm" onclick="reopenCaseFromList(\'' + c.id.replace(/'/g, "\\'") + '\')">' +
                    '<i class="fa-solid fa-box-open"></i></button>';
                list.appendChild(item);
            });
        }
        container.style.display = 'block';
        btn.innerHTML = '<i class="fa-solid fa-box-archive"></i> Hide Archived';
        archivedVisible = true;
    })
    .catch(err => alert('Failed to load archived cases: ' + err));
}

function reopenCaseFromList(caseId) {
    fetch('/api/v1/cases/' + encodeURIComponent(WORKTREE_NAME) + '/' + encodeURIComponent(caseId) + '/reopen', {
        method: 'POST'
    })
    .then(resp => {
        if (!resp.ok) throw new Error('Reopen failed');
        window.location.reload();
    })
    .catch(err => alert('Reopen failed: ' + err));
}

</script>
<script src="/static/js/workflow_picker.js"></script>

`)
//line views/worktree_home.qtpl:769
	p.StreamFooter(qw422016)
//line views/worktree_home.qtpl:769
	qw422016.N().S(`
`)
//line views/worktree_home.qtpl:770
}

//line views/worktree_home.qtpl:770
func (p *WorktreeHomePage) WriteRender(qq422016 qtio422016.Writer) {
//line views/worktree_home.qtpl:770
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/worktree_home.qtpl:770
	p.StreamRender(qw422016)
//line views/worktree_home.qtpl:770
	qt422016.ReleaseWriter(qw422016)
//line views/worktree_home.qtpl:770
}

//line views/worktree_home.qtpl:770
func (p *WorktreeHomePage) Render() string {
//line views/worktree_home.qtpl:770
	qb422016 := qt422016.AcquireByteBuffer()
//line views/worktree_home.qtpl:770
	p.WriteRender(qb422016)
//line views/worktree_home.qtpl:770
	qs422016 := string(qb422016.B)
//line views/worktree_home.qtpl:770
	qt422016.ReleaseByteBuffer(qb422016)
//line views/worktree_home.qtpl:770
	return qs422016
//line views/worktree_home.qtpl:770
}
