// Code generated by qtc from "worktrees.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Copyright © 2026 Groups.io, Inc.
// SPDX-License-Identifier: Apache-2.0
//

//line views/worktrees.qtpl:4
package views

//line views/worktrees.qtpl:4
import "github.com/wingedpig/trellis/internal/worktree"

//line views/worktrees.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/worktrees.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/worktrees.qtpl:7
type WorktreesPage struct {
	BasePage
	Worktrees   []worktree.WorktreeInfo
	Active      *worktree.WorktreeInfo
	ProjectName string
	BinariesDir string
	Version     string
}

//line views/worktrees.qtpl:17
func (p *WorktreesPage) StreamRender(qw422016 *qt422016.Writer) {
//line views/worktrees.qtpl:17
	qw422016.N().S(`
`)
//line views/worktrees.qtpl:18
	p.StreamHeader(qw422016)
//line views/worktrees.qtpl:18
	qw422016.N().S(`

<main>
<div class="hero">
    <div class="container">
        <img src="https://trellis.dev/images/logo.png" alt="Trellis" height="150" class="mb-3 hero-logo">
        <p class="lead">A web-based control plane for your development environment</p>
        <p class="text-muted">Rapidly switch between worktrees, terminals, locally running services, and local or remote logs using tmux, SSH, and keyboard-driven pickers—instead of a collection of disconnected tools.</p>
        `)
//line views/worktrees.qtpl:26
	if p.Version != "" {
//line views/worktrees.qtpl:26
		qw422016.N().S(`<p class="text-muted mb-2">v`)
//line views/worktrees.qtpl:26
		qw422016.E().S(p.Version)
//line views/worktrees.qtpl:26
		qw422016.N().S(`</p>`)
//line views/worktrees.qtpl:26
	}
//line views/worktrees.qtpl:26
	qw422016.N().S(`
        <div class="mt-4">
            <a href="https://trellis.dev/docs/" class="btn btn-primary btn-lg me-2"><i class="fa-solid fa-book"></i> Documentation</a>
            <a href="https://github.com/wingedpig/trellis" class="btn btn-outline-secondary btn-lg me-2" target="_blank"><i class="fa-brands fa-github"></i> GitHub</a>
            <a href="https://groups.io/g/trellis" class="btn btn-outline-secondary btn-lg" target="_blank"><i class="fa-solid fa-envelope"></i> Email Group</a>
        </div>
    </div>
</div>
</main>

<h5 class="mb-3"><i class="fa-solid fa-code-branch"></i> Worktrees</h5>

<p>Current worktree: <strong>`)
//line views/worktrees.qtpl:38
	if p.Active != nil {
//line views/worktrees.qtpl:38
		qw422016.E().S(p.Active.Name())
//line views/worktrees.qtpl:38
	} else {
//line views/worktrees.qtpl:38
		qw422016.N().S(`None`)
//line views/worktrees.qtpl:38
	}
//line views/worktrees.qtpl:38
	qw422016.N().S(`</strong></p>

<div class="list-group mb-4">
    `)
//line views/worktrees.qtpl:41
	for _, wt := range p.Worktrees {
//line views/worktrees.qtpl:41
		qw422016.N().S(`
    `)
//line views/worktrees.qtpl:42
		isActive := p.Active != nil && p.Active.Path == wt.Path

//line views/worktrees.qtpl:42
		qw422016.N().S(`
    `)
//line views/worktrees.qtpl:43
		isMain := wt.Name() == p.ProjectName

//line views/worktrees.qtpl:43
		qw422016.N().S(`
    <div class="list-group-item `)
//line views/worktrees.qtpl:44
		if isActive {
//line views/worktrees.qtpl:44
			qw422016.N().S(`active`)
//line views/worktrees.qtpl:44
		}
//line views/worktrees.qtpl:44
		qw422016.N().S(`" data-worktree-path="`)
//line views/worktrees.qtpl:44
		qw422016.E().S(wt.Path)
//line views/worktrees.qtpl:44
		qw422016.N().S(`">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                `)
//line views/worktrees.qtpl:47
		if isActive {
//line views/worktrees.qtpl:47
			qw422016.N().S(`
                <i class="fa-solid fa-check"></i>
                `)
//line views/worktrees.qtpl:49
		} else {
//line views/worktrees.qtpl:49
			qw422016.N().S(`
                <i class="fa-solid fa-code-branch"></i>
                `)
//line views/worktrees.qtpl:51
		}
//line views/worktrees.qtpl:51
		qw422016.N().S(`
                `)
//line views/worktrees.qtpl:52
		qw422016.E().S(wt.Name())
//line views/worktrees.qtpl:52
		qw422016.N().S(`
                `)
//line views/worktrees.qtpl:53
		if isActive {
//line views/worktrees.qtpl:53
			qw422016.N().S(` (current)`)
//line views/worktrees.qtpl:53
		}
//line views/worktrees.qtpl:53
		qw422016.N().S(`
                <span class="wt-status">
                `)
//line views/worktrees.qtpl:55
		if wt.Dirty {
//line views/worktrees.qtpl:55
			qw422016.N().S(`
                <span class="badge bg-danger ms-2" title="Uncommitted changes">
                    <i class="fa-solid fa-pencil"></i> dirty
                </span>
                `)
//line views/worktrees.qtpl:59
		}
//line views/worktrees.qtpl:59
		qw422016.N().S(`
                `)
//line views/worktrees.qtpl:60
		if wt.Ahead > 0 || wt.Behind > 0 {
//line views/worktrees.qtpl:60
			qw422016.N().S(`
                <span class="badge bg-info text-dark ms-2" title="Commits ahead/behind main">
                    `)
//line views/worktrees.qtpl:62
			if wt.Ahead > 0 {
//line views/worktrees.qtpl:62
				qw422016.N().S(`<i class="fa-solid fa-arrow-up"></i>`)
//line views/worktrees.qtpl:62
				qw422016.N().D(wt.Ahead)
//line views/worktrees.qtpl:62
			}
//line views/worktrees.qtpl:62
			qw422016.N().S(`
                    `)
//line views/worktrees.qtpl:63
			if wt.Behind > 0 {
//line views/worktrees.qtpl:63
				qw422016.N().S(`<i class="fa-solid fa-arrow-down"></i>`)
//line views/worktrees.qtpl:63
				qw422016.N().D(wt.Behind)
//line views/worktrees.qtpl:63
			}
//line views/worktrees.qtpl:63
			qw422016.N().S(`
                </span>
                `)
//line views/worktrees.qtpl:65
		}
//line views/worktrees.qtpl:65
		qw422016.N().S(`
                `)
//line views/worktrees.qtpl:66
		if wt.Detached {
//line views/worktrees.qtpl:66
			qw422016.N().S(`
                <span class="badge bg-secondary ms-2">Detached</span>
                `)
//line views/worktrees.qtpl:68
		}
//line views/worktrees.qtpl:68
		qw422016.N().S(`
                </span>
                <br>
                <small class="text-muted">Branch: `)
//line views/worktrees.qtpl:71
		qw422016.E().S(wt.Branch)
//line views/worktrees.qtpl:71
		qw422016.N().S(`</small>
            </div>
            <div>
                `)
//line views/worktrees.qtpl:74
		if !isActive {
//line views/worktrees.qtpl:74
			qw422016.N().S(`
                <a href="#" class="btn btn-sm btn-primary" onclick="promptSwitchWorktree('`)
//line views/worktrees.qtpl:75
			qw422016.E().S(JSAttr(wt.Name()))
//line views/worktrees.qtpl:75
			qw422016.N().S(`'); return false;">
                    <i class="fa-solid fa-sign-in-alt"></i> Switch
                </a>
                `)
//line views/worktrees.qtpl:78
			if !isMain {
//line views/worktrees.qtpl:78
				qw422016.N().S(`
                <button class="btn btn-sm btn-danger" onclick="showRemoveModal('`)
//line views/worktrees.qtpl:79
				qw422016.E().S(JSAttr(wt.Name()))
//line views/worktrees.qtpl:79
				qw422016.N().S(`', '`)
//line views/worktrees.qtpl:79
				qw422016.E().S(JSAttr(wt.Branch))
//line views/worktrees.qtpl:79
				qw422016.N().S(`')">
                    <i class="fa-solid fa-trash"></i> Remove
                </button>
                `)
//line views/worktrees.qtpl:82
			}
//line views/worktrees.qtpl:82
			qw422016.N().S(`
                `)
//line views/worktrees.qtpl:83
		} else {
//line views/worktrees.qtpl:83
			qw422016.N().S(`
                <span class="text-muted">Cannot remove current worktree</span>
                `)
//line views/worktrees.qtpl:85
		}
//line views/worktrees.qtpl:85
		qw422016.N().S(`
            </div>
        </div>
    </div>
    `)
//line views/worktrees.qtpl:89
	}
//line views/worktrees.qtpl:89
	qw422016.N().S(`
</div>

`)
//line views/worktrees.qtpl:92
	if len(p.Worktrees) == 0 {
//line views/worktrees.qtpl:92
		qw422016.N().S(`
<div class="alert alert-info">
    <i class="fa-solid fa-info-circle"></i> No git worktrees found.
</div>
`)
//line views/worktrees.qtpl:96
	}
//line views/worktrees.qtpl:96
	qw422016.N().S(`

<div class="card mb-4">
    <div class="card-header">
        <i class="fa-solid fa-plus"></i> Create New Worktree
    </div>
    <div class="card-body">
        <form id="createWorktreeForm" onsubmit="return validateAndConfirmCreate(event)">
            <div class="mb-3">
                <label for="branchName" class="form-label">Branch/Worktree Name:</label>
                <input type="text" class="form-control" id="branchName" name="branch_name"
                       placeholder="e.g., feature-x, bugfix-123, my-experiment"
                       pattern="[a-zA-Z0-9][a-zA-Z0-9-_]*"
                       title="Must start with letter or number, can contain letters, numbers, hyphens, and underscores"
                       required>
                <div class="form-text">
                    This will create:
                    <ul class="mb-0">
                        <li>New branch: <code><span id="branchPreview">feature-x</span></code></li>
                        <li>New worktree directory: <code>../<span id="dirPreview">`)
//line views/worktrees.qtpl:115
	qw422016.E().S(p.ProjectName)
//line views/worktrees.qtpl:115
	qw422016.N().S(`-feature-x</span></code></li>
                    </ul>
                </div>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="switchToWorktree" name="switch_to">
                <label class="form-check-label" for="switchToWorktree">
                    Switch to new worktree after creation
                </label>
            </div>
            <button type="submit" class="btn btn-primary">
                <i class="fa-solid fa-code-branch"></i> Create Worktree
            </button>
        </form>
    </div>
</div>

`)
//line views/worktrees.qtpl:132
	if p.BinariesDir != "" {
//line views/worktrees.qtpl:132
		qw422016.N().S(`
<div class="alert alert-info">
    <h6><i class="fa-solid fa-folder"></i> Binary Locations</h6>
    <p class="mb-0">Each worktree has its own binary directory. Current: <code>`)
//line views/worktrees.qtpl:135
		qw422016.E().S(p.BinariesDir)
//line views/worktrees.qtpl:135
		qw422016.N().S(`</code></p>
</div>
`)
//line views/worktrees.qtpl:137
	}
//line views/worktrees.qtpl:137
	qw422016.N().S(`

<!-- Generic Alert Modal -->
<div class="modal fade" id="alertModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="alertModalTitle">Alert</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p id="alertModalMessage"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="alertModalOk">OK</button>
            </div>
        </div>
    </div>
</div>

<!-- Generic Confirm Modal -->
<div class="modal fade" id="confirmModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmModalTitle">Confirm</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p id="confirmModalMessage" style="white-space: pre-wrap;"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="confirmModalYes">Yes</button>
            </div>
        </div>
    </div>
</div>

<!-- Activation Progress Modal -->
<div class="modal fade" id="activationModal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="fa-solid fa-sync fa-spin" id="activationSpinner"></i>
                    <span id="activationTitle">Switching Worktree...</span>
                </h5>
            </div>
            <div class="modal-body">
                <div id="activationProgress">
                    <p>Running pre-activation hooks...</p>
                </div>
                <div id="activationResults" style="display: none;">
                    <div class="alert" id="activationStatusAlert">
                        <strong id="activationStatus"></strong>
                        <span id="activationDuration" class="text-muted ms-2"></span>
                    </div>
                    <div id="hookResultsContainer"></div>
                </div>
            </div>
            <div class="modal-footer" id="activationFooter" style="display: none;">
                <button type="button" class="btn btn-primary" id="activationOkBtn">OK</button>
            </div>
        </div>
    </div>
</div>

<!-- Remove Worktree Modal -->
<div class="modal fade" id="removeWorktreeModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Remove Worktree</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove worktree <strong id="removeWorktreeName"></strong>?</p>
                <p>This will:</p>
                <ol>
                    <li>Remove the worktree directory</li>
                    <li>Remove binaries directory</li>
                    <li>Kill any tmux session for this worktree</li>
                </ol>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" id="deleteBranchCheckbox" checked>
                    <label class="form-check-label" for="deleteBranchCheckbox">
                        Also delete git branch <strong id="removeBranchName"></strong>
                    </label>
                </div>
                <div class="alert alert-warning">
                    <i class="fa-solid fa-triangle-exclamation"></i> <strong>Warning:</strong> This action cannot be undone!
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmRemoveBtn">
                    <i class="fa-solid fa-trash"></i> Remove Worktree
                </button>
            </div>
        </div>
    </div>
</div>

<script>
var currentRemoveWorktree = '';
var currentRemoveBranch = '';
var projectName = '`)
//line views/worktrees.qtpl:244
	qw422016.E().S(JSAttr(p.ProjectName))
//line views/worktrees.qtpl:244
	qw422016.N().S(`';
var pendingConfirmCallback = null;

// Show alert modal
function showAlert(message, title) {
    document.getElementById('alertModalTitle').textContent = title || 'Alert';
    document.getElementById('alertModalMessage').textContent = message;
    var modal = new bootstrap.Modal(document.getElementById('alertModal'));
    modal.show();
    // Focus the OK button when modal is shown
    document.getElementById('alertModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('alertModalOk').focus();
    }, { once: true });
}

// Show confirm modal and return promise
function showConfirm(message, title) {
    return new Promise(function(resolve) {
        document.getElementById('confirmModalTitle').textContent = title || 'Confirm';
        document.getElementById('confirmModalMessage').textContent = message;

        var modal = new bootstrap.Modal(document.getElementById('confirmModal'));
        var yesBtn = document.getElementById('confirmModalYes');
        var modalEl = document.getElementById('confirmModal');

        // Clean up old handlers
        var newYesBtn = yesBtn.cloneNode(true);
        yesBtn.parentNode.replaceChild(newYesBtn, yesBtn);

        newYesBtn.onclick = function() {
            modal.hide();
            resolve(true);
        };

        modalEl.addEventListener('hidden.bs.modal', function() {
            resolve(false);
        }, { once: true });

        modal.show();

        // Focus the Yes button when modal is shown
        modalEl.addEventListener('shown.bs.modal', function() {
            newYesBtn.focus();
        }, { once: true });
    });
}

function promptSwitchWorktree(name) {
    showConfirm('Switch to worktree "' + name + '"?\n\nThis will restart all services.', 'Switch Worktree')
        .then(function(confirmed) {
            if (confirmed) {
                switchWorktree(name);
            }
        });
}

function switchWorktree(name) {
    // Show progress modal
    var modal = new bootstrap.Modal(document.getElementById('activationModal'));
    document.getElementById('activationTitle').textContent = 'Switching to ' + name + '...';
    document.getElementById('activationProgress').style.display = 'block';
    document.getElementById('activationResults').style.display = 'none';
    document.getElementById('activationFooter').style.display = 'none';
    document.getElementById('activationSpinner').style.display = 'inline-block';
    modal.show();

    fetch('/api/v1/worktrees/' + encodeURIComponent(name) + '/activate', { method: 'POST' })
        .then(function(r) { return r.json(); })
        .then(function(resp) {
            // Hide progress, show results
            document.getElementById('activationProgress').style.display = 'none';
            document.getElementById('activationResults').style.display = 'block';
            document.getElementById('activationFooter').style.display = 'flex';
            document.getElementById('activationSpinner').style.display = 'none';

            // Unwrap API envelope: {data: {...}, error: {...}, meta: {...}}
            var isError = !!resp.error;
            var data = resp.data || {};
            var errorDetails = (resp.error && resp.error.details) || {};

            var statusAlert = document.getElementById('activationStatusAlert');
            statusAlert.className = 'alert ' + (isError ? 'alert-danger' : 'alert-success');

            if (isError) {
                document.getElementById('activationTitle').textContent = 'Activation Failed';
                document.getElementById('activationStatus').textContent = resp.error.message;
            } else {
                document.getElementById('activationTitle').textContent = 'Worktree Activated';
                document.getElementById('activationStatus').textContent = 'Successfully switched to ' + name;
            }

            var duration = data.duration || errorDetails.duration;
            if (duration) {
                document.getElementById('activationDuration').textContent = '(' + duration + ')';
            }

            // Display hook results
            var container = document.getElementById('hookResultsContainer');
            container.innerHTML = '';

            var hook_results = data.hook_results || errorDetails.hook_results;
            if (hook_results && hook_results.length > 0) {
                var heading = document.createElement('h6');
                heading.textContent = 'Hook Results:';
                container.appendChild(heading);

                hook_results.forEach(function(hook) {
                    var hookDiv = document.createElement('div');
                    hookDiv.className = 'card mb-2';
                    hookDiv.innerHTML = '<div class="card-header d-flex justify-content-between align-items-center py-2">' +
                        '<span>' + (hook.Success ? '<i class="fa-solid fa-check text-success"></i>' : '<i class="fa-solid fa-xmark text-danger"></i>') +
                        ' ' + hook.Name + '</span>' +
                        '<span class="text-muted small">' + hook.Duration + '</span>' +
                        '</div>';
                    if (hook.Output) {
                        var body = document.createElement('div');
                        body.className = 'card-body py-2';
                        var pre = document.createElement('pre');
                        pre.className = 'mb-0 small';
                        pre.style.maxHeight = '200px';
                        pre.style.overflow = 'auto';
                        pre.textContent = hook.Output;
                        body.appendChild(pre);
                        hookDiv.appendChild(body);
                    }
                    container.appendChild(hookDiv);
                });
            }

            // Set up OK button
            document.getElementById('activationOkBtn').onclick = function() {
                modal.hide();
                if (!isError) {
                    location.reload();
                }
            };
            document.getElementById('activationOkBtn').focus();
        })
        .catch(function(err) {
            document.getElementById('activationProgress').style.display = 'none';
            document.getElementById('activationResults').style.display = 'block';
            document.getElementById('activationFooter').style.display = 'flex';
            document.getElementById('activationSpinner').style.display = 'none';
            document.getElementById('activationTitle').textContent = 'Error';
            document.getElementById('activationStatusAlert').className = 'alert alert-danger';
            document.getElementById('activationStatus').textContent = 'Error: ' + err;
            document.getElementById('activationOkBtn').onclick = function() { modal.hide(); };
        });
}

function validateAndConfirmCreate(event) {
    event.preventDefault();

    var branchName = document.getElementById('branchName').value.trim();
    if (!branchName) {
        showAlert('Please enter a branch name', 'Validation Error');
        return false;
    }
    if (!/^[a-zA-Z0-9][a-zA-Z0-9-_]*$/.test(branchName)) {
        showAlert('Branch name must start with a letter or number and contain only letters, numbers, hyphens, and underscores', 'Validation Error');
        return false;
    }

    var switchTo = document.getElementById('switchToWorktree').checked;
    var message = 'Create new worktree with branch "' + branchName + '"?\n\nThis will create a new git branch and worktree directory.';
    if (switchTo) {
        message += '\n\nThe new worktree will be activated and services will restart.';
    }

    showConfirm(message, 'Create Worktree').then(function(confirmed) {
        if (confirmed) {
            createWorktree(branchName, switchTo);
        }
    });

    return false;
}

function createWorktree(branchName, switchTo) {
    var modal = new bootstrap.Modal(document.getElementById('activationModal'));
    document.getElementById('activationTitle').textContent = 'Creating worktree...';
    document.getElementById('activationProgress').innerHTML = '<p>Creating branch <strong>' + branchName + '</strong> and worktree directory...</p>';
    document.getElementById('activationProgress').style.display = 'block';
    document.getElementById('activationResults').style.display = 'none';
    document.getElementById('activationFooter').style.display = 'none';
    document.getElementById('activationSpinner').style.display = 'inline-block';
    modal.show();

    fetch('/api/v1/worktrees', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            branch_name: branchName,
            switch_to: switchTo
        })
    })
    .then(function(r) { return r.json(); })
    .then(function(data) {
        if (data.error) {
            document.getElementById('activationProgress').style.display = 'none';
            document.getElementById('activationResults').style.display = 'block';
            document.getElementById('activationFooter').style.display = 'flex';
            document.getElementById('activationSpinner').style.display = 'none';
            document.getElementById('activationTitle').textContent = 'Creation Failed';
            document.getElementById('activationStatusAlert').className = 'alert alert-danger';
            document.getElementById('activationStatus').textContent = data.error.message || data.error;
            document.getElementById('activationDuration').textContent = '';
            document.getElementById('hookResultsContainer').innerHTML = '';
            document.getElementById('activationOkBtn').onclick = function() { modal.hide(); };
            document.getElementById('activationOkBtn').focus();
        } else {
            modal.hide();
            location.reload();
        }
    })
    .catch(function(err) {
        document.getElementById('activationProgress').style.display = 'none';
        document.getElementById('activationResults').style.display = 'block';
        document.getElementById('activationFooter').style.display = 'flex';
        document.getElementById('activationSpinner').style.display = 'none';
        document.getElementById('activationTitle').textContent = 'Error';
        document.getElementById('activationStatusAlert').className = 'alert alert-danger';
        document.getElementById('activationStatus').textContent = 'Error: ' + err;
        document.getElementById('activationDuration').textContent = '';
        document.getElementById('hookResultsContainer').innerHTML = '';
        document.getElementById('activationOkBtn').onclick = function() { modal.hide(); };
    });
}

function showRemoveModal(worktreeName, branchName) {
    currentRemoveWorktree = worktreeName;
    currentRemoveBranch = branchName;
    document.getElementById('removeWorktreeName').textContent = worktreeName;
    document.getElementById('removeBranchName').textContent = branchName;
    var modal = new bootstrap.Modal(document.getElementById('removeWorktreeModal'));
    modal.show();
    // Focus the Remove button when modal is shown
    document.getElementById('removeWorktreeModal').addEventListener('shown.bs.modal', function() {
        document.getElementById('confirmRemoveBtn').focus();
    }, { once: true });
}

document.getElementById('confirmRemoveBtn').onclick = function() {
    var deleteBranch = document.getElementById('deleteBranchCheckbox').checked;
    var worktreeName = currentRemoveWorktree;
    var url = '/api/v1/worktrees/' + encodeURIComponent(worktreeName);
    if (deleteBranch) {
        url += '?delete_branch=1';
    }

    bootstrap.Modal.getInstance(document.getElementById('removeWorktreeModal')).hide();

    var modal = new bootstrap.Modal(document.getElementById('activationModal'));
    document.getElementById('activationTitle').textContent = 'Removing worktree...';
    document.getElementById('activationProgress').innerHTML = '<p>Removing <strong>' + worktreeName + '</strong>...</p>';
    document.getElementById('activationProgress').style.display = 'block';
    document.getElementById('activationResults').style.display = 'none';
    document.getElementById('activationFooter').style.display = 'none';
    document.getElementById('activationSpinner').style.display = 'inline-block';
    modal.show();

    fetch(url, { method: 'DELETE' })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                document.getElementById('activationProgress').style.display = 'none';
                document.getElementById('activationResults').style.display = 'block';
                document.getElementById('activationFooter').style.display = 'flex';
                document.getElementById('activationSpinner').style.display = 'none';
                document.getElementById('activationTitle').textContent = 'Removal Failed';
                document.getElementById('activationStatusAlert').className = 'alert alert-danger';
                document.getElementById('activationStatus').textContent = data.error.message || data.error;
                document.getElementById('activationDuration').textContent = '';
                document.getElementById('hookResultsContainer').innerHTML = '';
                document.getElementById('activationOkBtn').onclick = function() { modal.hide(); };
                document.getElementById('activationOkBtn').focus();
            } else {
                modal.hide();
                location.reload();
            }
        })
        .catch(function(err) {
            document.getElementById('activationProgress').style.display = 'none';
            document.getElementById('activationResults').style.display = 'block';
            document.getElementById('activationFooter').style.display = 'flex';
            document.getElementById('activationSpinner').style.display = 'none';
            document.getElementById('activationTitle').textContent = 'Error';
            document.getElementById('activationStatusAlert').className = 'alert alert-danger';
            document.getElementById('activationStatus').textContent = 'Error: ' + err;
            document.getElementById('activationDuration').textContent = '';
            document.getElementById('hookResultsContainer').innerHTML = '';
            document.getElementById('activationOkBtn').onclick = function() { modal.hide(); };
        });
};

// Update preview as user types
document.getElementById('branchName').addEventListener('input', function(e) {
    var value = e.target.value || 'feature-x';
    var repoName = projectName + '-' + value;
    document.getElementById('branchPreview').textContent = value;
    document.getElementById('dirPreview').textContent = repoName;
});

// Async refresh of worktree dirty/ahead/behind status
fetch('/api/v1/worktrees')
    .then(function(r) { return r.json(); })
    .then(function(resp) {
        var worktrees = (resp.data && resp.data.worktrees) || [];
        worktrees.forEach(function(wt) {
            var el = document.querySelector('[data-worktree-path="' + CSS.escape(wt.Path) + '"]');
            if (!el) return;
            var statusEl = el.querySelector('.wt-status');
            if (!statusEl) return;
            var html = '';
            if (wt.Dirty) {
                html += '<span class="badge bg-danger ms-2" title="Uncommitted changes"><i class="fa-solid fa-pencil"></i> dirty</span>';
            }
            if (wt.Ahead > 0 || wt.Behind > 0) {
                html += '<span class="badge bg-info text-dark ms-2" title="Commits ahead/behind main">';
                if (wt.Ahead > 0) html += '<i class="fa-solid fa-arrow-up"></i>' + wt.Ahead;
                if (wt.Behind > 0) html += '<i class="fa-solid fa-arrow-down"></i>' + wt.Behind;
                html += '</span>';
            }
            if (wt.Detached) {
                html += '<span class="badge bg-secondary ms-2">Detached</span>';
            }
            statusEl.innerHTML = html;
        });
    });
</script>

`)
//line views/worktrees.qtpl:575
	p.StreamFooter(qw422016)
//line views/worktrees.qtpl:575
	qw422016.N().S(`
`)
//line views/worktrees.qtpl:576
}

//line views/worktrees.qtpl:576
func (p *WorktreesPage) WriteRender(qq422016 qtio422016.Writer) {
//line views/worktrees.qtpl:576
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/worktrees.qtpl:576
	p.StreamRender(qw422016)
//line views/worktrees.qtpl:576
	qt422016.ReleaseWriter(qw422016)
//line views/worktrees.qtpl:576
}

//line views/worktrees.qtpl:576
func (p *WorktreesPage) Render() string {
//line views/worktrees.qtpl:576
	qb422016 := qt422016.AcquireByteBuffer()
//line views/worktrees.qtpl:576
	p.WriteRender(qb422016)
//line views/worktrees.qtpl:576
	qs422016 := string(qb422016.B)
//line views/worktrees.qtpl:576
	qt422016.ReleaseByteBuffer(qb422016)
//line views/worktrees.qtpl:576
	return qs422016
//line views/worktrees.qtpl:576
}
